### ISSUE TITLE
Probe is leaking resources

### ISSUE THREAD

**Issue by fincatto** [psi-probe/psi-probe#1026]
**Problem:**
`The following web applications were stopped (reloaded, undeployed), but their
classes from previous runs are still loaded in memory, thus causing a memory
leak (use a profiler to confirm):
/probe`

**Versions:**
Tomcat: 8.5
Probe: 3.0.0.RC1

**Comment by hazendaz** [comment]
@fincatto Can you isolate the issues and possibly submit a PR to fix?

**Comment by fincatto** [comment]
I just uploaded a version of probe on my tomcat and undeployed it. Then find leaks of tomcat manager show the leak.

**Comment by ahumphr** [comment]
This is still happening with  RC2 

Version:
Tomcat: 8.5.23
Server number:  8.5.23.0
OS Name:        Linux
OS Version:     4.4.49-92.14-default
Architecture:   amd64
JVM Version:    1.8.0_131-b11
JVM Vendor:     Oracle Corporation

Probe: 3.0.0.RC2

**Comment by fincatto** [comment]
Closing because no one cares.
