### ISSUE TITLE
Error quartz

### ISSUE THREAD

**Issue by sowe** [psi-probe/psi-probe#1029]
Error with pentaho
i'm following the instruction but i've this error in a log file.

[probe.log.zip](https://github.com/psi-probe/psi-probe/files/853168/probe.log.zip)

`12:36:00.002 ERROR {Probe_Quartz-3} [org.quartz.core.JobRunShell] Job DEFAULT.datasourceStatsJobDetail threw an unhandled Exception: 
org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'collect' on target class [class psiprobe.beans.stats.collectors.DatasourceStatsCollectorBean] fa
iled; nested exception is java.lang.NoClassDefFoundError: org/apache/commons/dbcp/BasicDataSource
        at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:266)
        at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
`

**Comment by hazendaz** [comment]
@sowe What version of tomcat are you using?  Also, with your data sources, do you have it configured to require dbcp?  We don't include the database adaptors themselves.  You would need to add that on your own.  The reason we don't supply them as we simply support way too many which would bloat code and potentially cause other issues.  Please let me know if info I have listed here helpse.  I'll leave this open until I hear back.  Thanks.

**Comment by hazendaz** [comment]
issue long resolved.
