### ISSUE TITLE
Status Graphs look like this when running from a low power computer....

### ISSUE THREAD

**Issue by tonywestonuk** [psi-probe/psi-probe#1035]
When run on my Orange pi (ARM JRE, 32bit), the requests graph looks like this

![image](https://cloud.githubusercontent.com/assets/14888910/24496991/ddc9f07e-1531-11e7-9899-8fcc604f8891.png)

**Comment by hazendaz** [comment]
@tonywestonuk Not sure what you want done with this.  Can you explain what would help here and/or submit a PR addressing your issue?

**Comment by hazendaz** [comment]
@tonywestonuk can you build from master and see if you experience anything different?  I updated one of the dependencies involved in the graphs.  Not sure if that alone would do anything but figured it won't hurt.

**Comment by tonywestonuk** [comment]
Ok, I'll check when I get home.  It appears that for some reason, the charts dataset has a zero, every few intervals.  This is the error - maybe it could be caused by some rounding error, that will skip an element of an array that is used to build the chart.... I did look through the code, but alas it was beyond me.

If the chart is made of 400 divisions....with the count of each unit defined in an array defined of 400 elements, which counts how many requests per interval...  If the resolution provided by server time is only 300 divisions,  and so a conversion is made using  something like intervalBin[400*I/300] , I would imagine this would produce a graph looking like the above, with ever 4th bin missed.

**Comment by hazendaz** [comment]
closing as old and some work was done around that area.  If still an issue, feel free to reopen.
