### ISSUE TITLE
github.global.oauth2Token

### ISSUE THREAD

**Issue by hazendaz** [psi-probe/psi-probe#1050]
@MALfunction84 Over on travis-ci, this token exists.  Seems like it's possible you might have added it.  In the build, this error shows up below.  I presume there is a problem with that token and I'm not sure what it is there for.  I'm leaning towards deleting it but wanted to reach out to see what its purpose is for currently.

```
Setting environment variables from repository settings
$ export github.global.oauth2Token=[secure]
The previous command failed, possibly due to a malformed secure environment variable.
Please be sure to escape special characters such as ' ' and '$'.
For more information, see https://docs.travis-ci.com/user/encryption-keys.
```

**Comment by MALfunction84** [comment]
I believe the token acts as a shared secret to prove to Travis that Github is the one requesting a new build. Removing it would probably break Travis.

If you ever need to change it, it's defined [here](https://github.com/psi-probe/psi-probe/settings/hooks/4407578).

**Comment by hazendaz** [comment]
@MALfunction84 Thanks.  You answered my suspicision.  That isn't needed.  It was actually causing a build exception being there.  I had not seen that on any other repos I work on.  I removed it and builds all still successfully run.  Travis is otherwise still attached.  That is done via profile over on travis then still listed.  The build itself didn't need a further token.  It's behind the scenes so to speak here.
