### ISSUE TITLE
java.lang.NoClassDefFoundError: ch/qos/logback/core/status/WarnStatus

### ISSUE THREAD

**Issue by joaocarlos86** [psi-probe/psi-probe#1055]
I'm getting the following exception when trying to use probe (psi-probe-web-3.0.0-20170427.052447-35.war, but it occur if I build it from scratch) with Tomcat 7.0.77:

Exception in thread "Probe_Quartz-1" java.lang.NoClassDefFoundError: ch/qos/logback/core/status/WarnStatus

I've tried to put logback-classic and logback-core (1.2.3) in lib folder of tomcat but have no success, still got the same exception.

**Comment by hazendaz** [comment]
@joaocarlos86 You shouldn't need to do that. I'm testing with 7.0.75 currently and not encountering the issue at all.  Can you test this in a stock tomcat with no other wars?  That should work without issue.  If that works, then need to know what you have in there that might be causing the issue.  I can upgrade to 7.0.77 to try again if stock doesn't work out of the box.  Please let me know your findings.

**Comment by joaocarlos86** [comment]
@hazendaz thanks for your answer. Without any others wars, probe runs well, I will investigate the side effect of my apps...
