### ISSUE TITLE
Requests by Application on application statistics, shows (MS) in label

### ISSUE THREAD

**Issue by tonywestonuk** [psi-probe/psi-probe#1065]
Requests by App, is a count of requests per 4 minutes.  (MS) - Milliseconds - is used on the Response time charts - it makes no sense having it here!

![image](https://cloud.githubusercontent.com/assets/14888910/25668480/ab7a5dd6-301e-11e7-8d69-1a99e5b67b63.png)

**Comment by hazendaz** [comment]
@tonywestonuk Can you submit a pull request to fix this?  I'll merge right away.

**Comment by hazendaz** [comment]
I have fixed this on Master and it will be included in the next release.
