### ISSUE TITLE
NPE in probe when run with web app that uses log4j2 logging

### ISSUE THREAD

**Issue by j-renkel** [psi-probe/psi-probe#1084]
If you deploy probe and a web app that uses log4j2 logging to the same tomcat, you get a null pointer exception when you click on the probe "Logs" tab.

The probe log file with the NPE and the web app's log4j2.xml file are in the attached .zip file:

[probe_bug.zip](https://github.com/psi-probe/psi-probe/files/1128575/probe_bug.zip)

If I can provide any other information that would help in resolving this, or ya need small experiments to be run, just let me know.

Thanks in advance,

Jim

**Comment by hazendaz** [comment]
@j-renkel is it possible for you to supply a small sample WAR that causes this behaviour?  That would help me a lot to diagnose and fix the issue.  I don't use log4j2 myself and assumed it was working as someone else provided the code originally.

**Comment by j-renkel** [comment]
I've added to the pre4vious .zip file a "hello-log4j2.war" file:

[probe_bug.zip](https://github.com/psi-probe/psi-probe/files/1132171/probe_bug.zip)

If I deploy only this .war file (and probe) to tomact, I don't get the NPE, but the app does not appear on the logs tab.

If I deploy this .war file and the securityServices.war file that prompted this bug report to tomcat, I do get the NPE, and neither app appears on the logs tab.

Hope this helps. Maybe finding out and fixing why the apps are not listed on the logs tab will coincidentally fix the NPE? One can hope! :-)

If there's anything else I can do, just let me know.

Jim

**Comment by hazendaz** [comment]
others had same issue due to missing war file.  Poke around issues to find resolution.  not issue with psi probe currently.  closing.
