### ISSUE TITLE
Quartz timer threads not shut down cleanly

### ISSUE THREAD

**Issue by mdeggers** [psi-probe/psi-probe#1089]
Platform: CentOS 6.9 64 bit
JVM:       1.8.0_141-b15
Tomcat:  7.0.79 (downloaded from tomcat.apache.org)
psi-probe: * master 7ed6eacd Merge pull request #1087 from hazendaz/master
When I stop Tomcat (service tomcat-name stop) I get the following in my catalina.out file:

SEVERE: The web application [/probe] appears to have started a thread named [Probe_Quartz-2] but has failed to stop it. This is very likely to create a memory leak.

Jul 21, 2017 9:24:44 AM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
SEVERE: The web application [/probe] appears to have started a thread named [Probe_Quartz-4] but has failed to stop it. This is very likely to create a memory leak.

This will definitely cause a memory leak if I redeploy psi-probe.

**Comment by hazendaz** [comment]
Sounds like we are missing the shutdown hook for quartz.  I don't have much time to look into this now but if you are fully stopping tomcat, then the error is rather meaningless as memory leak won't exist at that point.  However, we should ook at fixing this.  If you can figure out what is needed, most certainly push a pull request and I'll take a look.

**Comment by mdeggers** [comment]
Jeremy,,

I agree, this isn't much of an issue if I shut down Tomcat when updating
probe (which happens very infrequently). I'll try to take a look at it in
the next few days. I have some other production issues to worry about first
:-(.

Thanks again,
Mark
/mde/

**Comment by hazendaz** [comment]
closing for now.  quartz was dead for a number of years, its back alive and I had some side code trying to address this.  The new one may handle better, if still an issue can address in a separate ticket.
