### ISSUE TITLE
IllegalStateException when shutting down Tomcat

### ISSUE THREAD

**Issue by mdeggers** [psi-probe/psi-probe#1090]
Platform: CentOS 6.9 64 bit
JVM: 1.8.0_141-b15
Tomcat: 7.0.79 (downloaded from tomcat.apache.org)
psi-probe: * master 7ed6eac Merge pull request #1087 from hazendaz/master

When shutting down Tomcat I get an IllegalStateException followed by a ClassNotFoundException. This appears to be related to the Quartz timer thread that doesn't get shut down cleanly.

Snippet from my catalina.out file is included.
[ps-probe-snippet.txt](https://github.com/psi-probe/psi-probe/files/1166192/ps-probe-snippet.txt)

**Comment by hazendaz** [comment]
This appears to me that you might possibly have a mixture of logback jars in your tomcat/lib folder which conflict with psi-probe usage of logback.  I can isolate and potentially fix this by switching all of probe logging to use tomcat-juli provided by tomcat-slf4j-logback project which I also maintain so we still get logback usage without issues like this.  For now though, can you confirm if you have other logback libraries in your tomcat/lib?

**Comment by mdeggers** [comment]
I have no other logback libraries in $CATALINA_BASE/lib or
$CATALINA_HOME/lib. The only foreign library I have there is the mysql JDBC
driver.

Thanks for looking at the issues.

Mark
/mde/

**Comment by hazendaz** [comment]
closing as not since reported as an issue.  issue looking again seems misconfiguration of libraries as originally noted.
