### ISSUE TITLE
tomee data souce not listed in Data Sources tab

### ISSUE THREAD

**Issue by dmcletchie** [psi-probe/psi-probe#1097]
Hi,

I hope that this isn't a known issue or a config problem.

I'm using tomee, and I'm defining a datasource.  If I define it in a context.xml file, then PSI probe works as expected.  I see the data source in the global data source tab.  if I define it tomee.xml, then the datasource is not listed.  The resource does appear in applications -> resources.  I can click on it & test the connection & it works. 

I'd like to see the data source under the global datasources tab, so that I can monitor the use of my connection pool.  I've debugged & fixed the problem locally

It looks like the TomcatJdbcPoolDatasourceAccessor should work, except that the resource class is not a "org.apache.tomcat.jdbc.pool.DataSource", it is a "org.apache.tomee.jdbc.TomEEDataSourceCreator$TomEEDataSource".  the TomEEDataSource extends the DataSource.   TomcatJdbcPoolDatasourceAccessor isn't working since it's checking the class name, and it does not match for a subclass.   So, I could either:
* modify TomcatJdbcPoolDatasourceAccessor to include the second class name, 
* remove the class name comparison leave the instanceof as the only check
* create a new DatasourceAccessor just like TomcatJdbcPoolDatasourceAccessor  but it a different string constant in canMap().  

(If nobody suggests a preference, I guess I'll do the first one.)

I'm new to github, so I'm not sure what protocol is or how to go about getting this fix in place.  Any pointers would be great!  Thanks!

**Comment by hazendaz** [comment]
New class would be best.  Your option 3.  Feel free to make fix in your fork then send a pull request.  I'll merge it fairly quickly.  Thanks for finding the issue.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dougwm** [comment]
I have the same problem if I configure a dbcp2 datasource inside of tomee.xml.  So, if you're OK with the way that this one works, I'll create another issue & another pull request.

**Comment by hazendaz** [comment]
Hmmm...now your option 1 is sounding better.  If you want go ahead and send a PR covering both for me to look at.  Option 1.  Then we can go from there.

Get Outlook for Android<https://aka.ms/ghei36>



________________________________

**Comment by hazendaz** [comment]
@dougwm I'm good with what you did.  Go ahead and raise a pull request to provide support for dbcp2 usage.

**Comment by hazendaz** [comment]
long addressed, closing.
