### ISSUE TITLE
port redirection 8080 to 80

### ISSUE THREAD

**Issue by geethapuc** [psi-probe/psi-probe#1116]
Hi ,

We've configured probe for our tomcat application, the app is launched in aws elb, so port 8080 is redirected to 80.  Please suggest redirecting to port 80.  for example, www.myapp.com, proble should be accessed like: www.myapp.com/probe

thanks,
sagi

**Comment by hazendaz** [comment]
@geethapuc I'm not quite sure what you are asking.  The context depends on the WAR that you are using.  So if pulled from maven central it would be psi-probe or if from here downloaded it would be probe.  Redirect would just need the same context.  The port is irrelevant based on the overall setup.  Can you help me understand what your need is?  Or does this information help?

**Comment by hazendaz** [comment]
ok ask was to have this somehow redirect elsewhere.  That isn't possible.  This is how you start up tomcat and has nothing to do with this app.  Port 80 is blocked now anyways.  Port 443 is possible (ie https only now).  But still its a tomcat setup not a psi probe issue.
