### ISSUE TITLE
Support for multiple Tomcat services

### ISSUE THREAD

**Issue by aabiabdallah** [psi-probe/psi-probe#1139]
Probe does not seem to list all application running accross multiple Services in Apache Tomcat 8.5. Is this the expected behavior?

Tomcat Configuration:
```
<Server port="8005" shutdown="SHUTDOWN">
  ...
  <Service name="Apps">

    <Connector port="8080" protocol="HTTP/1.1" connectionTimeout="20000" redirectPort="8443" />
    <Connector port="8009" protocol="AJP/1.3" redirectPort="8443" />

    <Engine name="Catalina" defaultHost="localhost">
      <Realm className="org.apache.catalina.realm.LockOutRealm">
        <Realm className="org.apache.catalina.realm.UserDatabaseRealm" resourceName="UserDatabase"/>
      </Realm>
      <Host name="localhost" appBase="webapps1" unpackWARs="true" autoDeploy="true">
        <Valve className="org.apache.catalina.valves.AccessLogValve" directory="logs"
               prefix="localhost_access_log" suffix=".txt"
               pattern="%h %l %u %t &quot;%r&quot; %s %b" />
      </Host>
    </Engine>
  </Service>
  
  <Service name="Probe">
  
    <Connector port="8081" protocol="HTTP/1.1" connectionTimeout="20000" redirectPort="8443"/>
    
    <Engine name="Catalina" defaultHost="localhost">
      <Realm className="org.apache.catalina.realm.LockOutRealm">
        <Realm className="org.apache.catalina.realm.UserDatabaseRealm" resourceName="UserDatabase"/>
      </Realm>
      <Host name="localhost" appBase="webapps2 unpackWARs="true" autoDeploy="true"/>
    </Engine>
  </Service>
</Server>
```

**Comment by hazendaz** [comment]
Is that feature new on tomcat 8.5+ and 9.0+?  If not I'll presume issue on all versions.  I'll certainly take a look at this.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by aabiabdallah** [comment]
The haven't checked versions older than Tomcat 6 but I know it is supported since Tomcat 6+.

**Comment by FrankS77** [comment]
Hey, that would definitely what I need! Any news on this? Not possible with tomcat manager yet (Tomcat 9)

**Comment by BugHunterPhilosopher** [comment]
I'd definitively need that one too. Any news on that topic, please?

**Comment by hazendaz** [comment]
would need help from community to write code for such a feature.  As many may be noticing I'm closing nearly all tickets as there has been no followup in general on all parties and I'm one person that is maintaining this but don't use it making it really hard for me to provision out needs I don't have :(  I do agree this is needed though, so if super important please open a new ticket and please either help get a PR or get enough information together that would help me solve it.
