### ISSUE TITLE
Download thread dump?

### ISSUE THREAD

**Issue by nikowitt** [psi-probe/psi-probe#1146]
Hi,
is it possible to download a dump of all running threads? From what I see, it is only possible to directly check the trace per thread, but e.g. when the server is very unresponsive or about to crash, it is not easily possible to just dump all threads in a text file?

Best regards,
Niko

**Comment by hazendaz** [comment]
seems like a good thing but not seeing a lot of want for it and pretty old ask, closing for now.  If someone wants to try to add support, great, but don't see it happening currently.
