### ISSUE TITLE
Deploy war to central repository

### ISSUE THREAD

**Issue by mandrachek** [psi-probe/psi-probe#1155]
The gradle-gretty-plugin (https://github.com/gretty-gradle-plugin/gretty) supports deploying additional .war files via maven or ivy dependencies in a "farm" (https://gretty-gradle-plugin.github.io/gretty-doc/Farm-web-app-list.html), which makes it pretty easy to setup deployment of psi-probe during development. Currently, this requires downloading the war file, and adding to your project, and referencing it as a file, or installing it manually in your local maven repository. 

This could be made even easier if the war artifact was deployed to maven central/jcenter, and then it could be referenced as a dependency, for example:

farm {
   jvmArgs = ["-Djava.awt.headless=true","-Dcom.sun.management.jmxremote=true"]
   servletContainer = 'tomcat8'
   enableNaming = true
   realm 'auth'
   realmConfigFile 'tomcat-users.cfml'
   webapp project
   // file based
   // webapp projectDir.toString() + File.separator + "probe.war"
   webapp 'com.github.psi-probe:probe:3.0.0@war'
}

**Comment by hazendaz** [comment]
It's already deployed to central.  I just haven't released since August of last year.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hazendaz** [comment]
[probe](http://search.maven.org/#search%7Cga%7C1%7Cpsi-probe)
