### ISSUE TITLE
Can't see perm gen in the system - memory utilization tab

### ISSUE THREAD

**Issue by ppsanyal1** [psi-probe/psi-probe#1156]
![screen shot 2018-04-03 at 11 08 40 am](https://user-images.githubusercontent.com/31861920/38267121-6542b2e6-372f-11e8-93f6-1acd9c7d3db9.png)

Hi,

Please refer to the screenshot. We can't see Perm Gen in the memory utilization tab, although we can see Eden, Survivor space and Old Gen.

Can you please explain why?

Thanks,
Partha

**Comment by hazendaz** [comment]
Which jdk version are you using?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hazendaz** [comment]
Perm gen doesn't exist in jdk8+.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ppsanyal1** [comment]
Ok thanks! Didnt have that idea.
