### ISSUE TITLE
Update documentation referencing "probe.war"?

### ISSUE THREAD

**Issue by bknowles** [psi-probe/psi-probe#1175]
I found the article at https://groups.google.com/forum/#!msg/psi-probe/EYp9Fzxtl-E/0m3ycwucIAAJ which tells us that we can take the snapshots under https://oss.sonatype.org/content/repositories/snapshots/com/github/psi-probe/psi-probe-web/ and then rename them as "probe.war" so that they can be deployed as described in the documentation.

But I was wondering if maybe it would make sense to update the documentation to reflect this fact, instead of making people try to guess where the WAR files can be found, and what they might have to be renamed as in order to function?

**Comment by hazendaz** [comment]
I believe that is on the read me.  Also this is in maven central.  If clarity is missing on read me feel free to raise a pull request.  Thanks.

Renaming isn't actually necessary.  That's only to shorten the name. ??

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bknowles** [comment]
The README.MD does have a link for where the snapshots can be downloaded, that's certainly true.

But from there, it doesn't tell you how the snapshots need to be named.  And depending on "maven central" doesn't help anyone who doesn't know what maven central is or how to use it.

I think the steps outlined in the referenced article are actually quite important for deploying the latest snapshot if you're not using maven central, and I think it would be good for the project for that information to be replicated here, in the same README.MD.

**Comment by hazendaz** [comment]
@bknowles Readme has been updated to reflect downloads.  Please also note that this was always on github releases as well and that might not have been clear for those that do not understand the links / badges github provides so I duplicated a quick info area for that as well as where to grab from central with notes on the central locations that renaming is ok.  Please let me know if you would like to see more or if you have another idea, PRs are always welcome :)

**Comment by bknowles** [comment]
That's definitely where I would have expected to see the link, and I can confirm that I had mistakenly downloaded a different file and renamed it as probe.war.  So, this may well have been the cause of all the problems that I have seen.

Let me give this version a try and see if it solves the problems I was seeing.  Thanks!

**Comment by hazendaz** [comment]
closing as done.
