### ISSUE TITLE
Not able to access catalina.out  in browser however can download

### ISSUE THREAD

**Issue by whitehallfinance** [psi-probe/psi-probe#1190]
Hi Team,

I am trouble accessing /tomcat-7.0.42/logs/catalina.out and always getting below error message  stating "The page you requested does not exist on this server. Please use the navigation bar to locate the area you require." however i could download that.Please suggest what could be the root cause of this issue.

PSI Probe - Version 3.0.0 

Thanks
Gautam Sharma

**Comment by hazendaz** [comment]
Can you try 3.1.0?  It is Jdk8 on newer version.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by whitehallfinance** [comment]
Thanks for reply however we are bound to use JDK 1.7 :(
Anything we can do apart from 3.1.0 version upgrade?

**Comment by hazendaz** [comment]
The below exception I was recently made aware of.  I had not noticed it only becaues I overload log4j2 to slf4j in my usage.  I can back port a fix for that.  All the fix does is change the scope of logging to debug as is the case with all lother logger types.

I'll check this issue out on tomcat7 as soon as I can.

**Comment by maticomba** [comment]
Hello there... same issue here with tomcat7 and jdk 1.7. Just let me know if you need more info. Thanks in advance...

**Comment by dguerrar** [comment]
same issue for me on tomcat 8.5.37 and jdk 8

**Comment by hazendaz** [comment]
closing as catalina.out is available now.
