### ISSUE TITLE
 Illegal reflective access by com.thoughtworks.xstream.core.util.Fields

### ISSUE THREAD

**Issue by mshedsilegx** [psi-probe/psi-probe#1191]
Platform: Probe 3.1.0 / tomcat 9.0.10 / JDK 10.0.1
Probe seems to be functional, but throwing a warning at startup:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.thoughtworks.xstream.core.util.Fields (file:/instances/webapps/probe/WEB-INF/lib/xstream-1.4.10.jar) to field java.util.TreeMap.comparator
WARNING: Please consider reporting this to the maintainers of com.thoughtworks.xstream.core.util.Fields
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by shanmukha27** [comment]
Any update on this issue, please?

**Comment by hazendaz** [comment]
As I noted before.  This is NOT an issue with psi probe.  Its xstream.  That team has to release a patch for this to go away.  This is just a warning.  Groovy has the same issues.  There is nothing I can do about their internal usage.  Please refer to xstream team. Thanks.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hazendaz** [comment]
old issue, closing.  xstream has been updated many times since and issue not reported since.
