### ISSUE TITLE
The log4j2 log file appears in the list, but it does not open properly. Please help me.

### ISSUE THREAD

**Issue by eosos7** [psi-probe/psi-probe#1194]
The log4j2 log file appears in the list, but it does not open properly. log4j, and logback will work normally.

**<> Environment**
> CentOS release 6.7 (Final)
> Tomcat-8.5.23.0
> Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
> probe-3.1.0

**<> Clicking on the log file calls the following URL**
>http://xxx.xxx.xxx/probe/logs/follow.htm?logType=log4j2&webapp=%2f&context=true&root=true&logIndex=error

**However, only the following message is displayed on the screen:** The page you requested does not exist on this server. Please use the navigation bar to locate the area you require.

**<> In the probe.log file, only the following error is displayed.**
>11:59:48.312 ERROR {http-nio-8800-exec-4} [p.c.logs.AbstractLogHandlerController] log4j2 root log not found

**<> In the path 'WEB-INF/classes', the log4j2.xml file is well defined**

Please help me.

**Comment by hazendaz** [comment]
Hi @eosos7, you might want to look around at prior pull requests for log4j2 being brought in.  I don't have any sample projects that even use log4j2 as my preference is slf4j/logback.  In those older PRs, you would have much better luck reaching out to those contributors to find a solution.  Then any PR that comes this way I will be happy to merge.  Thanks and Good Luck!

**Comment by eosos7** [comment]
Thank you for your reply.

**Comment by dguerrar** [comment]
Dear all,

I am facing the same issue. Any option?

Thanks!

**Comment by dogilvie** [comment]
Hey,

I tracked this down to a missing dependency on log4j-web in my app.

Psi-probe is trying to load WebLoggerContextUtils and gets stumped by a ClassNotFoundException. This shows up in the probe log if you turn on probe debug logging.

So, add this to your maven dependencies for your app  (you might need to add a version if not using spring boot):

        <dependency>
		    <groupId>org.apache.logging.log4j</groupId>
		    <artifactId>log4j-web</artifactId>
	</dependency>

**Comment by hazendaz** [comment]
closing as answered by missing lib.
