### ISSUE TITLE
Unable to manually specify which tomcat adapter to use. Needed for tomcat security hardening

### ISSUE THREAD

**Issue by Aaron-LS** [psi-probe/psi-probe#1197]
Currently there is no mechanism other than code customization to force the application to use a specific tomcat adapter. Security hardening of tomcat often requires that the ServerInfo be altered or removed which causes psi-probe to crash. 

Specifically the ContainerWrapperBean.java class method public void setWrapper(Wrapper wrapper) {} fails to load an adapter if the server info cannot be extracted.

**Comment by Aaron-LS** [comment]
Added a pull request with extended code to check a properties file to force load a specific tomcat adapter.  Got the idea from this thread:
https://groups.google.com/forum/#!topic/psi-probe-discuss/6mUeSO7Phug

**Comment by hazendaz** [comment]
closing as addressed in easier way.  'adapters.properties' in src/main/resources states the order.
