### ISSUE TITLE
Log Tab Application Error

### ISSUE THREAD

**Issue by rbugby** [psi-probe/psi-probe#1207]
New install on Tomcat 8.5 on Windows 10. Every thing works except Log Tab. 

[localhost.2018-10-13.log](https://github.com/psi-probe/psi-probe/files/2475853/localhost.2018-10-13.log)
[catalina.2018-10-13.log](https://github.com/psi-probe/psi-probe/files/2475852/catalina.2018-10-13.log)
[probe.log](https://github.com/psi-probe/psi-probe/files/2475851/probe.log)

**Comment by hazendaz** [comment]
I would look more into the illegal state exceptions in your logs against your app and remove psi probe until you get that addressed.  Otherwise best I can tell, your constainer has stopped working when psi probe is trying to do other tasks as there are quartz schedulers that run often.

**Comment by hazendaz** [comment]
closing as old and no further info on this.
