### ISSUE TITLE
How to show tomcat access-log in logs tab?

### ISSUE THREAD

**Issue by distancelin** [psi-probe/psi-probe#1246]
the logs tab shows catelina.out and probe.log,bug access-log is not shown,how to do this please?

**Comment by hazendaz** [comment]
Currently it's not supported.  There should be issues on that already.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hazendaz** [comment]
For any upsupported logs, add them to the stdout.properties file in the WAR to make them show up. They cannot be modified but will show.
