### ISSUE TITLE
Problem masking tomcat version

### ISSUE THREAD

**Issue by nicoyn** [psi-probe/psi-probe#1260]
Hi there,

In our production servers (TOMCAT 8.5.xxx), we mask the server.info variable via the file org/apache/catalina/util/ServerInfo.properties in  catalina.jar .

The workaround was about changing the spring-probe-resources.xml in the WEB-INF of the probe.war.

But this file disappeared in the current probe version, and now it seems we can't play anymore with this feature (I've found this somewhere in the current code).

```
/**
   * Sets the force first adapter. Setting this property to true will override the server polling
   * each adapter performs to test for compatibility. Instead, it will use the first one in the
   * adapterClasses list.
   *
   * @param forceFirstAdapter the new force first adapter
   */
  // TODO We should make this configurable
  @Value("false")
  public void setForceFirstAdapter(boolean forceFirstAdapter) {
    this.forceFirstAdapter = forceFirstAdapter;
  }
```

I'm stuck here, anyone got an idea ? (other than recompile to put my tomcat version directly in the code...)

Thanks !

**Comment by hazendaz** [comment]
Just make sever.xml report back some arbitrary value as the server name.  That way you mark what you need without breaking psi probe ability to run properly.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by radboud-asselman** [comment]
@nicoyn Did you fix the problem? We have the same issue.

**Comment by nicoyn** [comment]
Nope, haven't found the correct syntax to put in my server.xml !
So my tomcat version is not hidden for now... (It's ok for our MZ servers).

**Comment by hazendaz** [comment]
Use https://github.com/psi-probe/psi-probe/blob/master/psi-probe-web/src/main/resources/adapters.properties, to control and rebuild.  This was recently made available.  It may not be in released version yet but is coming soon.
