### ISSUE TITLE
Application encountered an unexpected error. Please check the Tomcat logs.

### ISSUE THREAD

**Issue by ftsafezhaojing** [psi-probe/psi-probe#1263]
after i start probe,it can not visit and display the follow exception message  in page,but the catalina.out 
and probe.log in logs of tomcat has no error messge. 

"Application encountered an unexpected error. Please check the Tomcat logs. We will greatly appreciate it if you share the information with us. Sharing this information through our issue tracker or our discussion board will help us find and correct this problem as soon as possible!"

i don't know how to do ,who can tell me

**<my pc's Environment>**
CentOS Linux release 7.5.1804 (Core)
java version "1.8.0_181"
 apache-tomcat-9.0.16

**Comment by hazendaz** [comment]
What version are you using, what tomcat, what system?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hazendaz** [comment]
@ftsafezhaojing You may want to check all logs as the only time that occurs, it wrote some form of logs.  They logs may or may not be available in the UI.

**Comment by john182** [comment]
I have the same problem

**Comment by hazendaz** [comment]
any stack trace or info would help here.

**Comment by hazendaz** [comment]
closing as catalina.out displays fine.
