### ISSUE TITLE
Help, loading htm in production environment is very slow, it takes about 10S

### ISSUE THREAD

**Issue by nanjunyu** [psi-probe/psi-probe#1297]
In the test environment, the normal loading is very fast, but the production is very slow. Through the browser debugging, I found that the html loading took almost 10s, every time, such as http://xxxx:8080/log/logs/list .htm, found list.html loaded for 10 seconds, tomcat version is 7, java version is 8, the war package is directly downloaded on the github version 3.0, how to troubleshoot this question?

**Comment by hazendaz** [comment]
@nanjunyu Logs are read through the classpath so I suspect your production instance has a significantly larger set than you have in your development environment.  This is the first report I believe I've heard about this part being slow.  I've never seen it be slow myself.  Normally logs are a top question due to lack of showing them since it goes through the classpath.

**Comment by nanjunyu** [comment]
> @nanjunyu通过类路径读取日志，因此我怀疑您的生产实例具有比您在开发环境中更大的集合。这是我相信我听说过这部分很慢的第一份报告。我自己从未见过它很慢。通常，日志是一个最重要的问题，因为它不通过类路径显示它们。

Thank you!
    Not only is the log menu slow, but I click on other menus is also very slow, such as the application of the home page, Data Sources, etc. When I click on these menus, the code will also read all the log files under tomcat logs, production The number of log files under the environment tomcat is relatively large, and it cannot be cleared. Is there any recommended solution?
![QQ图片20190415144143](https://user-images.githubusercontent.com/23097168/56112351-6b7ea480-5f8d-11e9-9226-57b1b2c36576.png)
![QQ图片20190415144149](https://user-images.githubusercontent.com/23097168/56112359-6f122b80-5f8d-11e9-9d35-e3ecb599ccd7.png)

**Comment by hazendaz** [comment]
I'll likely need some help on fixing this type of issue.  I dont know why logs are checked when on other tabs.  There is also considerable reflection all over supporting far too much legacy.  I'm going to start removing some old support and start requiring users use recent libraries.  That will help some bit not sure how much.  I'm also going to consider dropping all obsolete support such as log4j1.  Some wont like that but at the level this library is downloaded, those affected by extreme legacy usage really can just use old versions.

Any more research you can perform on this issue will help greatly.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hazendaz** [comment]
Closing issue as not repeatable and we are many versions past 3.0 at this point in time.
