### ISSUE TITLE
Add JMX console functionality

### ISSUE THREAD

**Issue by GoogleCodeExporter** [psi-probe/psi-probe#13]
```
It would be great to have jconsole like functions within psiprobe.
Mostly you do not get the ports open on production machines for JMX,
therefore it would fit perfectly to this app.

BTW: Great idea to fork the dead lambdaprobe and continue to work on it!
```

Original issue reported on code.google.com by `robertos...@gmail.com` on 20 Apr 2009 at 9:25
- Blocking: #98, #98

**Comment by jander99** [comment]
Scanning Milestone-2.4.0

Yeah..this isn't something for 2.x.

**Comment by hazendaz** [comment]
Closing old issues unlikely to be addressed.

**Comment by mayproperty** [comment]
Closing an old problem is impossible to deal with.
https://perumahancirebon.id
