### ISSUE TITLE
Ask for authentication in index page

### ISSUE THREAD

**Issue by najmisyahir** [psi-probe/psi-probe#1306]
I have a problem with my psi-probe, when accessing the apps it instantly show the information of all the installed apps on the tomcat web server. Is there any way to ask for authentication when accessing it?

**Comment by hazendaz** [comment]
Did you setup the tomcat users configuration properly?  It should be always prompting for logon. I haven't ever seen it not do so.  If you were already logged in on another tab in the browser it would remain logged in.

**Comment by hazendaz** [comment]
closing as general usage does ask for password.
