### ISSUE TITLE
Probe 3.2.0 LDAP JNDIRealm problem

### ISSUE THREAD

**Issue by dasarro23** [psi-probe/psi-probe#1316]
In PSI-Probe 3.0.0 I had the possibility of authenticating via LDAP when having configured an LDAP realm in Tomcat server.xml, this was controlled with configuration in probe web.xml and spring-probe-security.xml adapting the name of the roles, without however in version 3.2.0 this option has disappeared and I can not adapt this version to authenticate with LDAP, any ideas?

Thanks!!

**Comment by hazendaz** [comment]
Legacy XML was replaced with java code.  Any prior setup as suggested was simply a hack that wasn't supported.  If you would like support you may have to build it and it's probably easy to do.  Look in the 'core' package root java files for all configuration.  I'd be happy to merge and release the support for ldap.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hazendaz** [comment]
closing as we no longer use XML based.  All spring is annotation based now.  If any feature is needed to configure as sounds like some custom adjustments we don't know about, best option would be to raise a PR to introduce ability for such feature.
