### ISSUE TITLE
tomcat 9 - connector view, connector shown twice

### ISSUE THREAD

**Issue by xarius74** [psi-probe/psi-probe#1337]
Hi,

On Connector View, connectors are shown twice and Table below image are only shown for one of the connector. For second connector message "no processors" is displayed.

I tried multiple combinations of probe and host version and so on. It looks like combination of tomcat 9 und linux makes a problem??

Has anybody noticed similar problems?

-----------------------------------
CONFIG A)  - WORKS
Probe Version:  Version 3.2.0 (built at 2018-12-20T22:06:41Z
Tomcat Version: 9.0.12
Java Version: build 1.8.0_121-b13
Host Version: Windows 7

CONFIG B)  - DOES NOT WORK
Probe Version:  Version 3.2.0 (built at 2018-12-20T22:06:41Z
Probe Version 3.0.0.RC2  <-- tried this version too.
Tomcat Version: 9.0.12
Java Version: openjdk version "1.8.0_191"
Host Version: SUSE Linux Enterprise Server 12 (x86_64) SLES 12 SP 4
![ProbeProblem](https://user-images.githubusercontent.com/51698981/59259322-de2c9900-8c39-11e9-977f-3ed43dc43d69.jpg)

CONFIG C)  - WORKS
Probe Version 3.0.0.RC2
Tomcat Version: Apache Tomcat/8.0.50
Java Version: OpenJDK Runtime Environment  1.8.0_171-b11  OpenJDK 64-Bit Server VM) 
Host Version: SUSE Linux Enterprise Server 12 (x86_64) SLES 12 SP 3

**Comment by pizzit** [comment]
Same problem with Tomcat 8.5.39 and Tomcat 8.5.41 

Also with Ajp Connector BIO, NIO or NIO2

**Comment by xarius74** [comment]
After comparing MBeans of Tomcat 9 (Windows <-> Linux). 
There is an additional child MBean "SocketProperties" for Connector in ThreadPools. 

I think it is possible to fix it with a little change in ContainerListenerBean.
OLD Line 147: 
Set<ObjectInstance> threadPools =
        server.queryMBeans(new ObjectName(serverName + ":type=ThreadPool,*"), null);
NEW Line 147:
    Set<ObjectInstance> threadPools =
        server.queryMBeans(new ObjectName(serverName + ":type=ThreadPool,name=\"*\""), null);

**Comment by hazendaz** [comment]
Can you make the change and confirm if it works the raise a pull request?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by xarius74** [comment]
I did change and it works. Provided pull request contains changed lines...

**Comment by hazendaz** [comment]
Thanks.  I'll get it merged and released this weekend.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hazendaz** [comment]
Issue resolved on master.  Closing.
