### ISSUE TITLE
Authentication twice

### ISSUE THREAD

**Issue by veix90** [psi-probe/psi-probe#1392]
Hi!
I have installed probe and configured it. The problem is, when I log into it:
1) Enter username and password to - https://probeserver.domain.com:8443/probe
2) password is asked again
3) I press Cancel
4) I enter username and password again and press Enter
5) Password is asked again
6) I press Cancel
7) I do refresh
8) I am logged in.

Is there some more logging to turn on or how to solve such behaviour?

Tomcat 7.0.76
CentOS 7

**Comment by hazendaz** [comment]
I've never seen that occur with standard setup using tomcat-users.xml.  Is your setup different?

**Comment by hazendaz** [comment]
Closing issue as no other reports, unable to reproduce, and tomcat 7.0.76 is rather old by roughly 2 years.
