### ISSUE TITLE
Email notifications triggered by memory usage

### ISSUE THREAD

**Issue by GoogleCodeExporter** [psi-probe/psi-probe#14]
```
Request for enhancement:

Add the ability to monitor HeapSize, PermGen Space etc. and inform by email
if limits are exceeded
```

Original issue reported on code.google.com by `robertos...@gmail.com` on 20 Apr 2009 at 9:29
- Blocking: #108

**Comment by jander99** [comment]
Scanning Milestone-2.4.0

A feature like this needs to have a data store of some kind.  What happens when the JVM is restarted?  Let's figure out a proper feature for monitoring and alerting in 3.x.

**Comment by MALfunction84** [comment]
We may just drop the entire thing and make Probe more Nagios-friendly. No use reinventing the wheel.

**Comment by jander99** [comment]
We should have a few alert buckets to place different stats into, that can
then: email, nagios, pagerduty, customhook, etc.

**Comment by MALfunction84** [comment]
I'm talking about exposing more of this information in a way that can be easily consumed by third-party monitoring/alerting tools. Probe itself wouldn't send out any notifications. Those other tools would.

**Comment by diogosantana** [comment]
Vote to drop notifications.

**Comment by hazendaz** [comment]
closing old issue.
