### ISSUE TITLE
Disabling Auto-commit

### ISSUE THREAD

**Issue by GoogleCodeExporter** [psi-probe/psi-probe#155]
```
Should it be possible to disable auto-commit when you make an SQL request ?

Release : 2.1.0

```

Original issue reported on code.google.com by `alain.ve...@yahoo.fr` on 12 Oct 2010 at 6:37

**Comment by hazendaz** [comment]
closing as old.  think issue though is not with this as far as I know but rather your DB allowing auto commit.  you should start a transaction first and end it when done.  think it allows that  but if still issue would need new ticket and help to fix.
