### ISSUE TITLE
There was an error when I run this project in idea

### ISSUE THREAD

**Issue by valten-hyl** [psi-probe/psi-probe#1558]
I clone and use both the master branch, tomcat9.0.24. I package it with command "mvn clean package -Dmaven.test.skip", and then put the probe.war in the directory of tomcat, therer is no problem visiting "http://localhost:8080/probe". However if I run it in IDEA then occuer a problem.

I get logs for details:

Error:java: java.lang.RuntimeException: java.lang.NoSuchMethodError: com.sun.tools.javac.util.JavacMessages.add(Lcom/sun/tools/javac/util/JavacMessages$ResourceBundleHelper;)V
Error:java: Caused by: java.lang.NoSuchMethodError: com.sun.tools.javac.util.JavacMessages.add(Lcom/sun/tools/javac/util/JavacMessages$ResourceBundleHelper;)V
Error:java: 	at com.google.errorprone.BaseErrorProneJavaCompiler.setupMessageBundle(BaseErrorProneJavaCompiler.java:202)
Error:java: 	at com.google.errorprone.ErrorProneJavacPlugin.init(ErrorProneJavacPlugin.java:40)

**Comment by hazendaz** [comment]
Did you aff error prone intellij plugin?  Intellij requires it.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by valten-hyl** [comment]
I have installed the plug-in, restarted the idea, and changed the java compiler mode to "Javac with error-prone", then occuer a problem.

I get logs for details:

Error:Failed to download error-prone compiler JARs: Failed to download 'https://repo1.maven.org/maven2/com/google/errorprone/error_prone_core/2.3.3/error_prone_core-2.3.3-with-dependencies.jar':
connect timed out.

I didn't find a reference to this jar

**Comment by valten-hyl** [comment]
my friend use the latest idea2019.3.4, then he can run the project. when i update my idea, then occur the problem .

I get logs for details:

Error:Failed to download error-prone compiler JARs: Failed to download 'https://repo1.maven.org/maven2/com/google/errorprone/error_prone_core/2.3.4/error_prone_core-2.3.4-with-dependencies.jar':
connect timed out

I have no idea now

**Comment by valten-hyl** [comment]
thank u
