### ISSUE TITLE
Java issue at catalina.out log file

### ISSUE THREAD

**Issue by NBC-Education** [psi-probe/psi-probe#1605]
Hello,
I'm seeking support for this issue
Have installed apache open meeting, have some trouble with media server failing.
Checking every part, especially Kurento, everything seem to be ok, just following error found with catalina.out log file: 

 _ARN  05-14 11:00:04.069 c.h.i.m.i.MetricsCollectionCycle:67 [cached.thread-5] - Collecting metrics from source com.hazelcast.map.impl.MapService failed java.lang.NoClassDefFoundError: com/hazelcast/map/impl/LocalMapStatsProvider$LocalMapOnDemandCalculatedStats         at com.hazelcast.map.impl.LocalMapStatsProvider.getOrCreateOnDemandStats(LocalMapStatsProvider.java:178)         at com.hazelcast.map.impl.LocalMapStatsProvider.createAllLocalMapStats(LocalMapStatsProvider.java:121)         at com.hazelcast.map.impl.MapStatisticsAwareService.getStats(MapStatisticsAwareService.java:42)         at com.hazelcast.map.impl.MapService.getStats(MapService.java:222)         at com.hazelcast.map.impl.MapService.provideDynamicMetrics(MapService.java:288)         at com.hazelcast.internal.metrics.impl.MetricsCollectionCycle.collectDynamicMetrics(MetricsCollectionCycle.java:88)         at com.hazelcast.internal.metrics.impl.MetricsRegistryImpl.collect(MetricsRegistryImpl.java:316)         at com.hazelcast.internal.metrics.impl.MetricsService.collectMetrics(MetricsService.java:160)         at com.hazelcast.internal.metrics.impl.MetricsService.collectMetrics(MetricsService.java:154)         at com.hazelcast.spi.impl.executionservice.impl.DelegateAndSkipOnConcurrentExecutionDecorator$DelegateDecorator.run(DelegateAndSkipOnConcurrentExecutionDecorator.java:77)         at com.hazelcast.internal.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:217)         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)         at java.base/java.lang.Thread.run(Thread.java:834)         at com.hazelcast.internal.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)         at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)_  
I'm specialist either of apache or of java, so just need some ideas to fix this.
Kindly

**Comment by hazendaz** [comment]
If you add hazelcast jar to the tomcat lib folder, this error will likely go away.

**Comment by hazendaz** [comment]
closing as noted resolution.  When items cross over between tomcat and app, the items need to be in tomcat lib to properly not have issues.
