### ISSUE TITLE
On Ubuntu + OpenJDK 6, all graphs are missing

### ISSUE THREAD

**Issue by GoogleCodeExporter** [psi-probe/psi-probe#161]
```
What steps will reproduce the problem?

Running probe with Tomcat 6 on Ubuntu 8.04 with OpenJDK 6.

What is the expected result?

All the graphs should be available as always.

What happens instead?

All graphs are missing, only displaying broken image link icons.

What version of Probe are you using?  In what environment (browser, server,
JVM, OS)?

Tried with probe 2.04 and 2.10 both having same problem. Browser-independent 
problem as graphs are not showing in different web browsers. Ubuntu 8.04, 
Tomcat 6 and OpenJDK 6 which are installed using apt-get from central 
repository.

Please provide any additional information below.

It seems to me that certain fonts are missing. The way OpenJDK or even Sun JDK 
is installed is different on Ubuntu/Debian as the JDK package would consist of 
a number of other packages as dependencies and I suspect it doesn't cover some 
fonts supposed to be included, which are required by probe or the graph library 
used by probe to work.
```

Original issue reported on code.google.com by `cont...@chenwang.org` on 26 Oct 2010 at 10:12

Attachments:
- [probe_graph_missing.png](https://storage.googleapis.com/google-code-attachments/psi-probe/issue-161/comment-0/probe_graph_missing.png)

**Comment by Middlerun** [comment]
Dear people from the future who have missing PSI Probe graphs and find this page: if you're using Tomcat 7 having this same problem and the above solutions don't work for you, make sure you have a "temp" directory in /var/lib/tomcat7. That was the problem for me. Hope that helps somebody.

**Comment by eqpllc** [comment]
Hi Middlerun,

Thank you very much for posting your solution that helped me with Tomcat 6! I've been desperately seeking a solution for days!!

Thank you!!
--Joe.

**Comment by MALfunction84** [comment]
@Middlerun Add to the [wiki](/psi-probe/psi-probe/wiki/Troubleshooting#graphs-do-not-display)?
