### ISSUE TITLE
FAILED ServerConnector@3207d26a{HTTP/1.1}{0.0.0.0:9022}: java.net.BindException: Address already in use

### ISSUE THREAD

**Issue by quinnxiao** [psi-probe/psi-probe#1634]
FAILED ServerConnector@3207d26a{HTTP/1.1}{0.0.0.0:9022}: java.net.BindException: Address already in use

**Comment by hazendaz** [comment]
already in use is pretty clear, your app is on a instance already running and its not a psi probe issue.  Its your tomcat.
