### ISSUE TITLE
A potential NPE bug

### ISSUE THREAD

**Issue by JulyChen728** [psi-probe/psi-probe#1739]
Hi all,
our bug scanner has reported a NPE bug.

Since the method [getRootLogger()](https://github.com/psi-probe/psi-probe/blob/41184cbf283907c6cfbb86c3b2c42c16ff2f460c/psi-probe-core/src/main/java/psiprobe/tools/logging/log4j/Log4JManagerAccessor.java#L63) may return null, a NPE bug may take place at [here](https://github.com/psi-probe/psi-probe/blob/41184cbf283907c6cfbb86c3b2c42c16ff2f460c/psi-probe-core/src/main/java/psiprobe/tools/logging/log4j/Log4JManagerAccessor.java#L101).

Thanks.

**Comment by hazendaz** [comment]
sure, there are potential null pointers all over but doesn't mean they are happening.  I've tried to fix any sonar issues recently but would prefer help from community of users to further help address some.  closing as nothing to do there.
