### ISSUE TITLE
Release war URL still points to 3.4.5 instead of 3.5.1

### ISSUE THREAD

**Issue by robertoschwald** [psi-probe/psi-probe#1740]
README link points to https://github.com/psi-probe/psi-probe/releases/download/psi-probe-3.4.5/probe.war
but releases 3.5.0 / 3.5.1 already tagged.

There is no https://github.com/psi-probe/psi-probe/releases/download/psi-probe-3.5.1/probe.war currently.

**Comment by hazendaz** [comment]
Please get the WAR from maven central -> https://search.maven.org/classic/remotecontent?filepath=com/github/psi-probe/psi-probe-web/3.5.1/psi-probe-web-3.5.1.war

**Comment by hazendaz** [comment]
Readme updated / releases contains new version.  I may just move to have that only available in maven central as its a manual process I can avoid but for now updated it.  It was incorrect in 2 spots in the readme.  Thanks for reporting.  Your suggested link for download now works.
