### ISSUE TITLE
Update all Silk icons to PNG

### ISSUE THREAD

**Issue by GoogleCodeExporter** [psi-probe/psi-probe#181]
```
All the Silk icons are currently GIFs, but the latest version of the icon 
package contains PNGs.  If we want to add new icons, they're going to have to 
be PNG files.  It would be nice to remain consistent.  Plus, PNG has an alpha 
channel.
```

Original issue reported on code.google.com by `MALfunct...@gmail.com` on 12 Jan 2011 at 7:18
- Blocked on: #186

**Comment by hazendaz** [comment]
This should be current direction.  No current browser in a long time cannot deal with png files and in fact there would have been defects anyways as some png were already in place.  Will address this soon for 3.0.0.  Obviously silk is EOL as it looks like version 1.3 released in 2006 was end of the road.
