### ISSUE TITLE
error accessing probe logs

### ISSUE THREAD

**Issue by rlefig** [psi-probe/psi-probe#1866]
When trying to access the logs tab under probe I get the following errors

10:17:55.709 WARN  {http-bio-8080-exec-6} [o.s.web.servlet.PageNotFound] No mapping for GET /probe/logs/css/classic/main.css
10:17:55.721 WARN  {http-bio-8080-exec-8} [o.s.web.servlet.PageNotFound] No mapping for GET /probe/logs/css/classic/messages.css

This is a RHEL7.9 server running tomcat 7 and probe 3.5.1. I do have this working on other similar servers but on two of them I have the following.

**Comment by rlefig** [comment]
Hi any help with this? What can I look for to help troubleshoot

**Comment by rlefig** [comment]
I am unclear as well but it is happening now on servers that use to work. I can not access the logs tab as any user and see the following message 

There was an error

Application encountered an unexpected error. Please check the Tomcat logs. We will greatly appreciate it if you share the information with us. Sharing this information through our issue tracker or our discussion board will help us find and correct this problem as soon as possible!

And the following shows up in the probe logs. I do not know why this is happening

09:36:44.583 WARN  {http-bio-8080-exec-1} [o.s.web.servlet.PageNotFound] No mapp
ing for GET /probe/logs/css/classic/main.css
09:36:44.585 WARN  {http-bio-8080-exec-7} [o.s.web.servlet.PageNotFound] No mapp
ing for GET /probe/logs/css/classic/messages.css

Please help

**Comment by rlefig** [comment]
Also even though it is only myself accessing probe why do I have 34 sessions according to tomcat


<h1>Sessions Administration for /probe</h1>

<p>Tips:</p>
<ul>
    <li>Click on a column to sort.</li>
    <li>To view a session details and/or remove a session attributes, click on its id.</li>
</ul>

<div class="error"></div>
<div class="message"></div>

<form action="/manager/html/sessions?path=/probe&amp;version=&amp;org.apache.catalina.filters.CSRF_NONCE=AAD64378A816ACC231D6450BC9675E44" method="post" id="sessionsForm">
    <fieldset><legend>Active HttpSessions informations</legend>
        
        
        
        
        </fieldset></form>
        34 active Sessions<br>
        
Session Id | Type | Guessed Locale | Guessed User name | Creation Time | Last Accessed Time | Used Time | Inactive Time | TTL
-- | -- | -- | -- | -- | -- | -- | -- | --

B263CC70BC1CE4DE9B8E2248C83A5907 | Primary | en_US | admin | 2021-06-15 09:51:48 | 2021-06-15 09:51:48 | 00:00:00 | 00:06:48 | 00:08:11
6A38C70E6AE76B788A0D5144042C10C8 | Primary | en_US | &nbsp; | 2021-06-15 09:51:48 | 2021-06-15 09:51:48 | 00:00:00 | 00:06:48 | 00:08:11
0C5E74E1DBD8AC9B2B49CD7D999D7EE7 | Primary | en_US | &nbsp; | 2021-06-15 09:51:48 | 2021-06-15 09:51:48 | 00:00:00 | 00:06:47 | 00:08:12
7BB2F3897F07F33CBFF0DE17698F8D02 | Primary | en_US | &nbsp; | 2021-06-15 09:51:48 | 2021-06-15 09:51:48 | 00:00:00 | 00:06:47 | 00:08:12
E8DDE2CEAB29FBB98A71109E24F26FCC | Primary | en_US | &nbsp; | 2021-06-15 09:51:48 | 2021-06-15 09:51:48 | 00:00:00 | 00:06:47 | 00:08:12
25D7AD34914E1D46E8FD6505005CA78E | Primary | en_US | &nbsp; | 2021-06-15 09:51:47 | 2021-06-15 09:51:47 | 00:00:00 | 00:06:48 | 00:08:11
E5B2448E65AFBB3EECED8820640AB788 | Primary | en_US | &nbsp; | 2021-06-15 09:51:48 | 2021-06-15 09:51:48 | 00:00:00 | 00:06:47 | 00:08:12
F33D0396704A2F01A522DDB0FE21D4FE | Primary | en_US | &nbsp; | 2021-06-15 09:51:48 | 2021-06-15 09:51:48 | 00:00:00 | 00:06:48 | 00:08:11
3BA9C01EF3E5ED1FF955D41E81CF9168 | Primary | en_US | &nbsp; | 2021-06-15 09:51:48 | 2021-06-15 09:51:48 | 00:00:00 | 00:06:47 | 00:08:12
EBF41B8A2EBF4B0FA3EECA74C2FF56A9 | Primary | en_US | &nbsp; | 2021-06-15 09:51:47 | 2021-06-15 09:51:47 | 00:00:00 | 00:06:48 | 00:08:11
EB22759BD766500BE30D69580C1FCBA5 | Primary | en_US | &nbsp; | 2021-06-15 09:51:48 | 2021-06-15 09:51:48 | 00:00:00 | 00:06:47 | 00:08:12
F3F80B205ECBB9772564EFBA7C31E5C6 | Primary | en_US | &nbsp; | 2021-06-15 09:51:49 | 2021-06-15 09:51:49 | 00:00:00 | 00:06:47 | 00:08:12
C824C4E0753615E02463A2DF1F43E961 | Primary | en_US | &nbsp; | 2021-06-15 09:51:48 | 2021-06-15 09:51:48 | 00:00:00 | 00:06:47 | 00:08:12
7DB7CFCAE39242C1D65D0678EF3C5921 | Primary | en_US | &nbsp; | 2021-06-15 09:51:48 | 2021-06-15 09:51:48 | 00:00:00 | 00:06:47 | 00:08:12
95B859DDA49A798E2BC280A2EF369AF0 | Primary | en_US | &nbsp; | 2021-06-15 09:51:49 | 2021-06-15 09:51:49 | 00:00:00 | 00:06:47 | 00:08:12
9038FE69BE889BF3BCAD539FB5A136D9 | Primary | en_US | admin | 2021-06-15 09:51:49 | 2021-06-15 09:57:59 | 00:06:10 | 00:00:36 | 00:14:23
2A5D4CFB94F0DE08D35210C9A713435B | Primary | en_US | &nbsp; | 2021-06-15 09:51:47 | 2021-06-15 09:51:47 | 00:00:00 | 00:06:48 | 00:08:11
20D9C1BC56E5A80379B8D46522320986 | Primary | en_US | &nbsp; | 2021-06-15 09:51:48 | 2021-06-15 09:51:48 | 00:00:00 | 00:06:47 | 00:08:12
E7CA47CE85D99C390C1A7FD26C9195FA | Primary | en_US | &nbsp; | 2021-06-15 09:51:48 | 2021-06-15 09:51:48 | 00:00:00 | 00:06:47 | 00:08:12
B8E7569C225D6447095DF700F9DAEC79 | Primary | en_US | &nbsp; | 2021-06-15 09:51:48 | 2021-06-15 09:51:48 | 00:00:00 | 00:06:48 | 00:08:11
7D36D2EB45C323F9D85927182CA5D13A | Primary | en_US | &nbsp; | 2021-06-15 09:51:48 | 2021-06-15 09:51:48 | 00:00:00 | 00:06:47 | 00:08:12
7B41A9FC5225C1CE147F1E14A950B7E5 | Primary | en_US | &nbsp; | 2021-06-15 09:51:49 | 2021-06-15 09:51:49 | 00:00:00 | 00:06:47 | 00:08:12
4D8EAC296F1620E005620B2468C81D84 | Primary | en_US | &nbsp; | 2021-06-15 09:51:49 | 2021-06-15 09:51:49 | 00:00:00 | 00:06:47 | 00:08:12
771BDB530855D09515D93E65A93D3EDB | Primary | en_US | &nbsp; | 2021-06-15 09:51:48 | 2021-06-15 09:51:48 | 00:00:00 | 00:06:47 | 00:08:12
921D2F649C1C2650A8C5689C7D17A27F | Primary | en_US | &nbsp; | 2021-06-15 09:51:47 | 2021-06-15 09:51:47 | 00:00:00 | 00:06:48 | 00:08:11
B86DE6852A05F66087ACF699A1B0B261 | Primary | en_US | admin | 2021-06-15 09:51:47 | 2021-06-15 09:51:48 | 00:00:00 | 00:06:48 | 00:08:11
4B8F6D0A8B2913AF43EAC48E4C67E89C | Primary | en_US | &nbsp; | 2021-06-15 09:51:48 | 2021-06-15 09:51:48 | 00:00:00 | 00:06:47 | 00:08:12
FE0C0BCBDDD849980BD3E514BBD810F5 | Primary | en_US | admin | 2021-06-15 09:51:46 | 2021-06-15 09:51:47 | 00:00:00 | 00:06:48 | 00:08:11
0130165DC0B5EA7607B65837805B3A9B | Primary | en_US | admin | 2021-06-15 09:51:48 | 2021-06-15 09:51:48 | 00:00:00 | 00:06:47 | 00:08:12
D4BF9ADB69C589E9DAD718CC0F253C41 | Primary | en_US | &nbsp; | 2021-06-15 09:51:47 | 2021-06-15 09:51:47 | 00:00:00 | 00:06:48 | 00:08:11
1743394027F5A64C926177B9E52C7657 | Primary | en_US | &nbsp; | 2021-06-15 09:51:47 | 2021-06-15 09:51:47 | 00:00:00 | 00:06:48 | 00:08:11
9CFEF8590B65D36B8737381A5773DE98 | Primary | en_US | &nbsp; | 2021-06-15 09:51:49 | 2021-06-15 09:51:49 | 00:00:00 | 00:06:47 | 00:08:12
CCAF566DB01AD09648DF1AA194968C43 | Primary | en_US | &nbsp; | 2021-06-15 09:51:49 | 2021-06-15 09:51:49 | 00:00:00 | 00:06:47 | 00:08:12
89E2277E9A1E18A139898C4AF691515B | Primary | en_US | &nbsp; | 2021-06-15 09:51:48 | 2021-06-15 09:51:48 | 00:00:00 | 00:06:47 | 00:08:12


        <p style="text-align: center;">
            </p>
  <p style="text-align: center;">
    </p>

**Comment by hazendaz** [comment]
@rlefig I believe you may be using http rather than https?  That is a known issue, spring creates new sessions constantly if not on https.  Currently we do not restrict to only work with https even though we probably should require that at this point in time.

**Comment by rlefig** [comment]
Hi @hazendaz what is the best way to access probe over https?. You are correct we are using http. and accessing probe via the 8080 tomcat port. Since these are DMZ systems we would like to keep probe internal only and not put it in the ssl.conf for it to work.

Probe 2.3.2 works, although it does not show all the logs, probe 2.4.0 works better but does not display log4j2 logs. We ant this to work so developers can access logs instead of asking sys admins all the time

Thanks

Rob

**Comment by rlefig** [comment]
even running through https I get the same errors with version 3.5.5

14:21:22.146 WARN  {ajp-bio-8009-exec-615} [o.s.web.servlet.PageNotFound] No mapping for G
ET /probe355/logs/css/classic/main.css
14:21:22.152 WARN  {ajp-bio-8009-exec-617} [o.s.web.servlet.PageNotFound] No mapping for G
ET /probe355/logs/css/classic/messages.css

**Comment by hazendaz** [comment]
simply configuring your tomcat to only allow https would do what you want as far as that goes.  As to log4j2, you would likely need to be on the latest.  I don't recall exactly when log4j2 support came in, if you seach issues you should see when it came in at variuos points.  There were issues on the first inclusion of it later fixed.  Also not all logs will show up as this product uses the classpath to find them rather than just listing what is in the logs folder.  That is still outstanding item that has not been addressed and there are some various loggers still not supported.  Most of those are still open issues but searching there will find any and all items around logging of note.

**Comment by rlefig** [comment]
thank you will keep working with it

**Comment by hazendaz** [comment]
closing as old and issues appear addressed, latest builds also require https so session issue here should be addressed.
