### ISSUE TITLE
https redirect - how to disable ?

### ISSUE THREAD

**Issue by neal3000** [psi-probe/psi-probe#1870]
I am running tomcat 8.5 , and I am getting a https redirect when I try to connect.  ( I want http, since I am behind a load balancer which is handling TLS ). How do I disable this ?

Thanks

telnet localhost 8080
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
GET /probe HTTP/1.0

HTTP/1.1 302
Location: https://localhost:8080/probe/
Date: Thu, 27 May 2021 04:05:16 GMT
Connection: close

**Comment by hazendaz** [comment]
Your tomcat is likely doing the redirect.  However, it would be really bad to use http at all.  Regardless of what you are behind, using http is leaving possiblity for man in the middle attack at the very least.  Load balancers can call https without issue and shoudl be.

**Comment by hazendaz** [comment]
closing as not applicable currently to psi probe - ie tomcat setup issue.
