### ISSUE TITLE
blank page when jarsToSkip psi-probe-core-3.5.1.jar 

### ISSUE THREAD

**Issue by bitozoid** [psi-probe/psi-probe#1898]
To speed up Tomcat startup, I have tried to skip scanning of jars. At `logging.properties`:

```
org.apache.jasper.compiler.TldLocationsCache.level = FINE
org.apache.jasper.servlet.TldScanner.level = FINE
```

so Tomcat logs a long list of jars to skip. I also get this one:

```
FINE: No TLD files were found in [jar:file:/usr/local/tomcat/probe/war/probe.war!/WEB-INF/lib/psi-probe-core-3.5.1.jar]. Consider adding the JAR to the tomcat.util.scan.StandardJarScanFilter.jarsToSkip property in CATALINA_BASE/conf/catalina.properties file.
```

However, if I append `psi-probe-core-3.5.1.jar` in `catalina.properties` to:

```
tomcat.util.scan.StandardJarScanFilter.jarsToSkip=\
...
psi-probe-core-3.5.1.jar,\
...
```

then I get a blank page when loading psi-probe in the browser.

**Comment by hazendaz** [comment]
This project is spring, it has to be scanned.  There are no TLDs as noted but it still needs scanned.

**Comment by hazendaz** [comment]
see META-INF in the probe-web module.  Maybe it just needs an adjustment there.

```
<Context path="/probe" privileged="true">
  <Loader delegate="false" />
  <JarScanner>
     <JarScanFilter defaultPluggabilityScan="false"
                    defaultTldScan="false"
                    pluggabilityScan="${tomcat.util.scan.StandardJarScanFilter.jarsToScan},psi-probe-core-*.jar"
                    pluggabilitySkip=""
                    tldScan="${tomcat.util.scan.StandardJarScanFilter.jarsToScan},spring-webmvc-*.jar,displaytag-*.jar,jakarta.servlet.jsp.jstl-*.jar,sitemesh-*.jar"
                    tldSkip="jakarta.servlet.jsp.jstl-api-*.jar" />
  </JarScanner>
</Context>
```

But for the purpose of what you were attempting to skip, see that we specifically need it scanning on pluggability.

**Comment by bitozoid** [comment]
I'm afraid it is my fault. To modify the default path, I created my own `$CATALINA_BASE/conf/catalina/localhost/....xml`, which takes precedence over `META-INF/context.xml`. However, I did not copy the `JarScanner` element.

Thanks a lot for your answer.

**Comment by bitozoid** [comment]
FTR:

- https://tomcat.apache.org/tomcat-9.0-doc/config/jar-scan-filter.html
- https://tomcat.apache.org/tomcat-9.0-doc/config/context.html
