### ISSUE TITLE
Deploy WAR doesnot load jar in tomcat lib directory

### ISSUE THREAD

**Issue by KarelHaruda** [psi-probe/psi-probe#1927]
Due tu licence politics of Oracle we cannot distribute oracle jdbc driver in application WAR file. 
For this reason we have this JAR file in Tomcat`s lib directory. 
After undeploy and deploy new version of WAR, newly deployed app doesnot have classes from this jar file until tomcat restart.
If app is deployed outside probe (new war is copied to webapps directory) app running normaly and can access classes from ojdbc.jar placed in tomcat lib directory.

Is it BUG in psi probe ?

**Comment by hazendaz** [comment]
Oracle has been publishing the drivers in maven central for last few years.  There is no longer a license restriction.

Not sure how this app would have anything to do with JAR that is in tomcat/lib as that is a separate classloader.  Not sure what versions you have referred to here but might help by documenting versions in use as well here for reference.

**Comment by KarelHaruda** [comment]
Hi, thank you for reply. We are running on psi probe Version 3.5.1. 
Its a good information that oracle drivers are in maven. I did not know it. It is possible to distribute ojdbc driver in war for commercial use ? Do you know it ? 
But it propably does not solve our problem, bcs same restriction politics has IBM db2 driver :(

**Comment by hazendaz** [comment]
you would need to check with this license terms.


  <licenses>
    <license>
      <name>Oracle Free Use Terms and Conditions (FUTC)</name>
      <url>https://www.oracle.com/downloads/licenses/oracle-free-license.html</url>
    </license>
  </licenses>

**Comment by hazendaz** [comment]
For those looking, see https://search.maven.org/search?q=g:com.oracle.database.jdbc

**Comment by hazendaz** [comment]
Also note due to old restrictions we had split the repo into two.  I plan to restore it back to how it used to be in coming releases probably by end of summer.  You can find the ojdbc module though at psi probe main project.
