### ISSUE TITLE
Add gc.log to log file tab

### ISSUE THREAD

**Issue by GoogleCodeExporter** [psi-probe/psi-probe#202]
```
Which existing feature would you like to see enhanced?


Please describe the enhancement in detail.


How will this enhancement make Probe better?

```

Original issue reported on code.google.com by `boris.no...@gmail.com` on 12 Mar 2011 at 9:23

**Comment by hazendaz** [comment]
Any logs not directly supported for configuration can be added via stdout.properties in web module.  Given its most often called 'gc.log', adding it to the normal build which should at least resolve this.
