### ISSUE TITLE
Breadcrumb navigation

### ISSUE THREAD

**Issue by GoogleCodeExporter** [psi-probe/psi-probe#207]
```
Please describe the feature you would like to see added.
Add breadcrumb navigation to the web UI.

How will this feature make Probe better?
When drilling down into data that Probe exposes, the path taken can be 
obscured.  One of the tabs will be highlighted, but sometimes that isn't enough 
to go on.

Relates to issue 113.
```

Original issue reported on code.google.com by `MALfunct...@gmail.com` on 1 Apr 2011 at 7:54

**Comment by hazendaz** [comment]
Closing 5 year old issue.  We have enough javascript / jsp need to upgrade to keep us busy another year.  I presume as we get into new techologies look and fell will greatly change.  I'm not sure how simply adding additional breadcrumb really does anything here.
