### ISSUE TITLE
Support for Tomcat 9.0.58?

### ISSUE THREAD

**Issue by ssjlfrank** [psi-probe/psi-probe#2125]
Hello all,

Trying to deploy a fresh war of probe to the latest Ubuntu Server 22.04, and the Tomcat that it ships with it is 9.0.58, for additional reference, the JDK we're using is build 1.8.0_312-8u312-b07-0ubuntu1-b07.

We're encountering the following error in probe.log upon accessing the webapp:

> 21:57:56.121 ERROR {main} [psiprobe.model.stats.StatsCollection] Could not read stats data from '/var/lib/tomcat9/work/Catalina/localhost/probe/stats.xml'
> com.thoughtworks.xstream.security.ForbiddenClassException: org.jfree.data.xy.XYDataItem
> 	at com.thoughtworks.xstream.security.NoTypePermission.allows(NoTypePermission.java:26)
> 	at com.thoughtworks.xstream.mapper.SecurityMapper.realClass(SecurityMapper.java:74)
> 	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:125)
> 	at com.thoughtworks.xstream.mapper.CachingMapper.realClass(CachingMapper.java:47)
> 	at com.thoughtworks.xstream.core.util.HierarchicalStreams.readClassType(HierarchicalStreams.java:29)
> 	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readBareItem(AbstractCollectionConverter.java:131)
> 	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readItem(AbstractCollectionConverter.java:117)
> 	at com.thoughtworks.xstream.converters.collections.CollectionConverter.addCurrentElementToCollection(CollectionConverter.java:99)
> 	at com.thoughtworks.xstream.converters.collections.CollectionConverter.populateCollection(CollectionConverter.java:92)
> 	at com.thoughtworks.xstream.converters.collections.CollectionConverter.populateCollection(CollectionConverter.java:86)
> 	at com.thoughtworks.xstream.converters.collections.CollectionConverter.unmarshal(CollectionConverter.java:81)
> 	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:74)
> 	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:72)
> 	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:68)
> 	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:52)
> 	at com.thoughtworks.xstream.converters.reflection.SerializableConverter$2.defaultReadObject(SerializableConverter.java:402)
> 	at com.thoughtworks.xstream.converters.reflection.SerializableConverter.doUnmarshal(SerializableConverter.java:447)
> 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:277)
> 	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:74)
> 	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:72)
> 	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:68)
> 	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:52)
> 	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readBareItem(AbstractCollectionConverter.java:132)
> 	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readItem(AbstractCollectionConverter.java:117)
> 	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readCompleteItem(AbstractCollectionConverter.java:147)
> 	at com.thoughtworks.xstream.converters.collections.MapConverter.putCurrentEntryIntoMap(MapConverter.java:107)
> 	at com.thoughtworks.xstream.converters.collections.MapConverter.populateMap(MapConverter.java:99)
> 	at com.thoughtworks.xstream.converters.collections.TreeMapConverter.populateTreeMap(TreeMapConverter.java:115)
> 	at com.thoughtworks.xstream.converters.collections.TreeMapConverter.unmarshal(TreeMapConverter.java:78)
> 	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:74)
> 	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:72)
> 	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:68)
> 	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:52)
> 	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:136)
> 	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
> 	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1421)
> 	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1399)
> 	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1293)
> 	at psiprobe.model.stats.StatsCollection.deserialize(StatsCollection.java:283)
> 	at psiprobe.model.stats.StatsCollection.afterPropertiesSet(StatsCollection.java:338)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
> 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
> 	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
> 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1389)
> 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309)
> 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:656)
> 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:639)
> 	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
> 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
> 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
> 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
> 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
> 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
> 	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:401)
> 	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:292)
> 	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103)
> 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4766)
> 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5230)
> 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
> 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:726)
> 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:698)
> 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:696)
> 	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1024)
> 	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1911)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
> 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
> 	at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:825)
> 	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:475)
> 	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1618)
> 	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:319)
> 	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
> 	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
> 	at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
> 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:946)
> 	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:835)
> 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
> 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1396)
> 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1386)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
> 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
> 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:919)
> 	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:263)
> 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
> 	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:432)
> 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
> 	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:927)
> 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
> 	at org.apache.catalina.startup.Catalina.start(Catalina.java:772)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:345)
> 	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:480)
> 

We see that the listed supported tomcat versions do not yet include 9.0.58;  is there something we can do to workaround this issue?

**Comment by hazendaz** [comment]
All tomcats for 7/8/9 to latest of those are supported from start of the support notice.  I'll update the list.

The issue above is xstream.  Other than the log, does it cause any other issues?  I've confirmed that xtream changed security so some code changes have to occur.  I plan to look at this soon but wanted to understand what other issues are seen.

**Comment by ssjlfrank** [comment]
The app authenticates via the standard browser dialog, and upon login serves a blank page with status 500.

**Comment by ssjlfrank** [comment]
Circling back around to this one.   Still experiencing same issues.   Webapp authenticates via browser dialog serves blank page with error 500

Stock install via apt on Ubuntu 22.04.
TC Version: Apache Tomcat/9.0.58 (Ubuntu)
Java Version: 1.8.0_342-8u342-b07-0ubuntu1~22.04-b07

**Comment by hazendaz** [comment]
3.5.9 was released on June 2nd resolving the issue.  Since then 3.6.0 is out.  Browser will always be blank, its secured from showing internal stack traces, your logs would have the details as to what the 500 is about with a stack trace.  

What version of psi probe are you using?

**Comment by ssjlfrank** [comment]
Not entirely sure what the issue was.  Started again from scratch with another set of eyes and is working now.    

Will add further comments if I come across what in my original configuration broke it.

**Comment by ssjlfrank** [comment]
Figured out the real difference:    Second time around was installed with jre11.   When we moved back to jre8 it broke again.    Apparently Debian's packaging with regards to tomcat9+jre8 has some issues.  Probe was failing silently,  meanwhile our own app was failing quite verbosely.

Resolved using this discussion:
https://bugs.launchpad.net/ubuntu/+source/tomcat9/+bug/1972829

**Comment by hazendaz** [comment]
@ssjlfrank Thanks for the details to help others!
