### ISSUE TITLE
permission error in tomcat 8.5 with ssl

### ISSUE THREAD

**Issue by marceel08** [psi-probe/psi-probe#2248]
Guys, I'm having permission error in tomcat 8.5 with ssl
I've done all the permission processes but I still can't succeed

You do not have sufficient privileges to access this page. Please use the navigation bar to choose another area or click "back" button in your browser.

**Comment by hazendaz** [comment]
would seem you possibly have not setup the users file as shown here https://github.com/psi-probe/psi-probe/wiki/InstallationApacheTomcat

**Comment by marceel08** [comment]
I did these processes, and I still have a problem..

**Comment by marceel08** [comment]
Guys, can you help me? I do not know what else to do

**Comment by hazendaz** [comment]
same as the instructions state.  SSL is just https on the app.  That isn't the ability to be authenticated to use the app.  That comes from setting up the user in tomcat.  This is documented in the wiki.

**Comment by marceel08** [comment]
yes, I already made all the configurations as instructed in the wiki and even so I was not successful

**Comment by hazendaz** [comment]
not sure how to help more here.  I use this with tomcat 9 on the regular and its only https and works fine.  I would suggest starting with a fresh tomcat and working your way up from there to figure out the issue you are facing.  When I run various tests for release on this, I'm always using http sand use various tomcats without issue.

**Comment by hazendaz** [comment]
closing as not enough data to help.  not seeing issue.  app only works with https now.

note, as noted in code

	<web-resource-collection>
		<web-resource-name>All areas</web-resource-name>
		<url-pattern>/*</url-pattern>
	</web-resource-collection>

was required in some tomcat versions to be on app web.xml too.  It is currently and that may or may not be part of the issue.  That would be needed likely in tomcat but look at web.xml to see specifically.
