### ISSUE TITLE
Psi-probe bug

### ISSUE THREAD

**Issue by liyang-10** [psi-probe/psi-probe#2250]
apache-tomcat-9.0.65  Psi-probe 3.5.8 Release

The previous version has two bugs
1：The first release of the WAR package removes the project directly
2: After the second release, a message is displayed indicating that the XXX.war package is not uploaded
Updating the project requires two  #uploads

Please forgive my terrible English. I hope you can understand it

**Comment by hazendaz** [comment]
Please use latest and try to repeat issue.  I don't know how much I really can assist.  I no longer use this as a main solution for about 7 years now unfortunately. I'm doing my best to support and bringing it up to date.  So any changes that I don't have details on are likely to go unfixed.  If you can provide a PR that would potentially address the situation that would help.
