### ISSUE TITLE
Apache commons text vulnerability

### ISSUE THREAD

**Issue by dogilvie** [psi-probe/psi-probe#2298]
Hello,

is the 3.5.8 probe release vulnerable to this security issue? I note that commons text is used, and has already been "renovated" to 1.10.

https://commons.apache.org/proper/commons-text/security.html

To keep our relatively dumb security scan software happy, a release moving to the 1.10 build of commons text would be appreciated.

Thanks!

**Comment by hazendaz** [comment]
Hi @dogilvie, I'll try to get a release out over this week.

**Comment by hazendaz** [comment]
Didn't make it for this past weekend but will try again this next weekend.  I had to release some submodules first and did get those updated (displaytag / psi-probe-ojdbc).  Tomcat just released nearly everything (assuming 8.5 will come this week) so kind of waiting on that and need to look over the modules to ensure everything has been applied that needs to be.

**Comment by frotman** [comment]
Any news? It's a vulnerability. Please tag 3.6.1 :-) thanks

**Comment by hazendaz** [comment]
The vulnerability is a very specific method which is not normally used and not used by this library.  So technically we are not vulnerable as a result.  I'm working on the code otherwise and wanted all tomcat had and they may be releasing again based on some data I'm seeing so this will get released once all that is squared away.

**Comment by hazendaz** [comment]
3.7.0 released.

**Comment by dogilvie** [comment]
> 3.7.0 released.

Thanks! Can you update the  "Latest Release via Github Releases" section at https://github.com/psi-probe/psi-probe 

It still points to 3.5.8

**Comment by hazendaz** [comment]
fixed, its pointed to proper 3.7.0 from github releases.
