### ISSUE TITLE
Linked images in Wiki are not available

### ISSUE THREAD

**Issue by JoachimRohde** [psi-probe/psi-probe#2490]
On https://github.com/psi-probe/psi-probe/wiki/Features the linked images are pointing to http://psi-probe.googlecode.com/svn/wiki/Features/[xyz].png and are therfore not available anymore.

**Comment by hazendaz** [comment]
I presume those showed what the pages looked like.  Given they are gone and the google archive doesn't seem to have any of that, I have simply removed all the links.  The original author mainly setup that wiki area, I don't generally use it myself so its quite out of date in general from looks of it but at least that will be one less confusing item.
