### ISSUE TITLE
When using a rolling appender, expose previous logs

### ISSUE THREAD

**Issue by GoogleCodeExporter** [psi-probe/psi-probe#290]
```
If the logger is configured to use a rolling appender, it would be nice to be 
able to access the old logs from the psi-probe interface.


```

Original issue reported on code.google.com by `fmarm...@gmail.com` on 14 May 2012 at 10:16

**Comment by hazendaz** [comment]
closing but would be possible if you put into a subfolder then gave stdout the location of the subfolder - ie logs/archive for example and then stating to just show all content from there.  If I have time I might do just that but for now closing, if need is there still raise new ticket.
