### ISSUE TITLE
When will the Psi Probe 4.1.1 war version be released?

### ISSUE THREAD

**Issue by attachi20** [psi-probe/psi-probe#3059]
When will the Psi Probe 4.1.1 war version be released?

**Comment by attachi20** [comment]
@hazendaz Thank you for letting me know. Before I checked Maven, I couldn't find the file there. I'll verify again. If it's not available, I appreciate your commitment to resolving the issue tonight

**Comment by hazendaz** [comment]
Hi @attachi20. This has been resolved.  From the readme you should be able to see where it is in general.  Its under psi-probe-web.war there (ie the actual module name).  Typically what I do after release is simply download the war from central, rename it to probe.war and add it to the releases section on github.
