### ISSUE TITLE
Calculation session size - You have passed wrong parameters to this page.

### ISSUE THREAD

**Issue by tachtler** [psi-probe/psi-probe#3154]
Hi,
on version 4.1.4 when I call up the page "/ - application summary" and then call up the menu item "estimate sessions size (could be slow)", the session size is calculated, but shortly afterwards the line "Runtime information" disappears and an error message in red "You have passed wrong parameters to this page." is displayed.

Many thanks in advance and best regards
Klaus.

**Comment by ralf-devop** [comment]
@tachtler
I found the reason for this issue.
The link behind "estimate sessions size (could be slow)" is wrong.

Wrong:
https://<server>:<port>/probe/appsummary.htm?size=true&webapp=%2F<appname>
Correct:
https://<server>:<port>/probe/appsummary.htm?webapp=%2F<appname>&size=true

Parameter "webapp" has to be first.
I'll fix it and raise a PR.

**Comment by tachtler** [comment]
Hi Ralf,

thank you for your reply.

Greetings
Klaus (from Munich)

**Comment by hazendaz** [comment]
Issue fixed on master, will be releasing in a few.  Closing issue as completed.

**Comment by tachtler** [comment]
Hi hazendaz,

I will try it out when the new version is available.

Regards
Klaus.
