### ISSUE TITLE
 Cannot find the declaration of element 'taglib'

### ISSUE THREAD

**Issue by enioha** [psi-probe/psi-probe#3186]
**Error deploying probe.war version 4.1.1**

 
**Caused by:** org.xml.sax.SAXParseException; systemId: file:/opt/tomcat/webapps/probe/WEB-INF/tld/probe.tld; lineNumber: 17; columnNumber: 17; cvc-elt.1.a: Cannot find the declaration of element 'taglib'.

**_Details:_**
    Server version name: Apache Tomcat/9.0.86
    Server version number: 9.0.86.0
    OS Name: Linux
    OS version: 5.14.0-162.12.1.el9_1.0.2.x86_64
    Architecture: amd64
    JVM Version: 11.0.21+9-LTS-193

**Cluster**: Enable

**Comment by hazendaz** [comment]
I'm applying fix suggested by @ralf-devop .  Will be releasing that tonight.  That was an oversight and appears to have been 4 year oversight.  The schema was already set correctly on line 16.

**Comment by hazendaz** [comment]
Code is merged to master.  I didn't get this out tonight.  Will do so sometime this weekend.  I need to do more testing...
