### ISSUE TITLE
Exclude logs that cause errors

### ISSUE THREAD

**Issue by GoogleCodeExporter** [psi-probe/psi-probe#319]
```
What steps will reproduce the problem?
1. See group post: 
https://groups.google.com/forum/?fromgroups=#!topic/psi-probe-discuss/8QeaGj6e0K
g
2. View logs tab.

What is the expected result?
Logs tab will display a list of logs.

What happens instead?
Logs tab displays an error (see attachment).

What version of Probe are you using?
2.3.2

What environment (browser version, Tomcat version, JVM version, server OS)?
See group post: 
https://groups.google.com/forum/?fromgroups=#!topic/psi-probe-discuss/8QeaGj6e0K
g

Please provide any additional information below.
(Attach logs or stack traces as files instead of pasting the contents
here.)
If retrieving any property of the log fails, the exception should be caught and 
the offending log removed.
```

Original issue reported on code.google.com by `MALfunct...@gmail.com` on 25 Sep 2012 at 2:21

**Comment by jander99** [comment]
Scanning Milestone-2.4.0

Can we move this under logging enhancements?

**Comment by hazendaz** [comment]
Issue is no longer available to look at.  I've never seen this.  We did have a recent situation with slf4j which was fixed.  Presumably it's due to issues with loggers that changed.  I can think of two such occassions.  Closing this issue as there is not enough information to do anything here.

**Comment by MALfunction84** [comment]
I think what's at issue here is the robustness of the log file accumulation. If any one log fails to resolve, the entire thing blows up. It'd be better to log the error (maybe even include an error message in the UI) and keep going so there's at least some partial results.

**Comment by hazendaz** [comment]
Do you know of any way to make this happen?

**Comment by MALfunction84** [comment]
Sure. When the each classloader is [interrogated](https://github.com/psi-probe/psi-probe/blob/master/core/src/main/java/psiprobe/beans/LogResolverBean.java#L321), the LogResolverBean tries out each supported log accessor, calling `appenders.addAll(fooAccessor.getBars())` for each one. Each of those `getBars()` methods builds a `List<LogDestination>`, but they immediately fail if creating any single `LogDestination` instance fails.

For example, `LogResolverBean` [uses](https://github.com/psi-probe/psi-probe/blob/master/core/src/main/java/psiprobe/beans/LogResolverBean.java#L331) `Jdk14ManagerAccessor`, which [uses](https://github.com/psi-probe/psi-probe/blob/master/core/src/main/java/psiprobe/tools/logging/jdk/Jdk14ManagerAccessor.java#L87) `Jdk14LoggerAccessor`, which [completely bails](https://github.com/psi-probe/psi-probe/blob/master/core/src/main/java/psiprobe/tools/logging/jdk/Jdk14LoggerAccessor.java#L47) if wrapping any one of the handlers fails. It should probably look more like this:

```java
public List<LogDestination> getHandlers() {
    List<LogDestination> handlerAccessors = new ArrayList<>();
    Object[] handlers;
    try {
      handlers = (Object[]) MethodUtils.invokeMethod(getTarget(), "getHandlers", null);
    } catch (Exception e) {
      logger.error("{}#handlers inaccessible", getTarget().getClass().getName(), e);
      return handlerAccessors;
    }
    for (int h = 0; h < handlers.length; h++) {
      Object handler = handlers[h];
      try {
        Jdk14HandlerAccessor handlerAccessor = wrapHandler(handler, h);
        if (handlerAccessor != null) {
          handlerAccessors.add(handlerAccessor);
        }
      } catch (Exception e) {
        // log that this one failed, but keep trying the others
      }
    }
    return handlerAccessors;
  }
```

This would be much more robust. The other log accessors could get very similar treatment.

**Comment by hazendaz** [comment]
closing as 6 years old and much of this is different now.
