### ISSUE TITLE
How to Uninstall Probe

### ISSUE THREAD

**Issue by GoogleCodeExporter** [psi-probe/psi-probe#369]
```
Kindly provide the steps to uninstall the psi probe which is installed under 
JBoss.
```

Original issue reported on code.google.com by `virtual....@gmail.com` on 21 Aug 2013 at 3:55

**Comment by hazendaz** [comment]
Not sure why this is even an issue.  If someone installs something, the reverse of install is true.  Simply stop container and delete.  Unclear how this has anything to directly do with psi probe as this would be true of any application running under any container.  Closing issue as it is not clear why this is an issue.
