### ISSUE TITLE
Cannot build project on OSX with Java 7

### ISSUE THREAD

**Issue by GoogleCodeExporter** [psi-probe/psi-probe#371]
```
What steps will reproduce the problem?
1. mvn package


What is the expected result?
successful build

What happens instead?
constituent[30]: 
file:/eclipse-common/maven2-standalone/current-maven/lib/xercesMinimal-1.9.6.2.j
ar
---------------------------------------------------
Exception in thread "main" java.lang.AssertionError: Missing tools.jar at: 
/Library/Java/JavaVirtualMachines/jdk1.7.0_21.jdk/Contents/Home/Classes/classes.
jar. Expression: file.exists()
    at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:395)


What version of Probe are you using?
Latest SVN trunk

What environment (browser version, Tomcat version, JVM version, server OS)?
OSX, Java 7 JDK 1.7.0_21

Please provide any additional information below.
Due to a long-standing bug in the jspc-maven plugin, currently it is not 
possible to build psi-probe on OSX with Java 7. As the upstream plugin provider 
was not able to fix this bug in months, a fork of the plugin exists which fixes 
the bug. See 
http://developer.jasig.org/projects/jspc-maven-plugin/2.0.0/jspc-maven-plugin/us
age.html

So a possible fix would be to switch to org.jasig.mojo.jspc jspc-maven-plugin



```

Original issue reported on code.google.com by `robertos...@gmail.com` on 23 Aug 2013 at 10:57

**Comment by jander99** [comment]
Does an updated jspc-maven plugin exist? Is anyone able to try this on a Mac? 

I'm reading up on jspc-maven-plugin and it seems the only thing it does is precompile .jsps.  Do we actually need this plugin for mvn package?  JSPs can be compiled at runtime just as easily and might actually be more correct since they are compiled on the target arch.  I thought maybe it could be used for unit testing, but this project is so far light on that. 

Thoughts?

**Comment by MALfunction84** [comment]
The jspc plugin is there as a test of the JSPs, to make sure they are free of syntax errors and have all the right tag libraries imported to work. At one time, it was including the compiled output in the resulting .war file, but it caused problems, so now it's only there as a test.

I recently updated the jspc plugin (ecc0f0c). Is the jspc plugin what's causing problems on Mac? "Missing tools.jar" suggests it's a problem with the Mac JDK itself.

**Comment by jander99** [comment]
I took a quick peek at the bug in the mojo jira.  Seems the plugin doesn't look in the right place.  The JDK has tools.jar (otherwise it wouldn't work at all) but it seems like the way the plugin functions, it can't find it and add it to the classpath to do the compilations.

**Comment by MALfunction84** [comment]
Can you link the mojo jira bug here? Might be helpful for others experiencing this problem. Thanks.

**Comment by jander99** [comment]
It's listed above

https://jira.codehaus.org/browse/MJSPC-53.  

Looks like @GoogleCodeExporter doesn't create links from text.  Mojo's jspc just seems unmaintained, The Jasig package itself is a little newer than the mojo one, but might fix the issues with Mac.  I can't tell based on the github (I also didn't look that far), but the author says it fixes for Tomcat7 Jasper, so I would say that is a primary reason to use it 

https://github.com/Jasig/jspc-maven-plugin

**Comment by MALfunction84** [comment]
Yeah, ecc0f0c changed it from mojo to jasig. I take it that didn't make any difference?

**Comment by robertoschwald** [comment]
I think we can close this issue by adding a readme note for OSX to use Oracle JDK 1.7 or 1.8 which fixes the issue.

**Comment by MALfunction84** [comment]
It might not be necessary if swapping out the jspc avoids the issue. Can anyone on OSX confirm?

**Comment by hazendaz** [comment]
No further input from users.  Plugin was changed.  No further reports of issues.  Closing this.
