### ISSUE TITLE
On connectors tab there are no graphs

### ISSUE THREAD

**Issue by GoogleCodeExporter** [psi-probe/psi-probe#389]
```
On connectors tab there are no graphs. Seems like system cannot get the data.
I added -Dcom.sun.management.jmxremote=true entry to CATALINA_OPTS but without 
success.

Probe version: 2.2.1
OS: Centos 6, 64-bit
JVM:  Java(TM) SE Runtime Environment  1.7.0_45-b18  Java HotSpot(TM) 64-Bit 
Server VM) 
Container: Apache Tomcat/7.0.47

```

Original issue reported on code.google.com by `krystian...@googlemail.com` on 9 Dec 2013 at 12:55

Attachments:
- [Untitled.png](https://storage.googleapis.com/google-code-attachments/psi-probe/issue-389/comment-0/Untitled.png)

**Comment by hazendaz** [comment]
Closing issue as no other reports and never seen this on multiple machine types.  Most likely issue with older version that since has went away.
