### ISSUE TITLE
Store user settings locally

### ISSUE THREAD

**Issue by GoogleCodeExporter** [psi-probe/psi-probe#39]
```
Please describe the feature you would like to see added.
The ability to store settings locally, perhaps to a user's home directory.

How will this feature make Probe better?
If configurable settings are not persistent, they would have to be
re-entered after Probe or Tomcat is restarted.  This feature would allow
user settings to persist through a Probe or Tomcat restart.  At least one
proposed feature would be nearly unusable without this (see issue 14), and
it opens up the possibility for additional features which require some
level of configuration.
```

Original issue reported on code.google.com by `MALfunct...@gmail.com` on 15 Aug 2009 at 4:29
- Blocking: #106, #107, #108, #114, #106

**Comment by hazendaz** [comment]
closing as old and not seeing value at the moment.  Most of those items suggested changed through here are on the fly meaning not permanent such as logging changes.  Preserving that here doesn't make sense.  Go fix the source if they are wrong.  If really necessary, think in 8 years someone would have added the feature.
