### ISSUE TITLE
Loosen access control for Quick Check XML page

### ISSUE THREAD

**Issue by GoogleCodeExporter** [psi-probe/psi-probe#426]
```
Which existing feature would you like to see enhanced?

Probe provides a Quick Check page in xml format which is accessible from url 
probe/adm/quickcheck.xml.htm

Please describe the enhancement in detail.

Quick Check page currently requires manager role. Since this check does not 
modify anything, this access control can be loosened down to probeuser role.

How will this enhancement make Probe better?

It will help to integrate with third party monitoring applications (eg. 
zabbix). Currently an user with manager role must be set up and configured to 
access this page. It would be much more secure if system monitoring 
applications does not have a probe manager password lying around in their 
configuration.

```

Original issue reported on code.google.com by `ali...@gmail.com` on 20 Oct 2014 at 11:26

**Comment by hazendaz** [comment]
@MALfunction84 What exactly does quick check actually do for us?  I have found it entirely useless probably because I have no clue what it's purpose is.  Possible it's purpose should be listed on the page itself.

**Comment by MALfunction84** [comment]
People use it as a health check for PSI Probe and the Tomcat server.

**Comment by jander99** [comment]
We have our Netscaler ping this to determine whether a JVM should be taken
out if rotation.

**Comment by hazendaz** [comment]
Thanks.  So is it simply on the website so people are aware of it?  If so ill add some more info there.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
