### ISSUE TITLE
Logback SiftingAppender broken in Logback v1.1.x

### ISSUE THREAD

**Issue by GoogleCodeExporter** [psi-probe/psi-probe#432]
```
What steps will reproduce the problem?
1.Use Logback Version 1.X.X (such as 1.1.1)
2.Use a Sifting Appender in your logback.xml
3.Deploy Probe and Click on the 'Logs' Tab after the Application has started
4.In the probe.log you'll find an Exception

What is the expected result?


What happens instead?
java.lang.NoSuchMethodException: No such accessible method: valueList() on 
object: ch.qos.logback.core.sift.AppenderTracker


What version of Probe are you using?
2.3.3


What environment (browser version, Tomcat version, JVM version, server OS)?


Please provide any additional information below.
(Attach logs or stack traces as files instead of pasting the contents
here.)

```

Original issue reported on code.google.com by `patrick....@gmail.com` on 29 Nov 2014 at 12:46

Attachments:
* [Fixed_Logback_Sifting_Appender_Support_for_Logback_Version___1_x_x.patch](https://storage.googleapis.com/google-code-attachments/psi-probe/issue-432/comment-0/Fixed_Logback_Sifting_Appender_Support_for_Logback_Version___1_x_x.patch)

**Comment by hazendaz** [comment]
Logback changed this code on this [commit](https://github.com/qos-ch/logback/commit/a86350e20ebf79b70aa737ea6149bf8485f2d295)

**Comment by hazendaz** [comment]
Issue produced on this is
java.lang.NoSuchMethodException: No such accessible method: valueList() on object: ch.qos.logback.core.sift.AppenderTracker

Fix is coming.

**Comment by hazendaz** [comment]
To test, add shif appender to logback xml in psi probe.  Build and run.  It will fail with error when selecting log tab.  Change as outlined in fix, then try again, the shift appender will show up without error.  I reviewed the logback code, found where it changed, and performed these verifications.

Add shift appender as addition to psi probe log...

```xml
  <appender name="SIFT" class="ch.qos.logback.classic.sift.SiftingAppender">
    <discriminator>
      <key>userid</key>
      <defaultValue>unknown</defaultValue>
    </discriminator>
    <sift>
      <appender name="FILE-${userid}" class="ch.qos.logback.core.FileAppender">
        <file>user-${userid}.log</file>
        <layout class="ch.qos.logback.classic.PatternLayout">
          <pattern>%d{HH:mm:ss:SSS} | %-5level | %thread | %logger{20} | %msg%n%rEx</pattern>
        </layout>
      </appender>
    </sift>
  </appender>
```

Add in root...
```xml
    <appender-ref ref="SIFT" />
```
