### ISSUE TITLE
Update jspc-maven-plugin and jspc-compiler-tomcat5

### ISSUE THREAD

**Issue by GoogleCodeExporter** [psi-probe/psi-probe#442]
```
The old one seems to cause issue, so I updated the pom to use the latest 
release.

```

Original issue reported on code.google.com by `moim...@gmail.com` on 16 Jan 2015 at 8:46

Attachments:
* [jspc.diff](https://storage.googleapis.com/google-code-attachments/psi-probe/issue-442/comment-0/jspc.diff)

**Comment by diogosantana** [comment]
Can I ask why use this plugin if it is not really used? Is there a reason for that?

**Comment by MALfunction84** [comment]
It's a form of testing to make sure the JSPs are free of errors.
