### ISSUE TITLE
Classloader Leak during JFreeChart initialization

### ISSUE THREAD

**Issue by GoogleCodeExporter** [psi-probe/psi-probe#443]
```
What steps will reproduce the problem?
1. Deploy probe.war
2. Access System - Memory Utilization (which starts JFreeChart)
3. Undeploy probe.war

What is the expected result?
A heap dump should not show probe classloader on the PermGen.


What happens instead?
The classloader of probe shows, which is stopped, does not get collected. See 
probeAppContextClassloaderLeak-01.png.


What version of Probe are you using?
2.3.3 and 2.4.0-SNAPSHOT

What environment (browser version, Tomcat version, JVM version, server OS)?
Chrome 40 64 bits, Tomcat 7.0.57, Java 1.7.0_60 64 bits (Oracle), Windows 7 64 
bits 

Please provide any additional information below.

The root cause can be viewed on probeAppContextClassloaderLeak-02.png

Add a patch solution as described at 
https://plumbr.eu/blog/hunting-down-memory-leaks-a-case-study

```

Original issue reported on code.google.com by `diogosan...@gmail.com` on 27 Jan 2015 at 5:37

Attachments:
* [probeAppContextClassloaderLeak-01.png](https://storage.googleapis.com/google-code-attachments/psi-probe/issue-443/comment-0/probeAppContextClassloaderLeak-01.png)
* [probeAppContextClassloaderLeak-02.png](https://storage.googleapis.com/google-code-attachments/psi-probe/issue-443/comment-0/probeAppContextClassloaderLeak-02.png)
* [psi-probe-patch.txt](https://storage.googleapis.com/google-code-attachments/psi-probe/issue-443/comment-0/psi-probe-patch.txt)

**Comment by diogosantana** [comment]
This leak is actually prevented by Tomcat Listeners (not by default).

[Tomcat 6 - JRE Memory Leak Prevention Listener](https://tomcat.apache.org/tomcat-6.0-doc/config/listeners.html#JRE_Memory_Leak_Prevention_Listener_-_org.apache.catalina.core.JreMemoryLeakPreventionListener)
[Tomcat 7 - JRE Memory Leak Prevention Listener](https://tomcat.apache.org/tomcat-7.0-doc/config/listeners.html#JRE_Memory_Leak_Prevention_Listener_-_org.apache.catalina.core.JreMemoryLeakPreventionListener)
[Tomcat 8 - JRE Memory Leak Prevention Listener](https://tomcat.apache.org/tomcat-8.0-doc/config/listeners.html#JRE_Memory_Leak_Prevention_Listener_-_org.apache.catalina.core.JreMemoryLeakPreventionListener)

**Comment by diogosantana** [comment]
Should we manually prevent this, with the patch, or leave to the Tomcat admin to enable the Tomcat Listener?

**Comment by MALfunction84** [comment]
I'm inclined to get the fix into Probe.

**Comment by diogosantana** [comment]
@MALfunction84 Do you want me to create a RP from the patch?

**Comment by MALfunction84** [comment]
@diogosantana Yes, that would be very helpful!
