### ISSUE TITLE
Upgrade to Spring Framework 4.x

### ISSUE THREAD

**Issue by GoogleCodeExporter** [psi-probe/psi-probe#449]
```
Which existing feature would you like to see enhanced?
Spring Framework.

Please describe the enhancement in detail.
Upgrade the Spring Framework to version 4.x.

Might want to go to 3.x first and iron out all the bugs. This would also 
involve upgrading to Spring Security 3.x (or possibly 4.x).

How will this enhancement make Probe better?
More configuration via annotations instead of XML files. Dropping support for 
Java 1.4 is long overdue.

Features are being held back by Spring 2.5 (see blocked issues).
```

Original issue reported on code.google.com by `MALfunct...@gmail.com` on 3 Mar 2015 at 10:17
* Blocking: #379

**Comment by hazendaz** [comment]
I will have a PR this weekend on dropping jdk 4 support, bringing spring framework and security both to latest 3 which are currently vulnerability free, plus updating the tomcat 6 through 8 versions to latest although that itself doesn't cause any adverse affects.  Spring 4 should be a drop in place for the most part as soon as that piece goes.  The quartz can come right after too.  Basically, we should be pushing the envelope here as far as we can.  The sooner the better.  Big companies are running scans that are making it clear status quo here will not be enough to allow usage.  Stay tuned...

**Comment by hazendaz** [comment]
Production Report.  Spring 3 works extremely well given the updates I did on my fork for our needs.  We are roughly two weeks into production at this point in time.  Due to some upcoming issues I see, it would be nice to finally cut 2.4.0 so spring 3/4 can come into proper usage ;)

**Comment by MALfunction84** [comment]
Agreed. The code restyling I'm working on is going to be very disruptive for this, isn't it? Do you know any way around it? I was just getting read to push, but I don't want to jeopardize your work.

**Comment by hazendaz** [comment]
You can move forward.  I can deal with the merge conflicts.  No problems there.  It will be disruptive but code styling is important.


Sent by Outlook for Android





On Fri, Jul 3, 2015 at 8:06 PM -0700, "Mark Lewis" <notifications@github.com> wrote:
Agreed. The code restyling I'm working on is going to be very disruptive for this, isn't it? Do you know any way around it? I was just getting read to push, but I don't want to jeopardize your work.

---

**Comment by hazendaz** [comment]
rather than deal with spring 4 and spring security at the same time, will deal with just spring 4.  Then will follow that up with spring security for 4.  pull request is coming.
