### ISSUE TITLE
New minimum requirements, road to 3.0?

### ISSUE THREAD

**Issue by jander99** [psi-probe/psi-probe#456]
I'd like to open this issue as a placeholder for discussing upgrading some of the infrastructure components which haven't really been touched since the fork from lambda-probe.  For the sake of the github move, let's target this for version 3.0.  We can use this as an opportunity to close older tickets that may no longer be relevant.  

### Tomcat
The minimum version now supported by apache is Tomcat 6.  Let's drop support for 5.0 and 5.5.  If someone is still using Probe on those versions, they can continue using version 2.x.  

### JBoss
The minimum version Probe should support would be JBossAS 5.x.  This would match with the Servlet 2.5 and JSP/EL specification of Tomcat 6.  Would be nice to get some statistics on how many psi-probe users are on JBoss. 

### Java
Since the requirement for Tomcat 6/JBossAS 5.x is Java 1.5, the minimum version of Java should be moved to Java 1.5.  However, Java 1.5 is quite old and at this point, so the recommendation should probably move to Java 1.6.  Tomcat 6 and JBossAS 5.x should still operate under Java 6.  And again, if users have issue with that, they can continue using version 2.x.  

### Libraries
An audit should be done on the number of libraries contained in this project.  By far this is probably the largest amount of work that needs to be done, as several libraries may no longer be supported or maintained.  We can work to identify lib functions that could be replaced by another better supported and more up-to-date library.  

### Move to organization
Should @MALfunction84 create an organization (free is fine, obviously) to host psi-probe so that others can help the development effort of the github repo and github pages? That would be up to them.  I personally think it'd be the right direction, to decouple the project from the user a little.  It could be the start of a community.  

So far this is what I've thought about.  I'd definitely like to hear other users input and get @MALfunction84's thoughts on how they see the future of the project.  

Thanks!

**Comment by MALfunction84** [comment]
I'm a big fan of all of this. I'd like to do the "Move to organization" right away, but I don't know how to move the repo and preserve all the issues. The Google Code Importer didn't seem to offer that as an option. Any ideas?

I'm a dude. You can use he/him instead of they/them. :)

**Comment by MALfunction84** [comment]
Okay, it would appear that "Transfer" under settings preserves everything. I'll see about doing that.

**Comment by jander99** [comment]
Gender pronouns noted. 

Here's two other things I found: https://gitter.im/ and https://github.com/google/error-prone.

**Comment by robertoschwald** [comment]
+1

**Comment by MALfunction84** [comment]
Transfer to "psi-probe" organization complete.

**Comment by MALfunction84** [comment]
I tried enabling error-prone. It emits errors without telling me which class(es) the errors are in.

**Comment by jander99** [comment]
Can you post the output from maven here if you still have that branch?

**Comment by MALfunction84** [comment]
Output:
```
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] PSI Probe
[INFO] PSI Probe Core
[INFO] PSI Probe Tomcat 5.0.x Adaptor
[INFO] PSI Probe Tomcat 5.5.x Adaptor
[INFO] PSI Probe Tomcat 6.0.x Adaptor
[INFO] PSI Probe Tomcat 7.0.x Adaptor
[INFO] PSI Probe Tomcat 8.0.x Adaptor
[INFO] PSI Probe Web Application
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building PSI Probe 2.4.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ psi-probe ---
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building PSI Probe Core 2.4.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ core ---
[INFO] Deleting C:\Users\mlewis\Projects\OSS\probe\github\psi-probe\core\target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ core ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\mlewis\Projects\OSS\probe\github\psi-probe\core\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ core ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 207 source files to C:\Users\mlewis\Projects\OSS\probe\github\psi-probe\core\target\classes
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] PSI Probe .......................................... SUCCESS [  0.137 s]
[INFO] PSI Probe Core ..................................... FAILURE [  5.859 s]
[INFO] PSI Probe Tomcat 5.0.x Adaptor ..................... SKIPPED
[INFO] PSI Probe Tomcat 5.5.x Adaptor ..................... SKIPPED
[INFO] PSI Probe Tomcat 6.0.x Adaptor ..................... SKIPPED
[INFO] PSI Probe Tomcat 7.0.x Adaptor ..................... SKIPPED
[INFO] PSI Probe Tomcat 8.0.x Adaptor ..................... SKIPPED
[INFO] PSI Probe Web Application .......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.177 s
[INFO] Finished at: 2015-04-07T09:57:04-04:00
[INFO] Final Memory: 30M/128M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project core: Compilation failure -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :core
```

Error:
```
error: types Map and Collection are incompatible; both define remove(java.lang.Object), but with unrelated return types
error: types Map and Collection are incompatible; both define remove(java.lang.Object), but with unrelated return types
error: types Map and Collection are incompatible; both define remove(java.lang.Object), but with unrelated return types
3 errors
```

**Comment by jander99** [comment]
So failed to compile because it actually found errors.  It just doesn't tell you where?  I wonder if this is because of generics and Java 1.4 support.  I'll file a separate enhancement request for error-prone for if we move to 1.5, and we can mark that off.  Would it be easier to start modifying the wiki page with ideas?

**Comment by MALfunction84** [comment]
But there aren't any generics in the code.

I like the idea of using separate issues for separate tasks. The wiki is more of a knowledge base than a place for tracking work or ideas.

**Comment by MALfunction84** [comment]
One thing I'd like to do in 3.0 is to move pretty much all of the server-specific code into the individual container adapters (note to self: also rename "adaptor" to "adapter") so the PSI Probe `core` library is as server-agnostic as possible.  For the cases where multiple server versions do things the same way (e.g. JNDI lookups), that should be a separate artifact/dependency injected into those container adapters.

This would be a *major* undertaking. I'd basically start by dropping Tomcat dependencies from the `core` artifact and pushing the broken implementations down into other artifacts. Then eventually I'd move all Spring controllers into the `web`, since they'd largely consist of calls to an injected instance of the TomcatContainer interface. Meanwhile, `core` would be the model, some utilities, and little else.

**Comment by jander99** [comment]
I like the idea of further decoupling runtime-specific logic from core.  Perhaps we have a Runtime interface with Tomcat6Runtime implementing Runtime, JBoss7Runtime implementing Tomcat6Runtime, etc.  Perhaps also support TomEE, Jetty, and Glassfish in a similar manner.  

I think we'd need a kind of workspace to hash this out.  Have you used https://trello.com/ before? I have no, but seems like it could be used for planning out projects in a psuedo-agile manner.

**Comment by MALfunction84** [comment]
The more the merrier. Such an architecture would more easily afford that, I think.  The biggest hurdle there is that the ContainerServlet interface serves as [the hook into Tomcat](https://github.com/psi-probe/psi-probe/blob/master/core/src/main/java/com/googlecode/psiprobe/ProbeServlet.java#L39), so already our controller is coupled to Tomcat APIs.

I've not used Trello, but I've seen colleagues use it. It's basically an issue tracker with a different UI. I'd really prefer the effort all be tracked here. I completely agree about a planning/design space, though. We could use the GitHub wiki for that, maybe? If you know of a better alternative, I'm all ears. (Thanks for all the suggestions on new tools, btw.)

**Comment by jander99** [comment]
Let's do a [wiki space](https://github.com/psi-probe/psi-probe/wiki/3.0) where folks can post their ideas on what a 3.0 would look like.  Maybe we need to pair down what to do in 2.4, finish up that work, release it, and start on 3.0? Some of the bugs that are set for the 2.4 milestone may no longer exist. I'm working on building a linux box where I can make some docker containers and qemu VMs so maybe I can test different configs with them.  I have a ton of ideas for 3.0, like db backends, and such. 

We're going to need the ability to have visio (draw.io?) diagrams of how things fit together.  This is starting to turn into an actual software development project.  Ha!

**Comment by MALfunction84** [comment]
Agreed on all points. If you see invalid issues in the 2.4 milestone, please point them out. My main goal for 2.4 was to get Tomcat 8 support working.

**Comment by jander99** [comment]
Should a branch be created for 3.0-dev that folks can start forking?

**Comment by MALfunction84** [comment]
Nah, then we'd just have to merge a bunch of 2.4's fixes in later. You hit the nail on the head earlier:

> we need to pair down what to do in 2.4, finish up that work, release it, and start on 3.0

**Comment by hazendaz** [comment]
Tomcat 8 support is highly needed.  Spring has to be upgraded before you cut 2.4 though.  I'm going to try to upgrade that portion this weekend.  Spring 2 is vulnerable code and we cannot use this library as a result now unless it is fixed ASAP.  I'd say get those two and cut 2.4.0.

Then, don't worry about the past.  This will be secure and stable.  Drop the legacy support.  All of it.  No more tomcat 5 or 5.5 since they are not supported for a very long time at this point.  Drop JSP in favor of REST / angular or bootstrap arrangement.

Splitting things up, definitely needed.  The core is actually dependent on tomcat 5 to start with.  So defintely need to make it as decoupled as possible.

**Comment by hazendaz** [comment]
JBoss is no longer a derivative of tomcat.  Wildfly is using undertow.  So would it make sense to just get up to the last JBoss released for the enterprise and/or drop that support.  This is primarily for tomcat instances anyways and with that landscape changing drastically maybe it is not worth attempting to support plus anyone using this is really on 2.3.3 anyway.  At least with the geting spring upgraded, the old support could be the signaled end of the road.  And anyone else on older jdks don't care about security at all or they wouldn't be there.  Again they can use old stable versions.

**Comment by MALfunction84** [comment]
Wow, I haven't seen this much engagement in years! Thanks for all of the enthusiasm.

I'd like to keep 2.4 scoped to adding Tomcat 8 without removing anything if possible. @hazendaz, when you talk about Spring 2.5 being vulnerable, which vulnerabilities do you mean?

**Comment by MALfunction84** [comment]
Hey guys, I want to get a poll up to gather some feedback about scoping 2.4 and 3.0. I especially want opinions about dropping legacy support. Any suggestions for a good polling platform?

**Comment by hazendaz** [comment]
There is a maven plugin that can be added to scan on a site build that will list all nvd known vulnerabilities.  Owasp provides it.  I'll add that tonight in a PR with directions so you can see the issues.  Commons file upload is also vulnerable.

--- Original Message ---

**Comment by MALfunction84** [comment]
@hazendaz Much appreciated.

**Comment by MALfunction84** [comment]
I've filed #474 for the vulnerability scan plugin.

**Comment by diogosantana** [comment]
@MALfunction84 Have you consider create a mailing list or something like a Google Group to discuss the future of probe without create tons of comments on issues?

**Comment by MALfunction84** [comment]
There is a Google Group [here](https://groups.google.com/forum/#!forum/psi-probe-discuss), but that one was primarily for discussions by users. I can create another one for developers and contributors, but is Google Groups a good platform for that? Someone had mentioned [Gitter](http://gitter.im) also. Let's continue the discussion in #480.

More generally, I'm trying to get roadmaps for [2.4](/psi-probe/psi-probe/milestones/2.4.0) and [3.0](/psi-probe/psi-probe/milestones/3.0.0) built up. I will move things around based on user/developer feedback of priorities. Each actionable item mentioned in this issue has been filed as a distinct issue or already addressed, so I'm closing this one.

* (Done) ["create an organization (free is fine, obviously) to host psi-probe"](#issue-64648943)
* #471: ["Let's drop support for 5.0 and 5.5."](#issue-64648943)
* #472: ["the recommendation should probably move to Java 1.6"](#issue-64648943)
* #457: ["An audit should be done on the number of libraries contained in this project"](#issue-64648943)
* #470: ["Drop JSP in favor of REST / angular or bootstrap arrangement"](#issuecomment-94119223)
* #474: ["There is a maven plugin... that will list all nvd known vulnerabilities."](#issuecomment-94500890)
* #449: ["Spring 2 is vulnerable code"](#issuecomment-94500890)
* #480: ["Have you consider create a mailing list... to discuss the future of probe...?"](#issuecomment-94592988)

Keep 'em coming, guys. Just please file them as separate issues. Thanks!
