### ISSUE TITLE
Using JDK 8 jdeps in Maven

### ISSUE THREAD

**Issue by jander99** [psi-probe/psi-probe#457]
Just a placeholder for eventually using jdeps as a way to determine which libraries are really needed, thus cleaning up the pom file(s) for this project.  

https://github.com/marschall/jdeps-maven-plugin

The only requirement is that the build use jdk 8, not that the project is only jdk 8 compatible.  It it stands now, travis will build the project using jdk8 javac.

**Comment by MALfunction84** [comment]
We can build a profile that runs this plugin only on JDK8.
