### ISSUE TITLE
Missing gif

### ISSUE THREAD

**Issue by reinert** [psi-probe/psi-probe#466]
Sometimes the app unsuccessfuly tries to load the gif **rb_0+6.gif** at [webapp/css/classic/gifs](https://github.com/psi-probe/psi-probe/tree/master/web/src/main/webapp/css/classic/gifs)

Chrome error:
http://localhost:8080/probe/css/classic/gifs/rb_0+6.gif Failed to load resource: the server responded with a status of 404 (Not Found)

![image](https://cloud.githubusercontent.com/assets/1285494/7209621/b063e204-e520-11e4-9f3b-a2f72ef89d2b.png)

**Comment by MALfunction84** [comment]
Huh. That should never happen. Those gifs are 5px wide. Gotta be an error in com.googlecode.psiprobe.jsp.VisualScoreTag

**Comment by diogosantana** [comment]
I create a unit test to check when this could happen based on `datasources.htm` usage of `probe:score`, but without sucess.

`probe:score` is used in 7 pages. @reinert can you provide more details about error? The page you are accessing and the others columns values like M, E and B?

When I confirm the bug via unit test, I will create a PR.

**Comment by jander99** [comment]
I also looked at this today a bit.  There might be an off-by-one bug in the
Tag @MALfunction84 mentioned.  There is some code that increments the last
digit of the filename.  At some point it incremented to 6, which makes a
filename that will 404.

**Comment by diogosantana** [comment]
Did you reproduce the bug?

I did a range test to all possible values to see if there was any 6 result. None found.

Check https://github.com/diogosantana/psi-probe/commit/252cd132336f64bdebcbf0d1fa3eb15aff2a007d.

**Comment by diogosantana** [comment]
The unit test was wrong at https://github.com/diogosantana/psi-probe/commit/252cd132336f64bdebcbf0d1fa3eb15aff2a007d.

Now it is fixed and it confirm the bug.

Please check https://github.com/diogosantana/psi-probe/commit/01825eafc74a3696e9acb30145205f929b30f159.
