### ISSUE TITLE
Oracle Dependencies

### ISSUE THREAD

**Issue by hazendaz** [psi-probe/psi-probe#468]
Oracle dependencies appear to be targetting 11g for UCP and 10 for OJDBC.  Neither are available in central due to licensing restrictions.  I'm just jumping in here and builds fail as a result.  In order to make the build work as described on the landing README, it should store the jars directly in this project under a thirdParty directory with a bat file to load it into local maven.  I do this on a project for other needs already so I can port that over here.  That is unless I'm missing something here.

**Comment by hazendaz** [comment]
OK _ found why this doesn't work for me.  I have my own nexus repo.  So this won't work.  Actually none will based on my usage.  I'm sure I'm not alone.  So better to solve this in another way.  I've got oracle pulled down, placed in a directory with a cmd file to build it.  This integrates in nicely with travis-ci as well.  I'll take the same approach with all so I can get a clean build then toss this up to see what you think about this approach.

		<repository>
			
			<snapshots>
				<enabled>false</enabled>
				<updatePolicy>never</updatePolicy>
			</snapshots>
			<id>code.lds.org</id>
			<name>code.lds.org</name>
			<url>https://code.lds.org/nexus/content/repositories/main-repo/</url>
			<layout>default</layout>
		</repository>

**Comment by hazendaz** [comment]
I've got a fully working windows/unix setup for this.  Travis CI builds are good.  Essentially I added a new project to the mix that uses the exec-maven-plugin to get the oracle / jmxri jars in place.  It's in the multi module build and assures repeatable success.  I'll have a PR on this sometime this weekend.  I'm additionally working on getting spring 3 completely in place.  I've got the spring 3 framework all going now.  I'm having a bit more trouble getting spring security 3 going but expect to have that resolved sometime tomorrow night.  There will be a number of things in my PR that come through.  I've did my best to make very clean commits.  In only one case, that didn't work completely as I would have wished but the entire set itself is going to be good.  At the time I get the PR up, please look and review.  If you feel the need to pull in smaller pieces at a time or adjustments needed due to the still continuing legacy support let me know and I can adjust accordingly.  Appreciate it!  My intent regardless is that as soon as I get this working on spring 3, I will be building and deploying that within the month to a production instance.  The issue currently is that spring 2 in any form we are not allowed using so we either remove psi-probe entirely or get this fixed.  I prefer getting this fixed.  When that dust settles, I'll come back in with spring 4 which I feel will be a drop in place at that point with no further changes.  The library is going to have to go java 6 shortly though.  And for what we are doing, we will be running this in tomcat 8.0.21 and jdk 1.8.0_45 on red hat linux.

**Comment by MALfunction84** [comment]
Appreciate the work and consideration!  Right now, Travis-CI is working just fine pulling Oracle artifacts from code.lds.org. Are you saying that doesn't work for you? Can you provide more information about the problem you're having? No one else has reported this issue. Maybe wait a bit before submitting a PR to see if this issue is widespread.

Also, please try to separate out your independent fixes into multiple PRs. (An update to Spring 3 is currently out-of-scope for 2.4, but I'm looking for more feedback on this. Let's keep that discussion over on #456.)

**Comment by hazendaz** [comment]
I sit behind my own nexus repo.  It ignores pom repos.  So either I add those to my nexus or figure out automation that works nicely for all.  My PR has my solution.  I would assume smaller number of users would be affected on a personal level but that would increase on the enterprise.

--- Original Message ---

**Comment by MALfunction84** [comment]
@hazendaz I haven't seen any other comments on this issue. I know the PR you were talking about was closed to be broken up into multiple PRs. Do you want to submit a new one or close this?

**Comment by jander99** [comment]
I think we have to assume that since oracle poms will not be part of maven's central repo, the solution for the project is to use a "public"ish (as in not behind any firewalls and accessible from the internet) repo that contains the artifacts we need.  If users are forbidden from using maven central or any public"ish" repos that this project references in any pom.xml, then those users need to be responsible for forking a version that can work for them.  I think its easy enough, i.e. to switch this project to an Artifactory repo so long as all referenced artifacts are present in that private repo.  

Maybe on the wiki we can list the pom files that need to be loaded in a BTF nexus/artifactory repo for this to build if a user points the project elsewhere.

**Comment by MALfunction84** [comment]
We used to include instructions for how to create those poms yourself. The [ojdbc14-pom.xml](/psi-probe/psi-probe/blob/master/ojdbc14-pom.xml) and [ucp-pom.xml](/psi-probe/psi-probe/blob/master/ucp-pom.xml) files are still in the repository.

@jander99 Are you suggesting that users whose infrastructure restricts them from building this project as-is must circumvent on their own? If so, then I agree. Travis-CI works. Maybe the solution is to have a nightly build (#499).

**Comment by diogosantana** [comment]
+1 to @jander99 idea.


Diogo Sant'Ana

**Comment by jander99** [comment]
Yes, we delivery a buildable solution for normal folks, and then anyone who has a special case can change their fork of the project.  How else would any other maven-based open source project work for these special people?

**Comment by hazendaz** [comment]
I planned to submit a new one a little down the road.  It would be probably be targeted for 3.0.  You can close this for now if you like.

--- Original Message ---

**Comment by hazendaz** [comment]
The special folks I'm referring is mainly anyone that builds this in a corporate setting where they are forced to use a corporate repo and do not have the ability to add the extra repos to pick up those dependencies.  Now given those users likely already have those onsite.  I'm not sure how many open source developers might stand behind their own nexus repo as I do.  The core issue is simply it causes more work that just typing mvn clean install.  My solution works perfectly solving the issues but I'm not sure if oracle licenses allow what I'm doing.  But then again I don't see what I'm doing being any different than the repos that have those jars.

--- Original Message ---

**Comment by jander99** [comment]
I work at a place that blocks maven central. I have to use our artifactory with anything maven or (in our case) ivy, so I completely understand.  In my case, even to use this software I would need to get approval to add all jars required to build, with the proper versions, to our artifactory.  It is alot of work no matter what.  This work would be duplicated for any open source project I wanted to use at my job.

In those cases, I basically look for a release .jar, .war, .exe whatever that I can directly use that I don't need a build system for.  Most of the "customers" this project has will likely be grabbing a release tarball/zip for direct deployment and would not be touching the code.  Therefore, this project should have the proper maven directives for a proper build that can be put in github's releases section.

**Comment by MALfunction84** [comment]
The Oracle dependencies have always been a problem. Technically, lds.org is violating Oracle's licensing agreement by making them publicly available. Those artifacts might disappear at any time, so I'm going to leave this open for now because we still need a long-term solution.

**Comment by hazendaz** [comment]
11g are now availabe in the 'safer' way psi probe uses the dependencies.  I will be submitting PR request shortly.

**Comment by hazendaz** [comment]
code.lds.org now has 11g drivers.  PR coming with updates to oracle poms and build pom.

**Comment by MALfunction84** [comment]
I think we've been talking about two different problems. One was that the Oracle dependencies needed to be updated. That has been solved by the referenced PR.

The second problem, which is still a problem, is that we have no reliable way use Oracle dependencies in an open-source Maven project because the dependencies are encumbered by a closed-source license. I'm going to open a separate issue for this second problem.

**Comment by hazendaz** [comment]
Thanks.  That was exactly the issue.
