### ISSUE TITLE
Drop support for Tomcat 5.0, 5.5, and 6.0

### ISSUE THREAD

**Issue by MALfunction84** [psi-probe/psi-probe#471]
Tomcat 5.0 and 5.5 are no longer needed.

**Comment by MALfunction84** [comment]
Removing Tomcat 6 too makes #473 that much easier.

**Comment by MALfunction84** [comment]
Fixed in ca8a4f8.

**Comment by diogosantana** [comment]
Oh! That feels good! lol

**Comment by MALfunction84** [comment]
Yeah, like taking off your shoes at the end of the day.

**Comment by MALfunction84** [comment]
So if Apache will keep Tomcat 6 going [through the end of 2016](http://mail-archives.apache.org/mod_mbox/www-announce/201506.mbox/%3C556ECB68.2080804@apache.org%3E), why are we dropping it now? The primary reason was mentioned above: #473. Servlet API 3.0 will let us loosely couple Tomcat to the core module, but Tomcat 6, being Servlet 2.5, doesn't let us do that.

Another reason is that, given the long development cycles lately, it's entirely possible we won't see PSI Probe 3.0 drop until after Tomcat 6 has reached EOL. I only mostly joking.

**Comment by jander99** [comment]
Most folks are probably already on 7+ anyway.  I'll look for stats...
