### ISSUE TITLE
Set up discussion area for developers

### ISSUE THREAD

**Issue by MALfunction84** [psi-probe/psi-probe#480]
We need a place for developers to discuss and plan PSI Probe's development. Ideally, there would be a way to solicit feedback from PSI Probe users as well to steer the discussions.

Couple of platforms that have come up:

* Google Groups
* Gitter

**Comment by diogosantana** [comment]
Gitter is just for chat? No topic like feature?

**Comment by MALfunction84** [comment]
You can have multiple channels for different topics, but you're right; it's not a forum. Any suggestions?

**Comment by MALfunction84** [comment]
Found [Poll](https://github.com/adambutler/poll) for gathering user feedback.

**Comment by diogosantana** [comment]
I use a lot mailing list, but have no experience in setup one. Google Groups is not a possibility?

**Comment by MALfunction84** [comment]
Google Groups is possible. I just wasn't sure if there was another option that integrated better with GitHub. This is usually the point where @jander99 jumps in to drop some knowledge on me.

**Comment by jander99** [comment]
Could this be our use case for https://trello.com?

**Comment by MALfunction84** [comment]
Hmm, that really does seem more of a notes/planning app than a discussion forum. Does it integrate with GitHub?

**Comment by jander99** [comment]
I can't quickly find anything.  Perhaps we spin off something new...

**Comment by MALfunction84** [comment]
There is already a google group [here](https://groups.google.com/forum/#!forum/psi-probe-discuss), but it's sort of generic. Should developers have a dedicated group, or are you guys okay sharing a space with users?

**Comment by diogosantana** [comment]
We could use this group. If it get a high volume of mix messages, we create
a second one. Is that ok?


Diogo Sant'Ana

**Comment by MALfunction84** [comment]
Sounds good to me.
