### ISSUE TITLE
Add servlet-api and jsp-api dependencies to web project

### ISSUE THREAD

**Issue by diogosantana** [psi-probe/psi-probe#482]
Add servlet-api and jsp-api dependencies to web project.

@hazendaz I still getting the spring-security xsd not found on validation. But since .settings is on gitignore, I can suspend xml validation and get no modified file. That works for me, until Spring 3.

**Comment by MALfunction84** [comment]
These should be indirect dependencies of web already.

* web => core => servlet-api-2.4
* web => core => jasper-compiler => jsp-api-2.0

What's the motivation for adding them directly to web?

**Comment by diogosantana** [comment]
Both are provided in core and not visible in web.

Try to add a servlet to web a run mvn clean package. It won't compile web.

    package web;
    
    import java.io.IOException;
    
    import javax.servlet.ServletException;
    import javax.servlet.http.HttpServlet;
    import javax.servlet.http.HttpServletRequest;
    import javax.servlet.http.HttpServletResponse;
    
    public class TestServlet extends HttpServlet {
    
    	private static final long serialVersionUID = 3412500610604747990L;
    
    	protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
    		System.out.println("teste");
    	}
    }

Compile message:

    TestServlet.java:[5,20] error: package javax.servlet does not exist

**Comment by hazendaz** [comment]
Yup it is jsp related.  It has a huge amount of errors otherwise in eclipse.  This is the fix.

--- Original Message ---

**Comment by MALfunction84** [comment]
> Try to add a servlet to web a run mvn clean package. It won't compile web.

There is currently no Java source in the web module. I don't understand the desire to to add a dependency that wouldn't be used. But I guess if Eclipse requires it...

**Comment by hazendaz** [comment]
Jsp code.  Eclipse validates and flags as an error.  This just clears the error.  It didn't affect the maven build itself.  In jsp eclipse allows code completion like elsewhere.  That said it cannot do its job without this.  So we are all good now.  Longer term expression language should be use in jsp rather than java code...

--- Original Message ---
