### ISSUE TITLE
Allow users to download latest SNAPSHOT build

### ISSUE THREAD

**Issue by MALfunction84** [psi-probe/psi-probe#499]
Make the most recent successful build available for download.

**Comment by MALfunction84** [comment]
Travis has [documentation](http://docs.travis-ci.com/user/deployment/releases/) about uploading releases to GitHub, but it only works for tags.

**Comment by hazendaz** [comment]
You could just manually upload build points.  https://github.com/psi-probe/psi-probe/releases

**Comment by MALfunction84** [comment]
I'd much rather provide an automated build of master's HEAD, direct from Travis. Surely I'm not the only one.

**Comment by hazendaz** [comment]
One option might be to add sonatype into the mix and push to central.

http://central.sonatype.org/pages/apache-maven.html

**Comment by hazendaz** [comment]
Maven central push exists now.  I'll work on travis in coming week to get snapshots auto-uploaded.  It's quite trivial as I do this across all of the mybatis projects.

**Comment by MALfunction84** [comment]
:+1:

**Comment by hazendaz** [comment]
Autobuilds now working as of #696 for snapshots

[here](https://oss.sonatype.org/content/repositories/snapshots/com/github/psi-probe/)

**Comment by MALfunction84** [comment]
@hazendaz You are the man.
