### ISSUE TITLE
Optimize Imports

### ISSUE THREAD

**Issue by jander99** [psi-probe/psi-probe#510]
We should optimize imports.  This will clean up some of the code.

**Comment by MALfunction84** [comment]
I'm thinking of folding this into #512. Objections?

**Comment by MALfunction84** [comment]
Keeping this separate from #512 for now. If a single commit fixes both, that's not the end of the world.

**Comment by MALfunction84** [comment]
Organizing these according to [Google's style guide](http://google.github.io/styleguide/javaguide.html#s3.3-import-statements)...

**Comment by MALfunction84** [comment]
I think I co-opted this issue when I misread the title as "Organize imports." If "Optimize imports" is something else, please re-file. Sorry about that.
