### ISSUE TITLE
Reformat code according to conventions and include formatting configuration for IDEs

### ISSUE THREAD

**Issue by MALfunction84** [psi-probe/psi-probe#512]
**This is not a debate area.** If you want to argue about code conventions, go post on the [Google Group](https://groups.google.com/forum/#!topic/psi-probe-discuss/z6GtjJni_iE). I will regretfully delete any off-topic comments made here.

Seems like the top three IDEs are Eclipse, IntelliJ, and NetBeans. Whatever conventions we adopt, we should commit the appropriate configurations for these IDEs so that contributors don't have to worry about it.

We probably shouldn't actually apply the formatting changes to all the code until just before we create the 2.4 branch.

**Comment by hazendaz** [comment]
Adding reference link for google styling as they provide preconfigured settings for intellij and eclipse styles among other things.

https://code.google.com/p/google-styleguide

**Comment by MALfunction84** [comment]
I'm trying out https://github.com/revelc/formatter-maven-plugin with Google styling. There are a few long statements and expressions that get mangled. I'm working to break them up so I can run the formatter indiscriminately.

**Comment by MALfunction84** [comment]
Checkstyle is still reporting 562 warnings. Well, let's get crackin'...

**Comment by hazendaz** [comment]
Is checkstyle setup now to use Google checks?


Sent by Outlook for Android





On Fri, Jul 17, 2015 at 7:34 PM -0700, "Mark Lewis" <notifications@github.com> wrote:
Checkstyle is still reporting 562 warnings. Well, let's get crackin'...

---

**Comment by MALfunction84** [comment]
@hazendaz Yes. Eventually I plan to add checkstyle as a build plugin so it's enforced on every build, including PRs.

**Comment by MALfunction84** [comment]
I'm using a slightly older version of google_checks.xml (6.7) because the newest release of checkstyle produces an error with older configs. See checkstyle/checkstyle#1275. It's fixed in checkstyle-6.9, which should be released soon.

**Comment by MALfunction84** [comment]
In the interests of getting a release out, I'm calling this one done. The remaining checkstyle warnings are about documentation, which is not exactly code style. The remaining checkstyle checks will be addressed in #540.

**Comment by hazendaz** [comment]
Mark you have certainly been busy.  Glad to see the official release.  I’ll try to hop over with spring 3 stuff later this week.  I tried spring 4 but couldn’t quite get that working and I’m not 100% confident I got spring 3 all the way configured correctly.  Will need a helping hand :)

 

As an aside, do you know if tomcat is officially done with tomcat 6 or is the thought that this project just will be?  I cannot imagine enough changing in 6 at this point anyways but was curious as I support tomcat 6 in another project.

 

Thanks,

 

Jeremy

**Comment by MALfunction84** [comment]
Jeremy, thanks! Spring 4 is new to me as well, so it appears I'm in good company. :) I've addressed your Tomcat question over on #471 to keep it on-topic.
