### ISSUE TITLE
Remove com.googlecode from package names

### ISSUE THREAD

**Issue by MALfunction84** [psi-probe/psi-probe#513]
The current package name is ```com.googlecode.psiprobe```. We should probably change it to something divorced from wherever the code is being hosted at the time. I'm thinking of going with just ```psiprobe``` since there's not really any URL out there that represents the brand or company. Any better suggestions?

**Comment by jander99** [comment]
s/googlecode/github/g

Could just swap out googlecode for github. Or take donations for the
$12/year to own psiprobe.com?

**Comment by MALfunction84** [comment]
I'm not inclined to use ```com.github``` for two reasons. First, that prefix should be reserved for GitHub itself. Second, if we ever move again, we'd have to change again.

I'm also not inclined to register a domain name for this tiny project.

**Comment by jander99** [comment]
In that case, since honestly it really doesn't matter what we call packages
(foo compiles) then psiprobe.x.y.z is fine by me.  Not sure if you want to
take a vote.  There are a lot of references to package.x.y.z.class so what
we choose should reflect readability there as well.

**Comment by hazendaz** [comment]
Are there plans to release this to maven central?  I fixed the SCM tags on PR #514.  It would need sonatype parent added.  Sonatype requires it to be either owned or states we can use com.github.* since we are hosted here and many other projects do that.  I understand the not wanting to change again so that doesn't mean we have to have the internal packaging even changed from what it is now.  Just for release purposes, it could be pushed based on the hosting.  That is a much smaller change in scope than this effort would be.

**Comment by hazendaz** [comment]
Good example for the packaging not matching maven pom would be mybatis.  It still uses org.apache.ibatis in the core components.

**Comment by MALfunction84** [comment]
No, I had never *planned* to release this to Maven central. That doesn't mean we never will. I just can't imagine anyone pulling in one of PSI Probe's artifacts as a dependency. Maybe if we had broken it up differently...

**Comment by jander99** [comment]
Psi probe core, maybe. Depends how its split between api and UI.

**Comment by hazendaz** [comment]
I would pull the war version maven.  I've got a tomcat maven buildout for various environments so at the moment this war is local in my maven build.  If it were in central I could pull that out.  Odd case for sure I guess.  Well if this happens down the road....so be it.  In the meantime I'll play around with testing the ability to do so in order to fix up any maven related items so it's possible.  More to come...

--- Original Message ---

**Comment by hazendaz** [comment]
Back on this topic, I do have a need for this being in nexus again primarily for the war.  However, in doing so, it's going to require the pom group Id to be 'com.github.psi-probe'.  That is the only way we can release to sonatype.  Second, the artifactId naming really needs adjusted so it's clear this is all psi-probe artifacts.  

Here is what I'm thinking.
- psi-probe-core
- psi-probe-tc7-adaptor
- psi-probe-tc8-adaptor
- psi-probe-tc9-adaptor
- psi-probe-web with final name as psi-probe

Thoughts?

**Comment by MALfunction84** [comment]
I'd prefer not to have the groupId be tied to wherever we're hosting. Been bit by that one before! How strict is that requirement?  *Must* it be `com.github.psi-probe`, or could it be just `psi-probe`?

The new artifact names are okay. I'd prefer to spell out "tomcat." I also prefer "adapter" over "adaptor,"as you could guess by eeb4ca7. Or maybe just leave that part out entirely:
  * psi-probe-core
  * psi-probe-tomcat7
  * psi-probe-tomcat8
  * psi-probe-tomcat9
  * psi-probe-web (still becomes probe.war -- Changing this would be a disruptive.)

**Comment by hazendaz** [comment]
For release purposes, just poms would reflect where project is hosted.  Sounds like time to get a domain registered.  Sonatype is picky like that.  I tried to use unregistered domain before and they told me to either own it or use github.  For packaging, if we don't own the domain then it can be just as you originally suggested.


Sent from Outlook Mobile






On Tue, Jan 19, 2016 at 8:16 PM -0800, "Mark Lewis" <notifications@github.com> wrote:





I'd prefer not to have the groupId be tied to wherever we're hosting. Been bit by that one before! How strict is that requirement?  *Must* it be `com.github.psi-probe`, or could it be just `psi-probe`?

The new artifact names are okay. I'd prefer to spell out "tomcat." I also prefer "adapter" over "adaptor,"as you could guess by eeb4ca7. Or maybe just leave that part out entirely:
  * psi-probe-core
  * psi-probe-tomcat7
  * psi-probe-tomcat8
  * psi-probe-tomcat9
  * psi-probe-web (still becomes probe.war -- Changing this would be a disruptive.)

---

**Comment by hazendaz** [comment]
Sounds like this may end up looking like the waffle project.  If you have some time looks in my repos for waffle to see how that looks.  Java code there is under source/jna


Sent from Outlook Mobile






On Tue, Jan 19, 2016 at 8:16 PM -0800, "Mark Lewis" <notifications@github.com> wrote:





I'd prefer not to have the groupId be tied to wherever we're hosting. Been bit by that one before! How strict is that requirement?  *Must* it be `com.github.psi-probe`, or could it be just `psi-probe`?

The new artifact names are okay. I'd prefer to spell out "tomcat." I also prefer "adapter" over "adaptor,"as you could guess by eeb4ca7. Or maybe just leave that part out entirely:
  * psi-probe-core
  * psi-probe-tomcat7
  * psi-probe-tomcat8
  * psi-probe-tomcat9
  * psi-probe-web (still becomes probe.war -- Changing this would be a disruptive.)

---
