### ISSUE TITLE
Oshi project

### ISSUE THREAD

**Issue by hazendaz** [psi-probe/psi-probe#521]
This project is very interesting regarding information it provides on the OS.  I've started working on this specific project and wondered if this might be something that may end up being useful with psi-probe.  I don't know how much if any overlap there might be but wanted to at least mention this.  I'm not even sure I'll end up using this either.  I was recently asked to help out with mavenization efforts based on my work elsewhere.  The project does now require java 7 so it would be sometime before this can be used here if at all.  Please take a look and see if this is anything that can be used.

https://github.com/dblock/oshi

**Comment by MALfunction84** [comment]
It certainly has more information than the current System Information section. I see value in that.

**Comment by hazendaz** [comment]
Initial work...

![psi-probe](https://cloud.githubusercontent.com/assets/975267/13657636/cac5f45a-e63e-11e5-99c3-91fd9d995f19.png)

**Comment by hazendaz** [comment]
No plans to bring this in just yet as there are still things in oshi that are not consistent enough and probably more information that can be gathered I haven't figured out yet.  Just wanted to get detailed information up on what this has to offer and where it might go.

**Comment by MALfunction84** [comment]
Nice!

I'm noticing some some overlap with other sections under System though. A tab called "Oshi" doesn't make its content easily discoverable for those not familiar with that name and what the lib does. I'd much rather see the information under "Overview" or "System Properties," and then some headers to group related metrics (CPU, Memory, Disks, etc).

But yeah, this looks really useful!

**Comment by hazendaz** [comment]
I expect to bring this in under 'experimental usage'.  It requires java 8 to work so travis builds will need switched to run 8 only but we are avoiding pulling in any direct 8 items which happens to only exclude one thing in oshi.  To work it will require java 8 and I'll have to work out details still to prevent it from outright failing when running java 7.  I did expand the naming that fits (OS/Hardware Info).  This will likely close out another issue too but is just a big dump of data for now.  Since Oshi is under constant development I don't want to just yet force a lot in until we can better see how this works across platforms and how we might either replace internal pieces with it or simply use it in a nicer looking way.  I've also fully noted this on the output that its to be treated as an experimental feature.

**Comment by hazendaz** [comment]
oshi reverted to java 7.  I've brought this in under experimental usage.  Leaving this ticket open for now.

**Comment by hazendaz** [comment]
This is part of project now and on released versions.  Closing this ticket.  It is still experimental only in so much that it is slow but it does work cross platform.
