### ISSUE TITLE
dependency scope optimizations

### ISSUE THREAD

**Issue by robertoschwald** [psi-probe/psi-probe#529]
While trying to setup the project in Intellij IDEA, I noticed that Intellij tries to deploy many artifacts during debugging.

This is caused because the Tomcat-Version specific artifacts are not scoped "provided".
I provide a pull request to fix this.

**Comment by MALfunction84** [comment]
@robertoschwald Are you sure this was because of the absence of ```<scope>provided</scope>``` in one under the ```<dependencyManagement>```? The ```<scope>provided</scope>``` is declared in the ```<dependencies>```...

**Comment by robertoschwald** [comment]
Yes. It seems due to some limitations, IDEA ignores the scopes in the dependencies section and deploys the tomcat libs..

**Comment by MALfunction84** [comment]
Oh. Well then I probably broke this again with 6ded585. Can you confirm?
