### ISSUE TITLE
Global/application datasources not listed on Tomcat 6 and 7

### ISSUE THREAD

**Issue by diogosantana** [psi-probe/psi-probe#531]
Dividing #490 to conquer. I fixed the Tomcat 6 and Tomcat 7 issue. Tomcat 8 is more complicated because of https://github.com/psi-probe/psi-probe/issues/490#issuecomment-105272331:

Tomcat 8 changes tomcat-dbcp package name from org.apache.tomcat.dbcp.dbcp to org.apache.tomcat.dbcp.dbcp2. So datasources don't show up because org.apache.commons.dbcp.BasicDataSource can't find the new package name.

@MALfunction84 Should I create a separated issue to Tomcat 8 or we use #490?

**Comment by robertoschwald** [comment]
Will you push the TC7 fix, soon? I badly wait for a fix.

**Comment by diogosantana** [comment]
It is pushed: #532

**Comment by robertoschwald** [comment]
Great. I Test it locally.

**Comment by MALfunction84** [comment]
@diogosantana I would prefer a separate issue for Tomcat 8. Thanks!
