### ISSUE TITLE
All 127.0.0.1 behind a cache proxy

### ISSUE THREAD

**Issue by mohsen** [psi-probe/psi-probe#533]
Can you please do something like this to take remote address to show in connectors.jsp. Most proxy servers add a X-Forwarder-For header to the original HTTP request.

    public static String getRemoteAddress(HttpServletRequest request) {
        if (request == null) {
            return null;
        }
        String xff = request.getHeader("X-Forwarded-For");
        return xff != null ? xff : request.getRemoteAddr();
    }

**Comment by MALfunction84** [comment]
Duplicate of #317.
