### ISSUE TITLE
Global/application datasources not listed on Tomcat 8

### ISSUE THREAD

**Issue by diogosantana** [psi-probe/psi-probe#534]
Tomcat 8 changes tomcat-dbcp package name from org.apache.tomcat.dbcp.dbcp to org.apache.tomcat.dbcp.dbcp2. So datasources don't show up because org.apache.commons.dbcp.BasicDataSource can't find the new package name.

Originally from #490.

**Comment by diogosantana** [comment]
@MALfunction84 Can you mark 2.4 on this?

**Comment by MALfunction84** [comment]
@diogosantana This didn't require anything like 7cc44ae or e4a871a?

**Comment by diogosantana** [comment]
It is already done in `Tomcat80ContainerAdaptor`, but in a slightly different way because of how securty tokens are configured in Tomcat 8.
