### ISSUE TITLE
Indirectly reference missing on Tomcat55ContainerAdaptor

### ISSUE THREAD

**Issue by diogosantana** [psi-probe/psi-probe#537]
After 6ded58581641ea6fdd034d89f29fc5e6fe8ff779 Eclipse's compiler accuses indirectly reference missing on Tomcat55ContainerAdaptor.

Full error message: `The type org.apache.tomcat.util.http.mapper.Mapper cannot be resolved. It is indirectly referenced from required .class files`.

Cause: 6ded58581641ea6fdd034d89f29fc5e6fe8ff779 removes tomcat-util dependency. I don't know whether this was intentional or not.

**Comment by MALfunction84** [comment]
Sorry. Thanks for catching and fixing.
