### ISSUE TITLE
Release 2.4.0

### ISSUE THREAD

**Issue by davidmsibley** [psi-probe/psi-probe#539]
Could you run a maven release of the new code at some point?  It's been two years since the last release, and the 2.3.3 tag isn't natively buildable due to a svn specific build number plugin.

Of course people can pull down master to get support for tomcat 8, but a tag of the stable product with that addition would be nice.

**Comment by MALfunction84** [comment]
Doing some last-minute cleanup. I anticipate an official release this week.

**Comment by MALfunction84** [comment]
I'm running behind trying to clean up all the code. Expect delays. Sorry.

**Comment by jander99** [comment]
Anything we can assist with?

**Comment by MALfunction84** [comment]
Run `mvn checkstyle:checkstyle-aggregate` to generate the list of warnings under target/site/checkstyle-aggregate.html. I think the only thing it needs now is javadoc on public APIs.

I know that seems like a silly thing to hold up a release, but I'm trying to get all the major cleanup done so that I can enable strict checks *before* branching 2.4.

**Comment by MALfunction84** [comment]
If you want to help with javadoc cleanup, feel free to open a single PR per package and commit fixes for one class at a time. This should help us avoid collisions and duplicate effort.

**Comment by MALfunction84** [comment]
Tracking the above work in #512 still.

**Comment by diogosantana** [comment]
Mark, why you don't release just the way it is? This cleanup is taking too long to release. It's a little frustrate to me, because I did make a effort to fix the remaining issues to 2.4.

My vote is to release asap. :)

**Comment by MALfunction84** [comment]
You're quite right. 2.4.0 released.

**Comment by diogosantana** [comment]
Thanks. I appreciate it!

**Comment by isuftin** [comment]
:+1: :+1: :+1: :+1: :+1:
