### ISSUE TITLE
Maven Package test error

### ISSUE THREAD

**Issue by christophe-lechenadec** [psi-probe/psi-probe#543]
when I want to create the probe.war, mvn package,
I have 2 errors on tests

testLocalhost(com.googlecode.psiprobe.tools.WhoisTests)  Time elapsed: 0.274 sec  <<< ERROR!
java.net.ConnectException: Connexion refusée

testGoogle(com.googlecode.psiprobe.tools.WhoisTests)  Time elapsed: 0.006 sec  <<< ERROR!
java.net.ConnectException: Connexion refusée

Environnement :
Ubuntu 14.04.3 LTS

Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T13:57:37+02:00)
Maven home: /root/apache-maven-3.3.3
Java version: 1.8.0_51, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: fr_FR, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-61-generic", arch: "amd64", family: "unix"

**Comment by MALfunction84** [comment]
I cannot reproduce, but I've seen those tests fail when a firewall was blocking the requests.

**Comment by emphazer** [comment]
hello, same problem here. im behind a firewall and cant access whois port :43 
is it possible to skip the whois test?

**Comment by emphazer** [comment]
okay, found it thanks!

-Dmaven.test.failure.ignore=true or -DtestFailureIgnore=true - will ignore any failures occurred during test execution

-Dmaven.test.error.ignore=true ( deprecated ) - will ignore any errors occurred during test execution

-DskipTests - would compile the test classes but skip test execution entirely

-Dmaven.test.skip=true - would not even compile the tests
