### ISSUE TITLE
Parallel Deployment on Tomcat 7 still fails

### ISSUE THREAD

**Issue by mengdq** [psi-probe/psi-probe#545]
When we use it to do Parallel Deployment on Tomcat 7,
something like ROOT##001.war,
it still fails.

**Comment by MALfunction84** [comment]
Can you describe the failure? Can you provide more detailed steps to reproduce?

**Comment by mengdq** [comment]
Yes, It is occurring in PSI Probe 2.4.0.
It is easy to reproduce the problem.
Just make a war file, and named it to ROOT##1.war,
When you deploy it,
it fails.
![evidence1](https://cloud.githubusercontent.com/assets/13994707/9623184/3c4a0064-5178-11e5-9463-135c732e6427.PNG)
![evidence2](https://cloud.githubusercontent.com/assets/13994707/9623190/4342d486-5178-11e5-97f5-0ec9d1f92e6b.PNG)
![evidence3](https://cloud.githubusercontent.com/assets/13994707/9623193/48f0bc54-5178-11e5-8176-fdacafb71f22.PNG)
![evidence4](https://cloud.githubusercontent.com/assets/13994707/9623197/4d4ff0d0-5178-11e5-888d-903c83e00063.PNG)

**Comment by MALfunction84** [comment]
Sorry about that. Apparently #275 was not fixed after all.

**Comment by MALfunction84** [comment]
What version of Tomcat are you running?

**Comment by mengdq** [comment]
Tomca 7

**Comment by mengdq** [comment]
Could you tell me when you can fix this bug? I am waiting for you.

**Comment by hazendaz** [comment]
@mengdq This bug has been fixed on current master as of today.  Sorry for such a long delay.
