### ISSUE TITLE
Logback access logs not shown

### ISSUE THREAD

**Issue by hazendaz** [psi-probe/psi-probe#552]
While logback in general shows up the access logs if configured do not.  Add support for this.

**Comment by MALfunction84** [comment]
Is this different from #392?

**Comment by hazendaz** [comment]
Similar but different.  There are still a number of logs that don't show.  This is more closely related to logback.  I'll look more into this.  I just wanted to note it before I forget about it.


Sent by Outlook for Android





On Mon, Sep 28, 2015 at 7:02 PM -0700, "Mark Lewis" <notifications@github.com> wrote:
Is this different from #392?

---

**Comment by MALfunction84** [comment]
Fair enough. A configuration that demonstrates the problem would be appreciated.

**Comment by hazendaz** [comment]
missing log is called 'localhost-access.log'.  It's setup by using logback-access jars in tomcat/lib to get the access logs.  I'll look at taking this one on when I get some time.

**Comment by MALfunction84** [comment]
At the very least, this is probably dependent on #392. I'd like to get the native access logs before we get to the special case.

**Comment by hazendaz** [comment]
Essentially any log can be resolved by adding to this....note added the missing log and it worked.

```xml
	<bean id="logResolver" class="psiprobe.beans.LogResolverBean">
		<property name="containerWrapper" ref="containerWrapper"/>
		<property name="stdoutFiles">
			<list>
				<value>catalina.out</value>
				<value>wrapper.log</value>
				<value>stdout.log</value>
				<value>stdout.err</value>
				<value>localhost-access.log</value>
			</list>
		</property>
	</bean>
```

**Comment by hazendaz** [comment]
closing as tracking in one ticket now.  Stdout was added for this one but direct logic still not there yet.  Old work I have done was close but not close enough.  Will look at that separately.
