### ISSUE TITLE
deployXML="false" causes psi-probe NPE error

### ISSUE THREAD

**Issue by sschrisman** [psi-probe/psi-probe#554]
Setting deployXML="false" causes psi-probe to generate a NullPointerException.  

Cannot run psi-probe in same Tomcat instance as other applications because of this error.

**Comment by MALfunction84** [comment]
Can you provide a stack trace?

**Comment by hazendaz** [comment]
@sschrisman Can you provide stack trace for the issue?

**Comment by hazendaz** [comment]
@sschrisman There is no bug with psi probe here.  Setting deployXML to false results properly in tomcat throwing error that it cannot startup psi probe as documented in tomcat.  Then taking the context and adding to the xmlBase location of tomcat renamed as probe.xml will then properly load probe without issue.  Other apps all show up as well.  Therefore closing the issue.
