### ISSUE TITLE
Add JDeps 3 to Maven Build

### ISSUE THREAD

**Issue by jander99** [psi-probe/psi-probe#562]
http://www.infoq.com/news/2015/11/maven-jdeps-plugin-released

I can do this tonight and create a PR, should just be a change to pom.xml.  If it finds anything, I will create a new issue for resolution. 

This issue is simply opened to tie to the PR.

**Comment by jander99** [comment]
Closing issue.  No errors were found and we can discuss separately whether we want to add this as a test step and fail the build otherwise.  I don't think we need to as the codebase is fairly small to begin with.

**Comment by MALfunction84** [comment]
I don't have any problem with including this. Duplicates #457 anyway, right?
