### ISSUE TITLE
Uptime should be JVM (server) uptime instead of Probe context uptime

### ISSUE THREAD

**Issue by ranophoenix** [psi-probe/psi-probe#564]
Hi,

I have one server that uptime via ServletListener(current implementation) is:

**UP for 0 days 9 hours 30 minutes**

Using JMX (more reliable):

**RUNNING for 12 days 1 hours and 21 minutes**

**Comment by MALfunction84** [comment]
Well, there's the uptime of the machine, and there's the uptime of Tomcat itself. The current implementation shows the uptime of Tomcat. I suppose we could have both. I'd be inclined to put the machine's uptime on the System tab.

**Comment by ranophoenix** [comment]
Mark,

There are 3 uptimes:

1) Operating System;
2) JVM (my patch);
3) Webapp (in this case, the probe app) [current implementation]

The actual implementation is based on a ServletContextListener which is
called by application. I think that is more important to know the Tomcat
uptime, which is closely related with JVM uptime, than to know when probe
app was deployed, for instance.
Em 11/01/2016 02:09, "Mark Lewis" <notifications@github.com> escreveu:

**Comment by MALfunction84** [comment]
Quite true. I agree that JVM uptime is better.

Can you create a PR from your patch? It looks like you'll need to remove the reference to UptimeListener from `web/src/main/webapp/WEB-INF/web.xml`.
