### ISSUE TITLE
Issue when stopping/starting an application with Probe 2.4 under Tomcat 8 

### ISSUE THREAD

**Issue by aurelienpernoud** [psi-probe/psi-probe#573]
With tomcat 8 (8.0.24, but I doubt it comes from the subversion ?), and Probe 2.4 official release, you can't stop/start an application by clicking on the green or red status in the application list.

It generates an error on logs
ERROR com.googlecode.psiprobe.controllers.apps.AjaxToggleContextController  - java.lang.NoSuchMethodError: org.apache.catalina.Context.getAvailable()Z

You can still stop/start it by clicking on the application and then using the stop/start button on top though as a workaround, but it was nice to be able to do it from the main screen.

It works fine with Tomcat 7 FYI.

**Comment by aurelienpernoud** [comment]
The bug was apparently raised as a minor bug here but probably missed :)

https://github.com/psi-probe/psi-probe/issues/394#issuecomment-81738506

**Comment by hazendaz** [comment]
@aurelienpernoud Can you try the latest build of 3.0.0 and let me know if that works?  I will make it available in our releases section shortly.

**Comment by aurelienpernoud** [comment]
Hello,
Still not :ERROR com.googlecode.psiprobe.controllers.apps.AjaxToggleContextController  - java.lang.NoSuchMethodError: org.apache.catalina.Context.getAvailable()Z

**Comment by aurelienpernoud** [comment]
I used Version 3.0.0-SNAPSHOT you made FYI

**Comment by hazendaz** [comment]
Thanks for reverifying.


Sent from Outlook Mobile






On Mon, Jan 25, 2016 at 3:02 AM -0800, "aurelienpernoud" <notifications@github.com> wrote:





I used Version 3.0.0-SNAPSHOT you made FYI

---

**Comment by hazendaz** [comment]
@aurelienpernoud a fix is coming on this.  If you can be on the lookout for this issue being closed.  Once it is closed, I'm going to submit a new snapshot release to releases for you to give it another shot.  Should be within next day or so.

**Comment by aurelienpernoud** [comment]
Yep I saw the commit, no pb I can retest whenever a snapshot is ready !
