### ISSUE TITLE
NPE right after login when I tried to access tomcat logs

### ISSUE THREAD

**Issue by fieder** [psi-probe/psi-probe#574]
There was an error

Application encountered an unexpected error. We will greatly appreciate it if you share the information below with us. Sharing this information through our issue tracker or our discussion board will help us find and correct this problem as soon as possible!

java.lang.NullPointerException at com.googlecode.psiprobe.beans.LogResolverBean.interrogateApplicationClassLoaders(LogResolverBean.java:204) at com.googlecode.psiprobe.beans.LogResolverBean.getAllLogDestinations(LogResolverBean.java:143) at com.googlecode.psiprobe.beans.LogResolverBean.getLogDestinations(LogResolverBean.java:68) at com.googlecode.psiprobe.controllers.logs.ListLogsController.handleRequestInternal(ListLogsController.java:45) at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:153) at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:48) at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:875) at com.googlecode.psiprobe.ProbeServlet.doDispatch(ProbeServlet.java:54) at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:807) at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:571) at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:501) at javax.servlet.http.HttpServlet.service(HttpServlet.java:620) at javax.servlet.http.HttpServlet.service(HttpServlet.java:727) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:129) at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:77) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:610) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) at com.googlecode.psiprobe.Tomcat70AgentValve.invoke(Tomcat70AgentValve.java:38) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102) at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408) at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040) at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607) at org.apache.tomcat.util.net.AprEndpoint$SocketWithOptionsProcessor.run(AprEndpoint.java:2379) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.lang.Thread.run(Thread.java:745)

**Comment by MALfunction84** [comment]
What version of PSI Probe?

**Comment by fieder** [comment]
2.3.3

**Comment by hazendaz** [comment]
@fieder can you possibly upgrade to 2.4.0 and let me know if the issue still exists?

**Comment by fieder** [comment]
Ok, I'll give it a go. Thank you.

On Sat, Jan 16, 2016 at 7:16 PM, Jeremy Landis <notifications@github.com>
wrote:

> @fieder <https://github.com/fieder> can you possibly upgrade to 2.4.0 and
> let me know if the issue still exists?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/psi-probe/psi-probe/issues/574#issuecomment-172247479>
> .
>



-- 
*Felipe IEDER*
*CEO, Co-founder *

http://druidalabs.com
+44 2078 132 468
UK Registered Company No. 07023467
70 B Saltoun Rd, SW2 1ER, London.

**Comment by hazendaz** [comment]
@fieder any update on trying 2.4.0?

**Comment by fieder** [comment]
Hi - sorry delayed response ; a bit snowed under with our production systems. I managed to get rid of the error simply by stopping tomcat, deleting all logs and starting tomcat back again.  As soon as I get a grip on our own release I'll upgrade probe as you suggested.

**Comment by hazendaz** [comment]
@fieder we have a newer version now available for testing.  You can grab it [here](https://github.com/psi-probe/psi-probe/releases/download/3.0.0.M2/probe.war).

This version has one glitch if you use it as http instead of https.  In the web.xml, remove secure cookie attribute to test with http.  If using https, it's otherwise good.

Please let us know if this issue is still present so we know how to proceed.  No rush though.  

Thanks...

**Comment by MALfunction84** [comment]
I'd be interested to know whether it's fixed in 2.4.0. Might be something we want to cherrypick for a potential 2.4.1.

**Comment by hazendaz** [comment]
Closing issue as user never got back and this hasn't since been reported as a problem.
