### ISSUE TITLE
Resolve issue with Oracle dependencies encumbered by OTN license

### ISSUE THREAD

**Issue by MALfunction84** [psi-probe/psi-probe#584]
We currently rely on code.lds.org to host Oracle dependencies as Maven artifacts. IANAL, but I think the OTN forbids this. If they ever take the dependencies down, our project will fail to build unless people manually install the dependencies (which is how it used to work, years ago). This will definitely break Travis, as we can't manually install dependencies at all.

There was some discussion in #468 on this as well. Not sure how to fix it, but just acknowledging that it's an issue.

**Comment by hazendaz** [comment]
Resolved via #1046 and also fixing #1033 

Issue was encountered as code.lds.org had upgraded nexus and oracle libraries went away.  New solution in place isolates bulk of psi-probe essentially forever and not only that the license is agreed to with Oracle and established against my account and then downloaded directly from oracle's nexus repo via authentication.  That later part prevented it from effectively staying on this repo as travis ci won't share credentials even encrypted to forks / pull requests and as such builds would fail for community.  Now they will always work and there is no concern of things suddenly breaking here.
