### ISSUE TITLE
Add secure cookie attributes

### ISSUE THREAD

**Issue by hazendaz** [psi-probe/psi-probe#594]
It's generally accepted that web.xml should define timeout at 15 minutes.  While it inherites from tomcat, which is set to 30 by default, static scanners will otherwise report not setting this.

It's further generally acceptable to set secure cookie attribute so JSessionID is marked secure.  Even if tomcat is not https, it will secure the cookie.

**Comment by hazendaz** [comment]
Secure cookie causes a problem with session handling in http usage.  Unsure what the root cause is at the moment but assuming spring related.  Tomcat otherwise will handle secure cookie even on http.  Therefore re-opening this until it can be addressed to fit both http and https needs.

**Comment by MALfunction84** [comment]
Cool. Can you cite the reverting revision here when it's done?

**Comment by hazendaz** [comment]
secure and httpOnly added to the memory cookie as of #961

**Comment by hazendaz** [comment]
This was recently addressed, closing.
