### ISSUE TITLE
Replace Commons Logging usage with Slf4j and review logging output

### ISSUE THREAD

**Issue by hazendaz** [psi-probe/psi-probe#613]
As of #612, we are officially using logback logging rather than legacy log4j 1.  Now we need to address switching over our own internal logging to use slf4j so that we are not wrapped through jcl-to-slf4j needlessly in order to improve performance.  Additionally, this should be an opportunately to review logging configuration in case any adjustments are necessary.  The basic configuration as it stands is similar to that of tomcat logging at this time.

**Comment by jander99** [comment]
Let's make sure to test against Wildfly, TomEE, tcServer. Everyone tends to
do logging slightly differently.

**Comment by hazendaz** [comment]
Wildfly uses undertow now so I assume it doesn't work with psi probe.  Does it?  I have a wildfly setup so I can drop it in and see what happens.  I suspect it won't work though.

I'll get a TomEE setup and give that a shot in a few.  I don't have an account over at pivotal so getting tcServer will take a bit more time.  If you happen to have tcServer, can you give that a go?

We probably should run tests on older containers as well.  I've been using tomcat8 exclusively but know it will otherwise work in tomcat series.

Only real concern would be if someone wires up their tomcat* instance to use slf4j / logback directly in it.  However, I had smoke tested that already but will check it again to be sure in a little bit.  I'll follow-up here once various pieces have been vetted.
