### ISSUE TITLE
Remove JMXRI library - it's included in JRE since JDK 5.0

### ISSUE THREAD

**Issue by hazendaz** [psi-probe/psi-probe#615]
Currently, there are two possible profiles to run with the build.  The first includes JMX as a default.  The second does not for JBoss by marking it provided.  However, both are legacy needs.  Per Oracle, the JRE has included JMXRI since JRE 5.0.  So it's been there for a very long time.

See [here](http://www.oracle.com/technetwork/articles/java/javamanagement-140525.html)

Anyway, removal and testing proves it was unnecessary.  Further, It presented an error in Eclipse for JBoss Resolver on this line of code.

```Java
for (MBeanServer server : MBeanServerFactory.findMBeanServer(null)) {
```

Testing criteria does not require verification in jboss as it was otherwise marked provided.  This affected non jboss only and development thus limiting our ability to use more jmx.

**Comment by MALfunction84** [comment]
Makes sense.
