### ISSUE TITLE
Drop support of tomcat 7.0.15 and lower

### ISSUE THREAD

**Issue by hazendaz** [psi-probe/psi-probe#616]
Per code snippet

```Java
      /*
       * The above constructor's signature changed in Tomcat 7.0.16:
       * http://svn.apache.org/viewvc?view=revision&revision=1124719
       * 
       * If we reach this point, we are running on a prior version of Tomcat 7 and must use
       * reflection to create this object.
       */
      try {
        jcctx =
            ConstructorUtils.invokeConstructor(JspCompilationContext.class,
                new Object[] {name, false, opt, sctx, null, jrctx}, new Class[] {String.class,
                    Boolean.TYPE, Options.class, ServletContext.class, JspServletWrapper.class,
                    JspRuntimeContext.class});
        return jcctx;
```
We should not support known vulnerable versions of tomcat.  Anyone using such versions doesn't care about security and therefore can use psi probe 2.4.0.  Solutions like these are extremely hacky.  If we need to do things like this we should release parallel supported version and not mix legacy support and new support as a general rule of thumb.  At this point though, 7.0.16 was released almost 4 years ago so supporting it makes little to no sense.

**Comment by MALfunction84** [comment]
Agreed.
