### ISSUE TITLE
Do not delegate classloading toTomEE for slf4j/logback bindings

### ISSUE THREAD

**Issue by hazendaz** [psi-probe/psi-probe#625]
TomEE will likely run into issue with presense of logback.  This has been untested at this time.  From looking around the net, an old nabble from a few years ago discusses this and how to get around issue.  Context.xml will need the following.

context.xml

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<Context >
    <Loader delegate="false" />
</Context> 
```

**Comment by diogosantana** [comment]
@hazendaz , is this complete? I can only see `<?xml version="1.0" encoding="UTF-8"?>` as the context.xml content.

**Comment by hazendaz** [comment]
fixed.  thanks.

**Comment by jander99** [comment]
markdown eat it?

**Comment by hazendaz** [comment]
You got it.  They should make markdown a little smarter.  Xml is easy to see :)

**Comment by MALfunction84** [comment]
Did we confirm this is reproducible? Can you link to the nabble?

**Comment by hazendaz** [comment]
This has not been confirmed yet.  The link didn't have any real information beyond mentioning that.  So I grabbed that for reference until we can confirm.

**Comment by hazendaz** [comment]
Since this does not adversly affect anything, I'm adding it.  With our download counts significantly rising, I hope we will start getting more feedback and low issues might help appeal to users to submit issues ;)
