### ISSUE TITLE
Replace spring security path-type with request-matcher

### ISSUE THREAD

**Issue by hazendaz** [psi-probe/psi-probe#634]
Per warning, 22:39:16.505 WARN  {localhost-startStop-1} [o.s.security.config.http.MatcherType] 'path-type' is deprecated. Please use 'request-matcher' instead.

Solution is a simple change as indicated with no further changes.

**Comment by MALfunction84** [comment]
Is this part of the Spring migration?

**Comment by hazendaz** [comment]
It will be I'm sure but I haven't check spring security 4 to see if that legacy item is gone.  I just caught the warning in the logs and fixed it to make the warning go away.
