### ISSUE TITLE
Cluster traffic graphs sometimes do not display

### ISSUE THREAD

**Issue by GoogleCodeExporter** [psi-probe/psi-probe#64]
```
What steps will reproduce the problem?
1. Set up a Tomcat cluster with two instances (may still occur with more
than two instances).
2. In Probe, click the Cluster tab.

What is the expected output?
A graph of cluster traffic.

What do you see instead?
Occasionally, the graph will not load.

Please provide any additional information below.
Attempting to access the image URL directly (which is really a controller
for JFreeChart) displays a stack trace (attached).
```

Original issue reported on code.google.com by `MALfunct...@gmail.com` on 11 Jan 2010 at 11:41

**Comment by sepphuber** [comment]
Hi,

on Debian 9 with openjdk8 (as a debian package) the graphics did not display even though "-Djava.awt.headless=true" was already set.

So googling around for hours brought me to another working solution:

> Commenting out the `assistive_technologies` line in `/etc/java-8-openjdk/accessibility.properties` solved it.

Taken from here:
https://issues.jenkins-ci.org/browse/JENKINS-39636
