### ISSUE TITLE
FollowController always open log files with default system charset encoding

### ISSUE THREAD

**Issue by diogosantana** [psi-probe/psi-probe#644]
FollowController always open log files with default system charset encoding even if the respective logger uses a different one.

For example, if the system default charset encoding is ISO-8859-1 and a deployed app has logback configured to UTF-8, psi-probe will not show the accented characters correctly.

**Comment by hazendaz** [comment]
Good catch!  Please open issue to cover other loggers.  Thanks.


Sent from Outlook Mobile






On Thu, Feb 4, 2016 at 5:29 AM -0800, "diogosantana" <notifications@github.com> wrote:





FollowController always open log files with default system charset encoding even if the respective logger uses a different one

For example, if the system default charset encoding is ISO-8859-1 and a deployed app has logback configured to UTF-8, psi-probe will not show the accented characters correctly

---
Reply to this email directly or view it on GitHub:
https://github.com/psi-probe/psi-probe/issues/644

**Comment by MALfunction84** [comment]
I think it makes sense to use this issue for all loggers. Reopening.

Remaining loggers:
* catalina
* commons
* jdk
* log4j
* slf4jlogback

**Comment by hazendaz** [comment]
@diogosantana Any change you might be able to look at getting this for all the other loggers?

**Comment by hazendaz** [comment]
I don't think other loggers will be as easy since we use logback.  All others will need reflective way to accomplish this best I can tell.

**Comment by diogosantana** [comment]
I wish I could, but at the moment I just don't have the time due to work. Anyway, my main knowledge about log API's is logback.

Maybe psi-probe could only have this as partially supported. When anyone feels they want it to other log API, they will have to contribute?

**Comment by hazendaz** [comment]
think most modern logs were covered, I plan to drop nearly all junk loggers at some point soon anyways.  Days of supporting decades old dead products is coming to an end ;)
