### ISSUE TITLE
Data Sources Not Displayed Correctly on Tomcat 8 (3.0.0 Milestone 3)

### ISSUE THREAD

**Issue by e1d** [psi-probe/psi-probe#689]
In Tomcat 8, probe version 3.0.0 Milestone 3, the 'M' values (maximum number of connections in the pool) are wrong. Everything is 8.
It is displaying correct value in Tomcat 7.

Here is the screen shot:
![data sources](https://cloud.githubusercontent.com/assets/10696061/13562332/631f7d3a-e472-11e5-9c86-27fdecec93ab.jpg)

**Comment by e1d** [comment]
Any update about this? I can't figure out why it is different in Tomcat 8.

**Comment by hazendaz** [comment]
I haven't taken a look at this one yet.  If you can try to fix it and submit a pull request.  I can hold off releasing next set after this is resolved.


Sent from Outlook Mobile






On Mon, Mar 7, 2016 at 6:33 PM -0800, "e1d" <notifications@github.com> wrote:





Any update about this? I can't figure out why it is different in Tomcat 8.

---

**Comment by hazendaz** [comment]
@e1d Can you check your configuration and make sure you are using maxTotal on your tomcat 8 setup?  The value changed from maxActive to maxTotal in tomcat 8.  Under the hood in tomcat, tomcat defaults to 8 for maxTotal if it is not provided.  That leads me to think possibly you used the same configuration from tomcat 7 for tomcat 8 and thus the issue you are experiencing.  If that is the case, thing this isn't an issue and can be closed.

**Comment by hazendaz** [comment]
reference -> https://tomcat.apache.org/tomcat-8.0-doc/jndi-datasource-examples-howto.html

**Comment by e1d** [comment]
Oh my.. It solved the issue.
I wonder why are they changing that parameter.
BTW, thank @hazendaz !

**Comment by hazendaz** [comment]
No problem.  Internally tomcat 8 uses dbcp2.  So the real change was in that library.  I assume they did it for better clarity.


Sent from Outlook Mobile






On Tue, Mar 8, 2016 at 9:41 PM -0800, "e1d" <notifications@github.com> wrote:





Oh my.. It solved the issue.
I wonder why are they changing that parameter.
BTW, thank @hazendaz !

---

**Comment by e1d** [comment]
I see, BTW, does probe data sources show other data sources other than JDBC?
My friend is using JPA, and it is not displayed on probe data sources.

**Comment by hazendaz** [comment]
@e1d All JPA I've seen uses jdbc under the hood.  I'm not sure how we would indicate JPA pieces given that is inside applications rather than the container itself.  Maybe this will help in understanding the differences [here](http://stackoverflow.com/questions/11881548/jpa-or-jdbc-how-are-they-different)
