### ISSUE TITLE
Tomcat 8.5 support

### ISSUE THREAD

**Issue by hazendaz** [psi-probe/psi-probe#703]
Tomcat team has now backported all but java 8 and servlet 4.0 to what is now termed tomcat 8.5.x.  This is now under release voting.  I built out basic support for this and will merge in once the official release drops.  Details are still fast evolving.  More official statements will be ariving around March 29 when Tomcat team makes official announcements.

[here](https://ci.apache.org/projects/tomcat/tomcat85/docs/changelog.html)

**Comment by hazendaz** [comment]
Added support in #715

**Comment by b0c1** [comment]
I got "No container found for your server: Apache Tomcat/8.5.5" message

**Comment by hazendaz** [comment]
This is fixed on the lastest master and has been for a little while.  It was an issue with the milestone release I had pushed out as I missed a setting.  Can you check against master and let me know if this is still a problem?

**Comment by diegolucasb** [comment]
I was having the same "No container found for your server: Apache Tomcat/8.5.5" problem. After checking out master repo and package (man) new war file, it worked fine!

**Comment by hazendaz** [comment]
Glad to hear it!  There have been quite a number of changes under the hood on current master.  Please do provide any feedback of any issues encountered.
