### ISSUE TITLE
java.lang.NoClassDefFoundError: org/slf4j/event/LoggingEvent

### ISSUE THREAD

**Issue by shentley** [psi-probe/psi-probe#719]
Cloned the git repo and built the war using maven. There were no errors. The stack trace below is from the "Logs" tab, every other tab seems to work fine. I tried replacing the slf4j-api jar with a newer one but it didn't resolve the problem.

java version "1.7.0_99"
OpenJDK Runtime Environment (amzn-2.6.5.0.66.amzn1-x86_64 u99-b00)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)

Running the WAR on Apache Tomcat 8.0.20.

----

java.lang.NoClassDefFoundError: org/slf4j/event/LoggingEvent at java.lang.Class.getDeclaredMethods0(Native Method) at java.lang.Class.privateGetDeclaredMethods(Class.java:2625) at java.lang.Class.getMethod0(Class.java:2866) at java.lang.Class.getMethod(Class.java:1676) at org.apache.commons.beanutils.MethodUtils.getMatchingAccessibleMethod(MethodUtils.java:957) at org.apache.commons.beanutils.MethodUtils.invokeMethod(MethodUtils.java:270) at org.apache.commons.beanutils.MethodUtils.invokeMethod(MethodUtils.java:222) at psiprobe.tools.logging.logback.LogbackLoggerAccessor.getAppenders(LogbackLoggerAccessor.java:38) at psiprobe.tools.logging.logback.LogbackFactoryAccessor.getAppenders(LogbackFactoryAccessor.java:123) at psiprobe.beans.LogResolverBean.interrogateClassLoader(LogResolverBean.java:343) at psiprobe.beans.LogResolverBean.interrogateContext(LogResolverBean.java:295) at psiprobe.beans.LogResolverBean.getAllLogDestinations(LogResolverBean.java:191) at psiprobe.beans.LogResolverBean.getLogDestinations(LogResolverBean.java:102) at psiprobe.controllers.logs.ListLogsController.handleRequestInternal(ListLogsController.java:81) at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:147) at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:50) at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959) at psiprobe.ProbeServlet.doDispatch(ProbeServlet.java:86) at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893) at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:968) at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:859) at javax.servlet.http.HttpServlet.service(HttpServlet.java:618) at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:844) at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:316) at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126) at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90) at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114) at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:120) at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) at org.springframework.security.web.authentication.preauth.AbstractPreAuthenticatedProcessingFilter.doFilter(AbstractPreAuthenticatedProcessingFilter.java:116) at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:91) at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:213) at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:176) at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346) at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:129) at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:77) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:613) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) at psiprobe.Tomcat80AgentValve.invoke(Tomcat80AgentValve.java:45) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516) at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086) at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659) at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.lang.Thread.run(Thread.java:745) Caused by: java.lang.ClassNotFoundException: org.slf4j.event.LoggingEvent at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1305) at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1157) ... 69 more

**Comment by hazendaz** [comment]
@shentley You mention that you changed out slf4j-api with newer one.  The current master is already on the latest available so that sort of indicates you most likely have slf4j floating around possibly in tomcat/lib directory.  If not that, you probably have another jar in tomcat/lib that contains slf4j api.  Can you confirm that?

**Comment by shentley** [comment]
There is no slf4j in my tomcat lib folder, unless I'm missing something, here it is:

annotations-api.jar       jasper.jar          tomcat-jdbc.jar
catalina-ant.jar          jsp-api.jar         tomcat-jni.jar
catalina-ha.jar           servlet-api.jar     tomcat-spdy.jar
catalina.jar              tomcat-api.jar      tomcat-util.jar
catalina-storeconfig.jar  tomcat-coyote.jar   tomcat-util-scan.jar
catalina-tribes.jar       tomcat-dbcp.jar     tomcat-websocket.jar
ecj-4.4.1.jar             tomcat-i18n-es.jar  websocket-api.jar
el-api.jar                tomcat-i18n-fr.jar
jasper-el.jar             tomcat-i18n-ja.jar

You are right about the version though, I double checked and somehow I confused myself into thinking slf4j-api-1.7.5.jar was newer than slf4j-api-1.7.21.jar. Oops. Regardless I put the original jar back in there and it still fails.

**Comment by shentley** [comment]
I can't really explain what happened, but I upgraded slf4j in a different project and now it works. I don't know why a jar file in a different project matters, but the exception is now gone. 

Also, I upgraded to java 1.8 and rebuilt the war, then upgraded to Tomcat 8.0.33. Neither of those two changes made a difference.

**Comment by hazendaz** [comment]
I wonder if the real cause was not psi probe but rather your other project.  If you run your other project by itself with the slf4j-api you had previously does it work?  It might just be that psi-probe is listed in the stack trace...or there might be something else to it that we need to look at.  We do a lot of reflection under the hood so maybe there was a change in slf4j that is causing this when our library is in play.  If you can verify that I can take another look at this.  Thanks.

**Comment by shentley** [comment]
The other project had no errors.  This trace was not taken from the logs, it was displayed on the screen in the app on the Log tab. Maybe you can try to duplicate by deploying another project with an old slf4j to the same tomcat server.

**Comment by hazendaz** [comment]
Ah...ok.  that does indicate we are not supporting older slf4j logger.  I'll look more into the issue.  If you were able to upgrade even better.  Just make sure to use slf4j 1.7.21 as slf4j had leaks in the few prior versions.


On the logger tab we do a lot of teflection to figure out logs.  We try our best to support many versions within your own code so i think we can fix the issue for others needs.


Thanks for reporting and following up.


Sent from Outlook Mobile






On Wed, Apr 20, 2016 at 6:24 AM -0700, "shentley" <notifications@github.com> wrote:





The other project had no errors.  This trace was not taken from the logs, it was displayed on the screen in the app on the Log tab. Maybe you can try to duplicate by deploying another project with an old slf4j to the same tomcat server.

> On Apr 20, 2016, at 8:32 AM, Jeremy Landis <notifications@github.com> wrote:
>
> I wonder if the real cause was not psi probe but rather your other project. If you run your other project by itself with the slf4j-api you had previously does it work? It might just be that psi-probe is listed in the stack trace...or there might be something else to it that we need to look at. We do a lot of reflection under the hood so maybe there was a change in slf4j that is causing this when our library is in play. If you can verify that I can take another look at this. Thanks.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
>


---

**Comment by hazendaz** [comment]
@shentley Can you confirm what version of logback you had in your original setup that had the issue?  I did open up a separate issue on this #720 after review and finding notes from slf4j team on this.  I'm not exactly sure at the moment if this is really psi-probe issue or if you potentially had a mismatch in slf4j/logback usage on your own.  Per slf4j notes, it would be ok to have logback 1.1.4+ and earlier slf4j such as 1.7.5 that would work but in how psi-probe accesses that would be an issue as you described.  Please let me know.  Thanks in advance!

**Comment by shentley** [comment]
This was my original configuration. 

 <logback.version>1.0.13</logback.version> <slf4j.version>1.7.5</slf4j.version>

**Comment by hazendaz** [comment]
Thanks @shentley.  I appreciate it!
