### ISSUE TITLE
Updates to Japanese translation

### ISSUE THREAD

**Issue by GoogleCodeExporter** [psi-probe/psi-probe#73]
```
Which feature would you like to see enhanced?
Japanese translation.

Please describe the enhancement in detail.
Any commented-out property in messages_ja.properties needs to be translated
into Japanese.
```

Original issue reported on code.google.com by `MALfunct...@gmail.com` on 15 Jan 2010 at 9:37

**Comment by hazendaz** [comment]
closing as really old and ticket not necessary for language updates, if anyone needs they can send a PR.  Most were likely long addressed.
