### ISSUE TITLE
Problem with css (fonts/letters too big)

### ISSUE THREAD

**Issue by tachtler** [psi-probe/psi-probe#731]
Hi,

after upgrade to **Version 3.0.0-SNAPSHOT** the fonts are a little bit too big. The problem grows up for example, when you change the language, for example german.

![psi-probe-3 0 0-snapshot-fonts](https://cloud.githubusercontent.com/assets/11161944/15668824/8497441e-271d-11e6-8f84-0f8aafd82974.png)

The **css from Version 2.4.0** or smaller was better.

Thank you,
Klaus.

**Comment by hazendaz** [comment]
@tachtler I fully agree with you.  Another user wanted that change and I cannot at this point still wrap my head around the idea that this is better.  I will look into reverting that change or coming up with something in the middle.  If you happen to have any spare time and can make it a bit better, please feel free to file a pull request.  I don't have a lot of time these days so I cannot address this currently.

As a side note, in the next few days I will have a lot of others looking over the look and feel.  So if everyone agrees just how bad this looks, this might get pushed up in priority.  I've got a need to roll this to production pretty quickly so I will do what I can...

**Comment by tachtler** [comment]
Hi Jeremy,

thank you for your agreement. Maybe I can copy the css from a older installation and compare it with the latest one...

We will see...

Thank you!
Klaus.

**Comment by tachtler** [comment]
Hi Jeremy,

update the css to a better view for different languages, as used in 2.4.x versions. See my pull request #750, #751 and updated the messages_de.properties for the German language file too #752.

Thank you!
Klaus

**Comment by hazendaz** [comment]
Closing issue as this was merged into master.
