### ISSUE TITLE
Updates to Russian translation

### ISSUE THREAD

**Issue by GoogleCodeExporter** [psi-probe/psi-probe#74]
```
Which feature would you like to see enhanced?
Russian translation.

Please describe the enhancement in detail.
Any commented-out property in messages_ru.properties needs to be translated
into Russian.
```

Original issue reported on code.google.com by `MALfunct...@gmail.com` on 15 Jan 2010 at 9:39

**Comment by hazendaz** [comment]
closing as any language updates were likely added long time ago and certainly no issue is needed as anyone can send a PR if needed
