### ISSUE TITLE
Probe cannot detect/trace jdbc connection for spring application

### ISSUE THREAD

**Issue by e1d** [psi-probe/psi-probe#743]
It seems like Probe cannot detect a jdbc connection/pool for a Spring based application.

The connection properties/parameters for spring application is located in the application.properties file.

Please add the functionality.

**Comment by aurelienpernoud** [comment]
It makes sense, your spring application should (must) use the datasource defined at server level, not inside each application

**Comment by hazendaz** [comment]
This is a duplicate of #712, closing
