### ISSUE TITLE
version 3.0.0 deploy empty page

### ISSUE THREAD

**Issue by robertogermano** [psi-probe/psi-probe#748]
Hi everybody.
Using Probe 3.0.0 to deploy apps, a blank page has been returned and into the probe log file there is this warning:   
WARN  {http-apr-9080-exec-49} [o.s.web.servlet.PageNotFound] Request method 'POST' not supported
There are not other error. 

Any idea?

Thanks in advance

**Comment by hazendaz** [comment]
@robertogermano I have been able to replicate this issue but do not know what is causing it yet.  I will do some further analysis on a prior version to try to pin down when this issue got introduced.  If you can, try one of the milestone releases and let me know if those are also affected.

**Comment by hazendaz** [comment]
@robertogermano.  This issue was resolved by dropping back to spring 4.2.6 temporarily.  Tonight I pushed some changes which need reviewed by other psi probe members but you certainly can check out pull request #766 to confirm it's working as you expect.

**Comment by hazendaz** [comment]
Closing as duplicate issue and more information available on #788
