### ISSUE TITLE
HTTP Status 405 - Request method 'POST' not supported...

### ISSUE THREAD

**Issue by tachtler** [psi-probe/psi-probe#754]
Hi,

Version: 3.0.0.-SNAPSHOT (latest).

While opening the tab **System** and click on the right menu **Memory utilization**, following error occurs:
```
HTTP Status 405 - Request method 'POST' not supported

type Status report

message Request method 'POST' not supported

description The specified HTTP method is not allowed for the requested resource.
Apache Tomcat/7.0.54
```
See screen shot below as well:

![psi-probe-snapshot-3 0 0](https://cloud.githubusercontent.com/assets/11161944/16943931/93dd7d88-4d9e-11e6-9d09-e1d7542be5ee.png)

Thank you for your help!
Klaus.

**Comment by hazendaz** [comment]
Can you check to see if that works on last 3.0.0 milestone?

Get Outlook for Android<https://aka.ms/ghei36>



On Tue, Jul 19, 2016 at 4:52 AM -0400, "Klaus Tachtler" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

Version: 3.0.0.-SNAPSHOT (latest).

While opening the tab System and click on the right menu Memory utilization, following error occurs:

HTTP Status 405 - Request method 'POST' not supported

type Status report

message Request method 'POST' not supported

description The specified HTTP method is not allowed for the requested resource.
Apache Tomcat/7.0.54


See screen shot below as well:

[psi-probe-snapshot-3 0 0]<https://cloud.githubusercontent.com/assets/11161944/16943931/93dd7d88-4d9e-11e6-9d09-e1d7542be5ee.png>

Thank you for your help!
Klaus.

-

**Comment by tachtler** [comment]
Hi Jeremy,

i will build it now...

Thank you!
Klaus.

**Comment by tachtler** [comment]
Hi Jeremy,

I'm not sure if I did everything fine with github. How can I get the 3.0.0.M3 Version - it's the latest, so I can downlaod it with `git clone https://github.com/psi-probe/psi-probe`

After doing that, I build the succesful the Version: 3.0.0.-SNAPSHOT.

The error already occurs.

Thank you!
Klaus.

**Comment by hazendaz** [comment]
On releases tab on github it is packaged for download and immediate use.  If that one works it will help isolate where to look.

Get Outlook for Android<https://aka.ms/ghei36>



On Tue, Jul 19, 2016 at 9:34 AM -0400, "Klaus Tachtler" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Jeremy,

I'm not sure if I did everything fine with github. How can I get the 3.0.0.M3 Version - it's the latest, so I can downlaod it with git clone https://github.com/psi-probe/psi-probe

After doing that, I build the succesful the Version: 3.0.0.-SNAPSHOT.

The error already occurs.

Thank you!
Klaus.

-

**Comment by tachtler** [comment]
Hi Jeremy,

thank you for the advise, I will download the probe.war and try them in a few minutes...

Klaus

**Comment by tachtler** [comment]
Hi Jeremy,

## **it works!**

![psi-probe-3 0 0 m3](https://cloud.githubusercontent.com/assets/11161944/16952143/46930d7a-4dc8-11e6-89b4-868b99a5fb3c.png)

Thank you!
Klaus.

**Comment by hazendaz** [comment]
Thanks.  If you have the time and can pick some points from that build date towards mow to help narrow down the issue that would also be great.  Ill get in and try to help in about 12 hours.

It might also be related to web.xml settings.  I think i raised some security setting but would need to confirm.

Get Outlook for Android<https://aka.ms/ghei36>



On Tue, Jul 19, 2016 at 9:49 AM -0400, "Klaus Tachtler" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Jeremy,

it works!

[psi-probe-3 0 0 m3]<https://cloud.githubusercontent.com/assets/11161944/16952143/46930d7a-4dc8-11e6-89b4-868b99a5fb3c.png>

Thank you!
Klaus.

-

**Comment by hazendaz** [comment]
@tachtler Issue is with spring 4.3.x usage.  Haven't isolated the problem yet but will revert shortly if I don't figure it out.

**Comment by hazendaz** [comment]
@tachtler It's related to prototype.js and not using get where appropriate.  By default that uses post and there are a number of spots (memory, logs) that require get instead of post due to parameters being added.  Pre spring 4.3.0 that was allowed or rather ignored from being wrong.  Now it needs to be handled properly.  For now, I have pushed back to 4.2.6 as it will take a bit more testing before I'm comfortable fixing hopefully all the incorrect usages of prototype.  Please let me know if you are able to rebase with master and working again.

Thanks,

Jeremy

**Comment by tachtler** [comment]
Hi Jeremy,

i have cloned the latest **master** via git clone `https://github.com/psi-probe/psi-probe`.

The build was successful and the problems with the
`HTTP Status 405 - Request method 'POST' not supported`
will not be shown.

Your solution to step back to version 4.2.6 of spring was the right choice.

Thank you so much!
Klaus.

**Comment by hazendaz** [comment]
@tachtler I'll let this bake for a minute but if you could check out pull request #766 as that should allow us to move to spring 4.3.1 now and successfully work.  There were two issues.  One was invalid tag of 'webapp' that needed more around it as well as some invalid post usage where gets were the right answer under prototype.  With such glaring issues, I'm not exactly clear as to what spring was previously magically making work.  But at this point, all should be well again.  This should be on master in next few days but if you can check it beforehand to let me know it's good.  Thus far all my tests panned out.
