### ISSUE TITLE
Blank Page / 405 error(s) after psi probe upgraded to spring 4.3.x

### ISSUE THREAD

**Issue by diogosantana** [psi-probe/psi-probe#788]
adm/war.htm is not rendering page after war upload. Content lenght is 0:

```
Request URL:https://mydomain:8443/probe/adm/war.htm
Request Method:POST
Status Code:200 OK
```

```
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
Content-Type: text/html;charset=UTF-8
Content-Language: en
Content-Length: 0
Date: Thu, 18 Aug 2016 18:13:53 GMT
```

**Comment by hazendaz** [comment]
Confirmed this is an issue.  It uploads the war but shows a blank page.  If you can, see if you are getting any specific errors or issues in firebug.  I'll try to do the same if I have time tomorrow.  It's probably related to the upgrade to spring 4.3 if I had to guess.  There are still a few other things broken that I'm looking at.

**Comment by hazendaz** [comment]
I think this is a duplicate issue already reported if it contains this...

WARN {http-apr-9080-exec-49} [o.s.web.servlet.PageNotFound] Request method 'POST' not supported
There are not other error.

**Comment by diogosantana** [comment]
Ok. I can check, but it will take me a few days. Let me know if you get there first.

**Comment by hazendaz** [comment]
It is a duplicated open issue.  405 post error on view after upload to show deploy.  Havent figured out how to control that yet.  It is a direct result of spring 4.3.

Get Outlook for Android<https://aka.ms/ghei36>



On Fri, Aug 19, 2016 at 9:16 AM -0400, "diogosantana" <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok. I can check, but it will take me a few days. Let me know if you get there first.

-

**Comment by hazendaz** [comment]
Seems to me this is probably a spring bug.  I have converted all controllers over to annotations based and it's now working.  I still have a lot of testing to perform and some issues to resolve before I can make that cutover.  It's rather large so I don't want to give an ETA yet but can say it's progressing nicely.  When the dusk settings the control xml file will be empty other than noting to scan for annotations.

**Comment by hazendaz** [comment]
This will be addressed in #811

**Comment by hazendaz** [comment]
Spring 4.3 issue related to this change in ParameterizableViewController

```java
	public ParameterizableViewController() {
		super(false);
		setSupportedMethods(HttpMethod.GET.name(), HttpMethod.HEAD.name());
	}
```

**Comment by hazendaz** [comment]
For reference, see spring for this [commit](https://github.com/spring-projects/spring-framework/commit/135738f9bfb5b9dacf164d6561144589dc98deb8)

I have a hack work around I'll be applying shortly.

**Comment by hazendaz** [comment]
Reopening as place holder as some confirmations from community are necessary to confirm fixed everywhere.

**Comment by hazendaz** [comment]
Closing as unable to produce any others and no further complaints.  If new ones come in they will simply be quickly fixed.
