### ISSUE TITLE
JTA 1.1 (Java 5) dependency used instead of JTA 1.0.1B (Java 1.4)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [psi-probe/psi-probe#81]
```
The JBoss repository changed its JTA 1.0.1B artifact to redirect to JTA 1.1.  
This caused the wrong artifact to be packaged with the 2.0.0 .war file.

In order to ensure that PSI Probe works on Java 1.4, we should package JTA 
1.0.1B with PSI Probe instead of JTA 1.1.
```

Original issue reported on code.google.com by `MALfunct...@gmail.com` on 19 Jan 2010 at 6:44

**Comment by hazendaz** [comment]
This issue was due to JBOSS haven't bad copy.  The current JTA 1.1 is compiled for jdk 1.4.  I've done a full verification and I'm opening an issue noting real problems of not supporting jdk 1.4.
