### ISSUE TITLE
Memory utilization page visualization problem

### ISSUE THREAD

**Issue by diogosantana** [psi-probe/psi-probe#812]
Memory utilization page visualization problem

![image](https://cloud.githubusercontent.com/assets/5445929/19360337/7dbb5c88-9154-11e6-9926-e1c8578658ac.png)

**Comment by hazendaz** [comment]
@diogosantana What is the problem?

**Comment by diogosantana** [comment]
Look the picture, PS Eden Space. 4E8, 3E8, 2E8, 1E8, 0E0.

**Comment by hazendaz** [comment]
Need to be more explixit.  What are you trying to say is wrong there?  I don't specifically know what the numbering means so I'm not understanding what the issue is.  It looks similar to others so not clear on what the issue is.  Do we need a fix?  If so, can you fix the issue you are noticing?
