### ISSUE TITLE
2.4.0.SP1 release war not actually 2.4.0.SP1

### ISSUE THREAD

**Issue by phemmer** [psi-probe/psi-probe#813]
The 2.4.0.SP1 war on the github releases (https://github.com/psi-probe/psi-probe/releases/download/2.4.0.SP1/probe.war) does not appear to actually be 2.4.0.SP1.

Tomcat 8.5 support is completely missing, even though the 2.4.0.SP1 git tag shows it present:
https://github.com/psi-probe/psi-probe/blob/2.4.0.SP1/web/src/main/webapp/WEB-INF/spring-probe-resources.xml#L82

**Comment by hazendaz** [comment]
Sorry tagging is wrong.  2.4.0 is for tomcat 8 and before.  It does not cover 8.5 or 9.0.  Only version 3.0.0 master is currently on 8.5 and 9.0.  There are a couple of bugs at master but generally it is working.  One specific bug is file upload works but fails to show results.  I'll have to update the tagging so will keep this outstanding as a reminder.
