### ISSUE TITLE
javax.sql.XADataSource is not listed

### ISSUE THREAD

**Issue by vgarmash** [psi-probe/psi-probe#815]
Hello.

I installed the latest PSI-Probe into Tomcat 8.5.6 and I noticed that my datasources of type  `javax.sql.XADataSource` are not listed. I have 5 datasources defined like this:

```
<Resource auth="Container" driverClassName="net.sourceforge.jtds.jdbc.Driver" 
        factory="org.apache.tomcat.jdbc.pool.DataSourceFactory" jmxEnabled="true" 
        maxIdle="2" maxTotal="25" name="jdbc/vertex_taxgis" 
        removeAbandoned="true" removeAbandonedTimeout="20" type="javax.sql.XADataSource" 
        url="jdbc:jtds:sqlserver://{{..hidden..}}" 
        username="{{..hidden..}}" password="{{..hidden..}}" 
        validationQuery="select 1" validationQueryTimeout="15"/>
```

 The datasource works fine. It was create according the [The Tomcat JDBC Connection Pool](https://tomcat.apache.org/tomcat-8.5-doc/jdbc-pool.html) documentation. It has the following description for the `type` property:

> Type should always be `javax.sql.DataSource` or `javax.sql.XADataSource`
> 
> Depending on the type a `org.apache.tomcat.jdbc.pool.DataSource` or a `org.apache.tomcat.jdbc.pool.XADataSource` will be created.

So I assumed that if you implemented the datasource adapter according to the specification then it should work. I looked into the source of [psi-probe/core/src/main/java/psiprobe/beans/TomcatJdbcPoolDatasourceAccessor.java](https://github.com/psi-probe/psi-probe/blob/master/core/src/main/java/psiprobe/beans/TomcatJdbcPoolDatasourceAccessor.java) and I found why XADataSource is not listed. It is being filtered out by the following code:

```
@Override
  public boolean canMap(Object resource) {
    return resource.getClass().getName().equals("org.apache.tomcat.jdbc.pool.DataSource")
        && resource instanceof DataSource;
  }
```

The correct version would be:

```
@Override
  public boolean canMap(Object resource) {
    return (resource.getClass().getName().equals("org.apache.tomcat.jdbc.pool.DataSource") ||
             resource.getClass().getName().equals("org.apache.tomcat.jdbc.pool.XADataSource") )
        && resource instanceof DataSource;
  }
```

Please let me know if you can fix that, or you have some objections. I can submit a PR for that too.

P.S. I looked into other datasource adapters and you skipping XADataSource variant for all of them... So If you are agree I can add PRs for each of them.

**Comment by hazendaz** [comment]
@vgarmash Sorry thought I had gotten back with you on this.  If you want go ahead and raise pull requests for this issue.

**Comment by vgarmash** [comment]
@hazendaz Thanks. By the way - @MALfunction84 why you even check the class name? The main reason why this issue exist is because you check full class name in String format. What is the reasoning behind that? Did you have some classes implementing the datasource interface but then not providing correct implementation? Please give more details on that.

**Comment by MALfunction84** [comment]
The reason we check class names is twofold:

1. There is no common interface for all of the things we want to do with a datasource. We have to distinguish so we know which type to downcast to so we can start using its specific API.
2. Attempting to cast to a datasource type that is not present on Tomcat's classpath (like on an older version of Tomcat) will cause the ClassLoader to throw an error. Checking the class's name first helps us avoid attempting to load a nonexistent class.

**Comment by hazendaz** [comment]
I think there is a 3rd reason as well.  If we start coding to something it would require the jars that contain the info to be released with our product.  And that would certainly bloat our product unnecessarily.  Sonar does currently flag that issue but as things go we are trying to solve many needs in one product which can be a bit complicated especially in cases where tomcat changes direction ;)

**Comment by MALfunction84** [comment]
Actually, the datasource libraries are runtime dependencies. We don't bundle them with PSI Probe, but we can use them if they're present in Tomcat's classpath. That's why we do a string comparison on the classname; it might not be on the classpath.

**Comment by vgarmash** [comment]
We do both: `instanceof` && string comparasion. That's what was confusing. `instanceof` implies that we have the class in the classpath but in addition to that we also do the class name as string comparasion. In case of Tomcat JDBC driver it caused exclusion of XADatasource implementation which is class-compatible with non-xa datasource.
That's why I asked this question.
If we use `instanceof` then it should be enough as we don't use any specific implementation.
Viacheslav
On Dec 9, 2016 12:44 AM, Mark Lewis <notifications@github.com> wrote:Actually, the datasource libraries are runtime dependencies. We don't bundle them with PSI Probe, but we can use them if they're present in Tomcat's classpath. That's why we do a string comparison on the classname; it might not be on the classpath.

**Comment by vgarmash** [comment]
We do both: `instanceof` && string comparasion. That's what was confusing. The `instanceof` implies that we have the class in the classpath (you add import of the class you are comparing to) but in addition to that we also do the class name as string comparasion. In case of Tomcat JDBC driver it caused exclusion of XADatasource implementation which is class-compatible with non-xa datasource.
That's why I asked this question.

If we use `instanceof` then it should be enough as we don't use any specific implementation.

**Comment by MALfunction84** [comment]
The string comparison happens before the instanceof, and && short-circuits. This means it doesn't attempt to load the class until after the string comparison succeeds, avoiding the potential ClassNotFoundException.

We could try/catch that exception. TBH, we inherited that implementation from Lambda Probe and it hasn't been scrutinized.

XADataSource is not an extension of DataSource, so we would need a separate implementation.

**Comment by vgarmash** [comment]
Sorry, I didn't provide the full package for Tomcat JDBC datasource when I created my ticket initially. I hoped that you guys take a look and see for yourself. Here are the type hierarchy:
```
Object (java.lang)
 |- DataSourceProxy (org.apache.tomcat.jdbc.pool)
     |- DataSource (org.apache.tomcat.jdbc.pool)
         |- XADataSource (org.apache.tomcat.jdbc.pool)
```
Here is full class from Tomcat JDBC:
```
package org.apache.tomcat.jdbc.pool;

import org.apache.tomcat.jdbc.pool.DataSource;
import org.apache.tomcat.jdbc.pool.PoolConfiguration;

public class XADataSource extends DataSource implements javax.sql.XADataSource {
    public XADataSource() {
    }

    public XADataSource(PoolConfiguration poolProperties) {
        super(poolProperties);
    }
}
```

So I was really confused when I saw this code in `TomcatJdbcPoolDatasourceAccessor` which excludes immediate child of `org.apache.tomcat.jdbc.pool.DataSource`:

```
  @Override
  public boolean canMap(Object resource) {
    return (resource.getClass().getName().equals("org.apache.tomcat.jdbc.pool.DataSource")
        && resource instanceof DataSource; //<-- org.apache.tomcat.jdbc.pool.DataSource, not javax.sql.Datasource if you thought it is. org.apache.tomcat.jdbc.pool.DataSource is the parent class for non-xa and xa datasource version
  }
```

The same is valid for Oracle UCP:
```
PoolDataSource (oracle.ucp.jdbc)
 |- PoolDataSourceImpl (oracle.ucp.jdbc)
     |- PoolXADataSourceImpl (oracle.ucp.jdbc)
```

and here is `OracleUcpDatasourceAssessor`:

```
@Override
  public boolean canMap(Object resource) {
    return ("oracle.ucp.jdbc.PoolDataSourceImpl".equals(resource.getClass().getName())
        && resource instanceof PoolDataSource//<- oracle.ucp.jdbc.PoolDataSource which is parent for non-xa and xa datasources;
  }
```

I always though that if I import the class then it becomes required in the runtime regardless of if it was used or not. I want to test it myself.

Although the fix I suggested above should work fine as I just repeat the class hierarchy.

**Comment by hazendaz** [comment]
There be some magic in the code ;)

@vgarmash Can you raise some pull requests to fix?  I'm also thinking maybe we should do a little house keeping and move datasource accessors into new package.  Possible 'psiprobe.beans.datasources'.  Maybe you can also do that?  Or I can do that after some pull requests...I'm a bit busy in other areas (spring annotations) and very open to more community support especially where it makes sense.  I think everyone uses this differently so there is room for improvement ;)

**Comment by MALfunction84** [comment]
Ah, I misunderstood. `java.sql.XADataSource` (interface) does not extend `java.sql.DataSource` (interface), but `org.apache.tomcat.jdbc.pool.XADataSource` does extend `org.apache.tomcat.jdbc.pool.DataSource`.

As long as we catch any ClassNotFoundExceptions, I think we can safely remove the string comparisons so these implementations can have better compatibility.
