### ISSUE TITLE
Korean translation

### ISSUE THREAD

**Issue by GoogleCodeExporter** [psi-probe/psi-probe#84]
```
Which feature would you like to see enhanced?
Korean translation.

Please describe the enhancement in detail.
Any commented-out property in messages_ko.properties needs to be translated
into Korean
```

Original issue reported on code.google.com by `jungwoop@gmail.com` on 21 Jan 2010 at 9:33

**Comment by hazendaz** [comment]
closing as any language updates were likely added long time ago and certainly no issue is needed as anyone can send a PR if needed
