### ISSUE TITLE
Compatibility with Tomcat Ant tasks

### ISSUE THREAD

**Issue by GoogleCodeExporter** [psi-probe/psi-probe#86]
```
Please describe the feature you would like to see added.
If you use /manager for the url in a Tomcat Ant task, it works.  If you use
/probe, it doesn't work, but it should.

How will this feature make Probe better?
Probe could could truly *replace* the manager.
```

Original issue reported on code.google.com by `MALfunct...@gmail.com` on 22 Jan 2010 at 7:01

**Comment by hazendaz** [comment]
closing as 'ant' is legacy and fact tomcat still uses it is mind boggling.  Other tools are in place to run various tasks and this would need more info than provided here to what is actually wanted besides using legacy tool tomcat has.
