### ISSUE TITLE
Changing the language doesn't work anymore

### ISSUE THREAD

**Issue by tachtler** [psi-probe/psi-probe#905]
Hi,

after click on the flags at the bottom of the site, the language will not change anymore.

Thank you
Klaus.

**Comment by hazendaz** [comment]
Do you get a stack trace on this?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by tachtler** [comment]
Hi Jeremy,

no I don't - but I will build the next days all again and will report more detailed, sorry for my late reply.

Thank you
Klaus.

**Comment by tachtler** [comment]
Hi Jeremy,

Environment has changed - till I update from CentOS-7.2 to CentOS-7.3 (This is only a information):

I will test the latest build, as soon as possible!

```
Systeminformationen
JVM:  OpenJDK Runtime Environment  1.8.0_111-b15  OpenJDK 64-Bit Server VM)
Betiebssystem: Linux (unknown) amd64 3.10.0-327.36.3.el7.x86_64
Anzahl CPUs: 2
Systemzeit: Wed Dec 21 10:22:00 CET 2016
Arbeitsverzeichnis: /usr/share/tomcat
Informationen des Containers
Container: Apache Tomcat/7.0.69
catalina.base: /usr/share/tomcat
catalina.home: /usr/share/tomcat
Applikationsverzeichnis: /usr/share/tomcat/webapps
Basiskonfiguration /usr/share/tomcat/conf/localhost
```
Thank you
Klaus.

**Comment by tachtler** [comment]
Hi Jeremy,

the problem still exists... but no error logging in any log files, as far as I can see!

Sorry for that bad news.

Thank you
Klaus.

**Comment by hazendaz** [comment]
This is a result of #904.  I'm looking into issue now...
