### ISSUE TITLE
Counted wrapper properties should be sorted numerically

### ISSUE THREAD

**Issue by GoogleCodeExporter** [psi-probe/psi-probe#93]
```
This is a minor wart, the properties under "System Information > Wrapper
Control" that are counted (see below) should be sorted in numerical order.

IS:
wrapper.java.additional.1
wrapper.java.additional.10
...
wrapper.java.additional.2
...


SHOULD BE:
wrapper.java.additional.1
wrapper.java.additional.2
..
wrapper.java.additional.9
wrapper.java.additional.10
...

```

Original issue reported on code.google.com by `jh.web...@gmail.com` on 19 Feb 2010 at 11:47

**Comment by hazendaz** [comment]
closing as old issue, feel free to reopen if needed and willing to contribute a fix.  For this type of thing, for what I can see in our defaults, if I see area of concern, I'll make sure to sort for ease of reading if not already.
