### ISSUE TITLE
Found a graphical/css problem...

### ISSUE THREAD

**Issue by tachtler** [psi-probe/psi-probe#984]
Hi,

Click on PATH: Application | Choose application /probe for example | TAB (on the right) Sessions | Click on any listed session id ... 

URL: 

> /probe/attributes.htm?webapp=%2fprobe&sid=5885DE046B01FA8DA340A11CB233D78E&size=

![psi-probe-sessions](https://cloud.githubusercontent.com/assets/11161944/21847353/bd859b7e-d7fb-11e6-9527-51b3a9d603f2.png)

That's what I found, but I can not test everything, because I have no database configuration, cluster or any certificates inside my tomcat installation @home. Sorry for that.

Thank you
Klaus.

**Comment by hazendaz** [comment]
So in your case, I believe you are referring to the right side links under application hovering over grid.  I'm not able to replicate that.  What sort of resolution are you using?

**Comment by tachtler** [comment]
Hi Jeremy,

I'm using a screen resolution 1280x1024 on a 17" Monitor.

Klaus.

**Comment by hazendaz** [comment]
I'm really busy right now but if you have some time and code figure that out would be great to see a pull request.  At the current, I'm pretty much only going to be in here updating versions and any major flaws (not that this isn't major!).

**Comment by tachtler** [comment]
Hi Jeremy,

I am also very busy in my profession, so that will be able to handle the topic later.

Klaus.

**Comment by hazendaz** [comment]
Closing as monitor size was small then and it's been 3 years so likely things look better today.  If still an issue, please review on latest and open new ticket.
