### ISSUE TITLE
Deploying anything results in blank screen.

### ISSUE THREAD

**Issue by tonywestonuk** [psi-probe/psi-probe#985]
Deploy a war using the Deploy screen.

Once deployed, a blank page is shown with no indication if the war was deployed or not.  

However, the war does actually deploy fine.

**Comment by hazendaz** [comment]
This was fixed on 3.0.0.rc1 and further rated issues were all fixed on current master.  Please try those versions.

Get Outlook for Android<https://aka.ms/ghei36>



On Wed, Jan 11, 2017 at 7:23 AM -0500, "tonywestonuk" <notifications@github.com<mailto:notifications@github.com>> wrote:


Deploy a war using the Deploy screen.

Once deployed, a blank page is shown with no indication if the war was deployed or not.

However, the war does actually deploy fine.

**Comment by hazendaz** [comment]
3.0.0 rc2 will be likely released in next week after I've had a chance to look at other defects.  That will at least provide an official build where we believe issues like this are resolved.

Get Outlook for Android<https://aka.ms/ghei36>



On Wed, Jan 11, 2017 at 7:23 AM -0500, "tonywestonuk" <notifications@github.com<mailto:notifications@github.com>> wrote:


Deploy a war using the Deploy screen.

Once deployed, a blank page is shown with no indication if the war was deployed or not.

However, the war does actually deploy fine.

**Comment by hazendaz** [comment]
Closing as issue was fixed a while back.  It was related to changes in spring latest version and we have added an extension of spring for paramertized views so that we can allow proper http requests to work.
