### ISSUE TITLE
Set preferred language on probe from browser settings... (Feature Request?!?)

### ISSUE THREAD

**Issue by tachtler** [psi-probe/psi-probe#986]
Hi,

when I enter the web application /probe, it would be nice, if the preferred language from the browser setting would be honored by psi-probe.

Thank you!
Klaus.

**Comment by hazendaz** [comment]
I'm super busy right now with other things but love the idea.  If this is something you could assist in getting going, that would be great!

**Comment by tachtler** [comment]
Hi Jeremy,

maybe I can help, but I use for my projects struts2, so I have to realize, how to do that without my favorite framework ;-)

Klaus.

**Comment by tachtler** [comment]
Hi Jeremy,

is it a good idea to change the following lines to set the Browser locale as default, when psi-probe site was visited first by the user, or I'm totally wrong with that place?

(It's on:  psi-probe/core/src/main/java/psiprobe/ProbeConfig.java )

**Actual:**
```
  /**
   * Gets the cookie locale resolver.
   *
   * @return the cookie locale resolver
   */
  @Bean(name = "localeResolver")
  public LocaleResolver getLocaleResolver() {
    logger.debug("Instantiated cookieLocaleResolver");
    CookieLocaleResolver resolver = new CookieLocaleResolver();
    resolver.setDefaultLocale(Locale.ENGLISH);
    return resolver;
}
```
**Request:**
```
  /**
   * Gets the cookie locale resolver.
   *
   * @return the cookie locale resolver
   */
  @Bean(name = "localeResolver")
  public LocaleResolver getLocaleResolver() {
    logger.debug("Instantiated cookieLocaleResolver");
    CookieLocaleResolver resolver = new CookieLocaleResolver();
    resolver.setDefaultLocale(org.springframework.context.i18n.LocaleContextHolder.LocaleContextHolder.getLocale());
    return resolver;
}
```
(I also specified org.springframework.context.i18n in the above example, that you can see the class...)

Sorry, but I'm not familiar with the Spring Framework!

Thank you!
Klaus.

**Comment by tachtler** [comment]
Hi Jeremy,

or  only the following configuration must be done?
```
<bean class="org.springframework.web.servlet.i18n.AcceptHeaderLocaleResolver" id="localeResolver">
</bean>
```
(It's on: psi-probe/core/src/main/java/psiprobe/ProbeConfig.java )

Thank you!
Klaus.

**Comment by hazendaz** [comment]
We only use java config for spring now so it would go in the code.  Xml is essentially obsoleted.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by tachtler** [comment]
H Jeremy,

I found following article on stackoverflow, maybe there is the right description, how it could be done on psi-probe too?

[https://stackoverflow.com/questions/27580502/spring-mvc-redirect-user-according-to-browser-language?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa](https://stackoverflow.com/questions/27580502/spring-mvc-redirect-user-according-to-browser-language?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa)

(2 Answer)

> What about something like this in your controller:
> 
> @RequestMapping("/path")
> public String someMapping(Locale locale) {
>     if ("de".equals(locale.getLanguage())) {
>         return "redirect:http://de.example.com/some/path";
>     }
> }

**or** (last entry)

> Create a HandlerInterceptor (extend [HandlerInterceptorAdapter](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/servlet/handler/HandlerInterceptorAdapter.html)) and get the Accept-Language
> header from the Request. You need to register your Interceptor in your Web Application Context 
> Config.
> 
> You also want to know what domain your server is running on. See [How to get domain URL and 
> application name](https://stackoverflow.com/questions/2204870/how-to-get-domain-url-and-application-name)?
> 
> You should allow the user to change their locale (they might want your site in German even if
> browser is set to en_US). So you'd need to set a cookie in this case. See [LocaleChangeInterceptor](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/servlet/i18n/LocaleChangeInterceptor.html) 
> too.

Maybe there is a solution?

Thank you
Klaus.

**Comment by hazendaz** [comment]
closing as it sounds like the implementation is correct here.  Spring states it uses the default locale as fallback if it didn't have one provided in the header.  If still an issue as its been 5 years, please reopen new ticket after checking our latest.
