### ISSUE TITLE
Wrong flag are shown on Applications | (choose any app) | Sessions...

### ISSUE THREAD

**Issue by tachtler** [psi-probe/psi-probe#987]
Hi,

when I open psi-probe and click on Applications | (choose any app) | Sessions, on private IP addresses, a flag was shown. I would be better to present NO flag, or a neutral flag.

See screen shot below:
![psi-probe](https://cloud.githubusercontent.com/assets/11161944/21918462/e02c079c-d951-11e6-97cb-c08a573c480f.png)

Maybe, following "unknown" flag symbol could be used (it was made by myself, you can use it, if you want):

![flag-unknown](https://cloud.githubusercontent.com/assets/11161944/21918488/17634a54-d952-11e6-926b-a41266c9956c.png)

See my **Pull Request**: https://github.com/psi-probe/psi-probe/pull/988

Thank you!
Klaus.

**Comment by hazendaz** [comment]
So what I did was default to system setup value if it was unknown.  Obviously not a perfect solution for global usage.  While I'm on board with your idea of a unknown flag, I'd like something with a little more snap too it.  Not sure if there is something like a generic 'private' styled flag or if we could go a step further and provide some way to provide ones one flag so we could show a company emblem or something like that.

**Comment by tachtler** [comment]
Hi Jeremy,

maybe we could found a free to use picture and/or modify that. I will search for that, if I have a little bit more time for that.

Klaus.

**Comment by hazendaz** [comment]
closing as no follow up since, think this may have been resolved though.
