### ISSUE TITLE
Certificates do not show in tomcat 8.5+ using new XML configuration

### ISSUE THREAD

**Issue by hazendaz** [psi-probe/psi-probe#989]
With tomcat changes for how SSL is setup, we need to support the change.  At the moment it simply pulls up empty page with note of the type only and there are no errors best I could tell.

**Comment by hazendaz** [comment]
@diogosantana I'd really love to see you come back in here with some additional features.  With tomcat 8.5+ new SSLHostConfig, if we configure that we are not able to use trustStore or certificates tab effectively.  It knows the connector and shows it but then doesn't find anything to display.

**Comment by Meatwad** [comment]
I'm not seeing the certificates using the traditional NIO configuration either against Tomcat 8.5.11.  
I get "**HTTPS-JSSE-NIO-8443**" at the top of the screen and that's it.

**Comment by hazendaz** [comment]
@Meatwad Yes, I have confirmed that as well.  It simply doesn't work on tomcat 85 or 9 at the current time.  I don't have a lot of time to look into this currently but if you happen to have some time on your hands and could try to get a fix on this that is backwards compatible, I'd be more than happy to merge it.  Otherwise I'm affraid this might exist for a while.

**Comment by Meatwad** [comment]
Thanks everyone!  I went on a voyage of discovery and learned how to install Maven and compile from source.  I am seeing the certificates now (at least in NIO mode) from Tomcat 8.5.11.   You are awesome.

**Comment by hazendaz** [comment]
Special thanks goes to @diogosantana for pulling off original addition of certificates in probe as well as getting this going in tomcat 8.5+.  This should now be working no matter the version.  We just recently started rolling out tomcat 8.5 usage and where in a bad spot having had this then lost it.  So glad it's back and in time for us to apply it ;)
